
		
		<div class="body_main_container pos_relative">
			<div class="body_middle_container body_mar_b">
				<div class="body_top_height_start">
					<div class="text_row mycolleection">
						<div class="float_l"><h2>MANAGE MY DTABOX</h2></div>
						<div class="float_r"><P class="number_count">0/10&nbsp;&nbsp;<a href="<?php echo $baseUrl; ?>/databox/category-choice">Create</a></P></div>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
		<div class="body_main_container">
			<div class="body_middle_container body_mar_b">
				<div class="create_databox">
					<h3>no donuts. <br/>No Databoxes created :/</h3>
					<a href="<?php echo $baseUrl; ?>/databox/category-choice"><img src="<?php echo $basePath; ?>/images/social_media/databox_create.png"/></a>
					<h4>CLICK THE DONUT TO CREATE</h4>
				</div>
			</div>
		</div>

	<div class="clearfix"></div>
	