<link href="<?php echo $basePath; ?>/css/default.css" rel="stylesheet" type="text/css" />
	<div class="montage_container">
		<div class="body_middle_container body_mar_b">
	<div class="body_main_container">
		<div class="body_middle_container body_mar_b">
		<?foreach($this->dashboard as $key=>$dashboard){$count=0;?>
		<input type="hidden" id="totalCount<?echo $key;?>" name="totalCount<?echo $key;?>" value="<?echo $dashboard['totalLinks'];?>">
			<input type="hidden" id="presentCount<?echo $key;?>" name="presentCount<?echo $key;?>" value="7">
			<div class="tg_montage_t montage_brg_box">
			<div class="montage_box_brg_title">
				<div class="text_row">
					<div class="float_l"><h3><?echo $dashboard['user_hashname']?><span>&nbsp;(<?echo $dashboard['totalLinks']?>/100)</span></h3></div>
					<div class="float_r"><P><?echo $dashboard['category_title']?></P></div>
				</div><div class="clearfix"></div>
			</div>
			<div class="pos_relative">
				<div class="montage_row" id="montageRow<?echo $key;?>">
				<?foreach($dashboard['links'] as $links){
				$count++;
				if($count){
					$link=explode('***',$links);
					?>
					<div class="column1">
						<div><p><?echo substr($link[0],0,20) . '...';$url = $link[0];?></p>
						<a href="<?php echo $url; ?>" target="_blank"><img src="<?php if($link[2]!=""){echo $link[2];}else{ echo $basePath;?>/images/social_media/noimage.png<? } ?>"/></a></div>
					</div>
				<?}}?>
				</div>
				<div class="clearfix"></div>
			</div>
			</div>
			<?}?>
		</div>
	</div>
		</div>
	</div>
</div>
<div class="clearfix"></div>
<input type="hidden" id="hid_userid"  name="baseUrl" />
<input type="hidden" id="hid_cat_id"  name="baseUrl" />
<input type="hidden" id="category_user_id" value="0" />
<input type="hidden" id="report_id_hid" name="report_id_hid" value="0">
