<div class="content-wrapper">
 <!-- Content Page header and breadcrumbs) -->
	<section class="content-header">
		<div class="container mm_hide">	
		</div>
	</section>
	 <div class="container">
		<section class="content" style="min-height:600px;">
			<div class="row">
			<div class="error-page" style="margin-top:100px;">
            <h2 class="headline text-red"> 404</h2>
            <div class="error-content">
              <h3><i class="fa fa-warning text-red"></i> Oops! Page not found.</h3>
              <p>
                We could not find the page you were looking for.
                Meanwhile, you may <a href="https://taggerzz.com">return to home</a>.
              </p>
            </div><!-- /.error-content -->
          </div><!-- /.error-page -->
			</div>
		</section>
	</div>