<?php
	$tzCatImage = $basePath . "/img/defaultImg.png";
	if ( isset($this->editBoxId) && trim($this->editBoxId) != "" && is_numeric($this->editBoxId) && $this->editBoxId )
	{
		if( isset($this->tzCatImage) && trim($this->tzCatImage) != "" && $this->tzCatImage != "montage_default_img.png" )
		{
			$tzCatImage = $basePath . "/images/project/categoryImages/" . $this->tzCatImage;
		}
	}
?>
	<input type="hidden" id="basePath" name="basePath" value="<?php echo $basePath;?>" />
	<input type="hidden" id="baseUrl"  name="baseUrl" value="<?php echo $baseUrl;?>" />

	<input type="hidden" id="submitVal" name="submitVal" value="Go" />
	<input type="hidden" id="privateSVal" name="submitVal" value="Go" />
	<input type="hidden" id="publicSVal" name="submitVal" value="Go" />
	<input type="hidden" id="totalUrlsEntered" name="totalUrlsEntered" value="0" />
	<input type="hidden" id="allOkUrlCount" name="allOkUrlCount" value="0" />
	<input type="hidden" id="urlsDisplayCount" name="urlsDisplayCount" value="0" />
	<input type="hidden" id="submitClicked" name="submitClicked" value="0" />
	<input type="hidden" id="originalValue" name="originalValue" value="" />
	<input type="hidden" id="pvtCodeClicks" name="pvtCodeClicks" value="-1" />
	<input type="hidden" id="finalnvalidCount" name="finalnvalidCount" value="0" />

        <div id="mainContainerWrapper" class="mainContainerWrapper tmar_t125">

            <!-- This div is to include the header.html page 
            <div id='divIncludeContent'></div>-->
			<form id="linksForm" name="linksForm" method="post" enctype="multipart/form-data">
					<input type="hidden" id="editBoxId" name="editBoxId" value="<?php if ( isset($this->editBoxId) && trim($this->editBoxId) != "" ){ echo $this->editBoxId; }?>" />
					<input type="hidden" id="formUseMode" name="formUseMode" value="3" />
					<input type="hidden" id="categoryName" name="categoryName" value="" />
					<input type="hidden" id="categoryHighlight" name="categoryHighlight" value="2" />
					<input type="hidden" id="catTitle" name="categoryTitle" />
					<input type="hidden" id="categoryType" name="categoryType" value="0" />
					<input type="hidden" id="catHashTag" name="catHashTag" />
					<input type="hidden" id="uniqueCode" name="uniqueCode" />
					<input type="file" name="catImageFile" id="catImageFile" style="display:none;">
					<input type="hidden" id="hashNote" name="hashNote" />
					<input type="hidden" id="metaTags" name="metaTags" value="<?php if ( isset($this->metaTags) && trim($this->metaTags) != "" ){ echo $this->metaTags; }?>" />
					<input type="hidden" id="custTypeId" name="settingId" value="3" />
					<input type="hidden" id="matureContent" name="matureContent" value="<?php if ( isset($this->mature_content) && trim($this->mature_content) != "" ){ echo $this->mature_content; }?>" />
					<input type="hidden" id="notSafeForWork" name="notSafeForWork" value="<?php if ( isset($this->not_safe_for_work) && trim($this->not_safe_for_work) != "" ){ echo $this->not_safe_for_work; }?>" />
					<input type="hidden" id="linkPostFormation" name="linkPostFormation" value="1" />
					<input type="hidden" id="imageId" name="imageId" value="0" />
					<input type="hidden" id="typeImageCrop" name="typeImageCrop" value="0" />
					<input type="hidden" id="main_category" name="main_category" value="" />
					<input type="hidden" id="description123" name="description123" />

			</form>
            <section id="secCreateHighlight">
                <div id="divCreateHighlightWrapper" class="divCreateHighlightWrapper">
                    <div class="heading">Creating Your Highlight</div>
                    <div class="divCreateHighlightHashtag">
                        <span><h4>Hashtag</h4></span>
                        <input type="text" id="hashtagHolder" class='inptHashtag' placeholder="#hashtag" value="<?php if(isset($_SESSION['databox']->hashtag)){ echo $_SESSION['databox']->hashtag ;}?>" />
                    </div>
                    <div class="divCreateHighlightTitle">
                        <span><h4 style="margin:0">Title</h4> </span>
                        <input type="text" id='titleHolder' class='inptTitle' placeholder="Title of the collection" value="<?php if(isset($_SESSION['databox']->hashtitle)){ echo $_SESSION['databox']->hashtitle ;}?>" />
                    </div>
					<div class="divCreateHighlightHashtag">
                        <span><h4 id="linksCountPlus"><?php echo $this->countOfLinks;?>/100 Hot Links</h4></span>
                        <input type="text" id='DescriptionTitle' name="DescriptionTitle" class='inptTitle' placeholder="Aritcles, Videos, News" value="<?php if(isset($this->user_classification)){ echo $this->user_classification;}?>" />
                    </div>
					<div id="textBoxesGroup"><?
							if( isset($this->boxLinksArr) && count($this->boxLinksArr) > 0 )
							{
								$extraBoxUrlId = 0;
								$urlId = 1;
								foreach($boxLinksArr as $key=>$currBoxLink)
								{
									$currentLinkArray=explode("\t",$currBoxLink["current_db_info"]);
									// echo count($currentLinkArray);
									if( (!is_numeric ($currentLinkArray[1])) && (trim ($currentLinkArray[1]) != "") )
									{
										$url_id = 0;
										if( $currentLinkArray[0] == 0 )
										{
											$url_id = $urlId++;
										}
										else
										{
											$url_id = $currentLinkArray[0];
										}
										$extraBoxUrlId = $url_id;
										
										// echo $currentLinkArray[1];
										if($currentLinkArray[7]==0){
											$imageValue='checkmark_wrong.png';
										}else{
											$imageValue='manage_checking.png';
										}
						?><div class='divCreateHighlightLinks' id="textBoxDiv<?echo $url_id;?>">
											<input type="text" class="inptLinks" placeholder="Ex:- http://www.google.co.in" id="textbox<?echo $url_id;?>" value="<?echo $currentLinkArray[1];?>" <?php if(!isset($_GET['type']) && $_GET['type']!='refresh' ){ ?>onBlur="resetUrlStatus('<?echo $url_id;?>','0');" <?php } ?>>
											
											<span style="display:none" id="loadImg<?echo $url_id;?>"><img style="vertical-align:middle;width:15px;" src="<?php echo $basePath; ?>/img/bx_loader.gif" /></span>
											<span id="verifyImg<?echo $url_id;?>"><img id="imgVerified<?echo $url_id;?>" src="<?php echo $basePath; ?>/img/<?echo $imageValue;?>" /></span>
											<b id="rem<?echo $url_id;?>"><a href="javascript:void(0);" onClick="removeTextBox('<?php echo $url_id; ?>',1)"><img src="<?php echo $basePath; ?>/img/dashboard_delete.png" /></a></b>
										</div><?php
									}?>
									<?php if(isset($_GET['type']) && $_GET['type']=='refresh' ){ ?>
								<script>	
								$(document).ready(function () {
									resetUrlStatus('<?php echo $url_id;?>','edit');
								});
								</script>
									
								<?php } ?>
								<?php }?><div class='divCreateHighlightLinks' id="textBoxDiv<?php echo $extraBoxUrlId + 1; ?>">
							<input type="text" class="inptLinks" placeholder="Ex:- http://www.google.co.in" id="textbox<?php echo $extraBoxUrlId + 1; ?>" onBlur="resetUrlStatus('<?php echo $extraBoxUrlId + 1; ?>','0');" >
							<span style="display:none" id="loadImg<?php echo $extraBoxUrlId + 1; ?>"><img style="vertical-align:middle;width:15px;" src="<?php echo $basePath; ?>/img/bx_loader.gif" /></span>
							<span id="verifyImg<?php echo $extraBoxUrlId + 1; ?>"></span>
							<b id="rem<?php echo $extraBoxUrlId + 1; ?>"></b>
						</div><?php }
						else
						{
						?><div class='divCreateHighlightLinks' id="textBoxDiv1">
							<input type="text" class="inptLinks" placeholder="Ex:- http://www.google.co.in" id="textbox1" onBlur="resetUrlStatus(1);" />
							<span style="display:none" id="loadImg1"><img style="vertical-align:middle;width:15px;" src="<?php echo $basePath; ?>/img/bx_loader.gif" /></span>
							<span id="verifyImg1"></span>
							<b id="rem1"></b>
						</div><?php } ?>
                    </div>
                    <div class="divCreateHighlightImage">
                       <h4><span class="">Image </span><span class="smallFont dimFontColor"> ( related to your collection / sharing )</span></h4>
                        <button class="primaryButton" id="cropBoxImage">UPLOAD IMAGE</button>
                        <img src="<?php echo $tzCatImage; ?>" alt="" id="uploadedCatImage1"/>
                    </div>
					<div class="divCreateHighlightImage">
						<span class=""><h4>Categorizing Keywords for your Databox/Highlight</h4></span><br />
                        <input type='text' id="boxCategory" class="inptContentCategory input_pad5" placeholder="Ex:- 'Space Travel Astronomers' " value="<?php if ( isset($this->metaTags) && trim($this->metaTags) != "" ){ echo $this->metaTags; }?>" />
					</div>
                    <div class="">
                        <div class="" id="dcHtmlDiv">
						<a href="javascript:void(0)" id="databoxContinue" class="btnBlack right"/>CONTINUE CUSTOMISING</a></div>
						<div id="dcInprogressDiv" style="display:none;text-align:right"><img  style="vertical-align:middle;margin-right:3px;width:30px;" src="<?php echo $basePath; ?>/img/bx_loader.gif" />Saving Category...</div>
                    </div>
                </div>
            </section>
        </div>

		<!--Book Marks-->
		<?php
			if( $this->fetchedLinksCount > 0 )
			{
		?>
				<div id="bookmarksLoadingDiv" class="bookmarks_loading">
					<div class="pop">
						<img src="<?php echo $basePath; ?>/images/social_media/bx_loader.gif" />
						<p>Fetching Your Bookmarks</p>
					</div>
				</div>
		<?php
			}
		?>
		<div id="pop-up-bookmarks" style="display:none;">
		<? echo $this->htmlBook; ?>
		</div>
		<!--END-->

<script type="text/javascript" src="<?php echo $basePath; ?>/js/popupwindow.js"></script>
<script type="text/javascript" src="<?php echo $basePath; ?>/js/project/databox-common.js"></script>
<script type="text/javascript" src="<?php echo $basePath; ?>/js/project/links-dready.js"></script>
<script type="text/javascript" src="<?php echo $basePath; ?>/js/alert-meassage.js"></script>

<script src="<?php echo $basePath; ?>/js/crop/jquery.cropit.js"></script>

<div id="pop-up-image-crop-new" class="pop-up-display-content conform_popup_content" style="margin-bottom:20px;margin-top:20px;">
	<div class="pop_up_haeding close"><h3>CROP IMAGE </h3><span onclick="selectHighCropImage();">Upload Image</span></div>
	<input type="file" id="HighCropInp" class="cropit-image-input" style="display:none;" onchange="showHighCropButton()" />
	<div class="cropit-image-preview-container">
		<div id="crop_heigh" class="cropit-image-preview"></div>
	</div>
	<p style="text-align:center"><input type="range" class="cropit-image-zoom-input" /></p>
	<button class="export">Crop</button><span id="l_i_c" style="display:none;"><img src="<?php echo $basePath; ?>/images/social_media/bx_loader.gif" /></span>
</div>
<input type="hidden" id="cropImage1" name="cropImage1" value="0" />
<link rel="stylesheet" type="text/css" href="<?php echo $basePath; ?>/js/crop/cropit.css" />

<script>

function checkHighImageLoaded()
{
	var filename = $('#HighCropInp').val();
	
	var invalidExtension = false;
	
	if( filename.trim() != "" )
	{
		filename = filename.toLowerCase();
		var fnameArray = filename.split( "." );
		if( parseInt(fnameArray.length) > 0 )
		{
			if( (fnameArray[fnameArray.length-1] != "gif") && (fnameArray[fnameArray.length-1] != "jpg") && (fnameArray[fnameArray.length-1] != "jpeg") && (fnameArray[fnameArray.length-1] != "bmp") && (fnameArray[fnameArray.length-1] != "png") && (fnameArray[fnameArray.length-1] != "bpg") && (fnameArray[fnameArray.length-1] != "tiff") && (fnameArray[fnameArray.length-1] != "ppm") && (fnameArray[fnameArray.length-1] != "pgm") && (fnameArray[fnameArray.length-1] != "pbm") && (fnameArray[fnameArray.length-1] != "pnm") && (fnameArray[fnameArray.length-1] != "webp") )
			{
				invalidExtension = true;
			}
		}
		if( invalidExtension )
		{
			alert( crop_input_valid_file );
			$('#HighCropInp').value='';
			return false;
		}
	}
	return true;
}


$(function() {
	$('#pop-up-image-crop-new').cropit({
		imageBackground: true
	});
	$('.export').click(function() {
		var src = $('#pop-up-image-crop-new').cropit('export');
		var fetchUploadedUrl = BASE_URL+'/upload-montage-image';
		var imageId=$('#imageId').val();
		$("#l_i_c").show();
		$.ajax({
			type	: "POST",
			url		: fetchUploadedUrl,
			data	: { data: src,page:'predefined',imageId:imageId},
			success: function(data){
				$("#l_i_c").hide();
				$('#pop-up-image-crop-new').popUpWindow({action: "close"});
				$('#uploadedCatImage1').attr('src', src);
				$('#typeImageCrop').val(1);
				$('#imageId').val(data.imageId);
				if(chkvalues==0){
					chkvalues=2;
				}
			}
		});
		//window.open(imageData);
	});
});

</script>
