<div class="tdatabox_reviews">
	<div class="databox_reviews_w97">
		<h2>COMMENTS</h2>
		<?php if(isset($_SESSION['usersinfo']->userId)){?>
			<div class="">
				<textarea id="message" class="" placeholder='Enter your comment'></textarea>
				<div class="comment_btn_bg">
					<button id="commentSend" onClick="insertComment()" class="btn">COMMENT SEND</button>
					<input type="hidden" id="hidSendComment" value="0" >
				</div>
			</div>
		<?php } ?>
		<?php if(count($this->getComments)!=0){foreach($this->getComments as $getComments){ 
		?>
			<div id="commentsList">
				<div id="comment<?php echo $getComments['databox_comment_id'];?>"class="">
					<div class="row tmar_b20">
						<div class="rimg_left"><img  width="55px" src="<?php echo $basePath; ?>/images/project/montageImages/<?php echo $getComments['montage_image']; ?>" alt="" class="height100" /></div>
						<div class="rcontenleft">
							<div class="name_c"><?php echo $getComments['display_name']; ?></div>
							<span id="commText<?php echo $getComments['databox_comment_id'];?>"><?php echo $getComments['databox_comment']; ?></span><br/>
							<?php if(isset($_SESSION['usersinfo']->userId)){if($_SESSION['usersinfo']->userId==$getComments['comment_user_id']){?><br/>
								<div class="comment_btns_pos_ab">
									<button class="comment_edit_btn" onClick="editComment('<?php echo $getComments['databox_comment_id']?>','<?php echo $getComments['databox_comment']; ?>')">Edit</button> 
									<button id="deleteComment<?php echo $getComments->databox_comment_id;?>" 
									class="comment_delete_btn" onClick="deletedComment(<?php echo $getComments['databox_comment_id'];?>)">Delete </button>
								</div>
							<?php } else{ ?>
								<div class="comment_btns_pos_ab">
									<button id="replyComment<?php echo $getComments['databox_comment_id'];?>" 
									class="comment_edit_btn" onClick="replyComment(<?php echo $getComments['databox_comment_id'];?>)">Reply</button>
								</div>
							<?}}else{}?>
							<span id="replay_content"></span>
							<div style="display:none;margin-left:8%;" id="replyDiv<?php echo $getComments['databox_comment_id'];?>">
								<textarea id="msg<?php echo $getComments['databox_comment_id'];?>" class="" placeholder='Enter your replay'></textarea>
								<div class="comment_btn_bg">
									<button id="reCommentSend<?php echo $getComments['databox_comment_id'];?>" onClick="insertReplyComment(<?php echo $getComments['databox_comment_id'];?>)" class="btn">Reply SEND</button>
									<input type="hidden" id="hidReplySendComment" value="0" >
									<input type="hidden" id="hidUpReplySendComment" value="0" >
									<input type="hidden" id="parentCid" value="0" >
								</div>
							</div>
						</div>
					</div>
				</div>			
				<div class="clearfix"></div>
			</div>
			<? if(isset($getComments['sub']) && count($getComments['sub'])>0){ foreach($getComments['sub'] as $getCommentss){ ?>	
				<span id="insert_div"></span>			
				<div id="reCommentsList<? echo $getCommentss['databox_comment_id']; ?>" style="margin-left:5%;">
					<div id="reComment<?php echo $getCommentss['databox_comment_id'];?>"class="">
						<div class="row tmar_b20">
							<div class="rimg_left"><img  width="55px" src="<?php echo $basePath; ?>/images/project/montageImages/<?php echo $getCommentss['montage_image']; ?>" alt="" class="height100" /></div>
							<div class="rcontenleft">
								<div class="name_c"><?php echo $getCommentss['display_name']; ?></div>
								<span id="reCommText<?php echo $getCommentss['databox_comment_id'];?>"><?php echo $getCommentss['databox_comment']; ?></span><br/>
								<?php if(isset($_SESSION['usersinfo']->userId)){if($_SESSION['usersinfo']->userId==$getCommentss['comment_user_id']){?><br/>
									<div class="comment_btns_pos_ab">
										<button class="comment_edit_btn" onClick="editReComment('<?php echo $getCommentss['databox_comment_id']?>','<?php echo $getCommentss['parent_comment_id']; ?>')">Edit</button> 
										<button id="deleteComment<?php echo $getCommentss['databox_comment_id'];?>" 
										class="comment_delete_btn" onClick="deletedReComment(<?php echo $getCommentss['databox_comment_id'];?>)">Delete </button>
									</div>
								<?php }} else{}?>
							</div>
						</div>
					</div>			
					<div class="clearfix"></div>
				</div>
			<?}}?>
		<?php } } ?>
	</div>
</div>