<link rel="stylesheet" href="<?php echo $basePath; ?>/css/new_css/gridstack.min.css"/>
<style>
.grid-stack > .grid-stack-item > .grid-stack-item-content{
	overflow-y:hidden;
}
</style>
<?php 
global $layoutTitle;
global $layoutUrl;
global $layoutImage;
global $layoutDescription;
$layoutUrl=$baseUrl.$_SERVER['REDIRECT_URL'];
$layoutTitle = $this->hashName . " | " . $this->categoryTitle;
$layoutImage=$basePath.'/images/project/categoryImages/'.$this->ImageNumber .'.jpg';
$layoutDescription = "";
if( isset($this->categoryDescripton) )
{
	if( strlen($this->categoryDescripton) > 600 )
	{
		$layoutDescription = substr($this->categoryDescripton,0,600) . '...';
	}
	else
	{
		$layoutDescription = $this->categoryDescripton;
	}
}
global $isPrivateBox;
if( isset($this->isPrivateDatabox) && ($this->isPrivateDatabox == 0) )
{
	// echo "<pre>";print_r($this->isPrivateDatabox);exit;
	$isPrivateBox = "Yes";
}
if( isset($this->boxKeywords) && trim($this->boxKeywords) != "" )
{
	global $layoutKeywords;
	$layoutKeywords = $this->boxKeywords;
}
?><body>

<div id="mainContainerWrapper" class="mainContainerWrapper" style="width:95%;margin:125px auto;">
	<section id="secCustomizeDatabox">
		<div class="c_DivCustomizationWrapper">
				<span id="pubDddContainer">
				<?php if($this->data==0){?>
					<div id="drag-drop-demo" class="grid-stack c_DivCardsWrapper customize_w"><?php $tzGsRowNum= 1;
					
					$tzDataGsX = 0;
					$tzDataGsY = 0;
					foreach($this->userCollectedLinksArr as $key=>$databoxLinksGrids)
					{
					//echo "<pre>";print_r($databoxLinksGrids);exit;
						$xSet = 0;$ySet = 0;
						if($key==0){?>
						<input type="hidden" value="<?echo $databoxLinksGrids['collector_id'];?>" id="category_user_id">
						<input type="hidden" value="<?echo $databoxLinksGrids['user_category_id'];?>" id="category_id">
						<?}
						
							$titleclass="img_title_pos_ab";
							$descriptionclass="img_desc_pos_ab";
						?>
						<? if(strpos($databoxLinksGrids['link'], "https://") !== false || strpos($databoxLinksGrids['link'], "http://") !== false){
							$url=$databoxLinksGrids['link'];
						}
						else{
							$url='http://'.$databoxLinksGrids['link'];
						}?>
						<?php $videoHeightReduce = false;
						$imageSocialAlone="";
						$valueSocialAlone=0;
						if(isset($databoxLinksGrids['image']) && $databoxLinksGrids['image']!=null){
							$imageLink=$databoxLinksGrids['image'];
						}else{
							$imageLink=$basePath.'/images/social_media/customization_no_img.jpg';
						}
						?>
						<div id="dragDropWindow<?echo $key+1;?>" class="grid-stack-item c_DivCard"
						<?php if( $tzGsRowNum % 4 == 0 ) { $xSet = $tzDataGsX;$tzDataGsX = 0;$ySet = $tzDataGsY;$tzDataGsY += 20; } else{ $xSet = $tzDataGsX;$tzDataGsX += 2;$ySet = $tzDataGsY; } ?> data-gs-x="<?php echo $xSet; ?>" data-gs-y="<?php echo $ySet; ?>" data-gs-height="18" data-gs-width="2">
							<div class="grid-stack-item-content">
									<?php
								if($databoxLinksGrids['is_video']==1)
								{
								?>
								
								<div class="c_DivCardImgWrapper"  >
										<iframe  width="272px" height="272px" style="<? echo $imageSocialAlone; ?>" src="<?echo $databoxLinksGrids['iframe_src'];?>" frameborder="0" allowfullscreen></iframe>
								</div>
								
								<?php 
								}else{
								?>
									<a href="<?echo $url;?>" target="_blank">
									<div  class="c_DivCardImgWrapper">
										<img class="c_DivCardImg" src="<?php echo $imageLink; ?>"/>
									</div>
									</a>
								<?php } ?>	
								
								<?php if(isset($databoxLinksGrids['title']) && $databoxLinksGrids['title']!=""){?>
									<div class="pad_10px" ><h2>
										<?php if(strlen($databoxLinksGrids['title'])>20){
												echo substr($databoxLinksGrids['title'],0,20) . '...'; 
											}
											else
											{
												echo $databoxLinksGrids['title'];
											}
										?>
									</h2></div><?} $parahid="";
								if(isset($databoxLinksGrids['description']) && $databoxLinksGrids['description']!="no Description"){?>
								<div class="pad_10px" >
								<?php
									if(strlen($databoxLinksGrids['description'])>250){
										echo substr($databoxLinksGrids['description'],0,250) . '<a href="'.$url.'" target="_blank">...Read more</a>';
										$parahid=1;
									}
									else
									{
										echo $databoxLinksGrids['description'];
										$parahid=0;
									}
								?>
								</div>
								<?}?>
								
							</div>
						</div>
					<?php $tzGsRowNum++; } ?>
					</div>
				<?
				}
				else
				{
					foreach($this->databoxLinksGrid as $key=>$databoxLinksGrids)
						echo $databoxLinksGrids['div_html'];{?>
					<?php }
				}?>
			</span>
		</div>
	</section>
</div>

<div id="tempRemDiv" style="display:none;"></div>

<script src="<?php echo $basePath; ?>/js/new_js/libs/jquery/jquery.js"></script>
        <!-- DragDrop Plugin -->
		
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
		
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.7.0/underscore-min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
        <script src="<?php echo $basePath; ?>/js/new_js/gridstack.min.js"></script>
        <!-- DragDrop Plugin End -->
        <script src="<?php echo $basePath; ?>/js/new_js/jquery.nicescroll.min.js"></script>
		<!-- Cat Desc CKEditor Pop Up -->
<?if($this->data==0){?>
<input type="hidden" id="incrId" value="<?echo count($this->databoxLinksGrid)?>">
<?}else{?>
<input type="hidden" id="incrId" value="<?echo $databoxLinksGrids['count_divs'];?>">
<?}?>



<input type="hidden" id="viewPageYes" value="0" />
<input type="hidden" id="viewPageChanged" value="0" />
<input type="hidden" id="commentMode" value="0" />
<input type="hidden" id="scrollHeight" value="0" />
<input type="hidden" id="catDescCkEditorYes" value="0" />
<input type="hidden" id="catDescChanged" value="0" />
<input type="hidden" id="hiddenDec" value="<?php echo $this->categoryDescripton;?>" />

<input type="hidden" id="basePath" name="basePath" value="<?php echo $basePath;?>" />
<input type="hidden" id="baseUrl"  name="baseUrl" value="<?php echo $baseUrl;?>" />


<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5461ef997855b9fa" async="async"></script>
<script type="text/javascript">
$('body').css('background','#f6f6f6')
var i=0;
	$(function () {
	
		$('.grid-stack').gridstack({
			static_grid:true,
			min_width: 768,
			item_class: 'grid-stack-item',
			handle: '.grid-stack-item-content',
			// one cell height
			cell_height: 1,
			// vertical gap size
			vertical_margin: 20,
			horizontal_margin: 10
		});
		 $('.grid-stack').gridstack({
			 
	// turns animation on
  animate: false,

  // if false it tells to do not initialize existing items
  auto: true,

  // amount of columns
 width: 12,

  // maximum rows amount
height: 0, 

  // widget class
  item_class: 'grid-stack-item',

  // class for placeholder
  placeholder_class: 'grid-stack-placeholder',

  // draggable handle selector
  handle: '.grid-stack-item-content',

  // one cell height
  cell_height: 1,

  // vertical gap size
  vertical_margin: 20,

  // if false it tells to do not initialize existing items
 // auto: true,
  
  // minimal width.
  min_width: 768,

  // enable floating widgets
  float: false,

  // vertical gap size
  vertical_margin: 20,

  // if true the resizing handles are shown even the user is not hovering over the widget
  always_show_resize_handle: false,

  // allows to owerride jQuery UI draggable options
  draggable: {handle: '.grid-stack-item-content', scroll: true, appendTo: 'body'},
  // allows to owerride jQuery UI resizable options
  resizable: {autoHide: true, handles: 'se'}
		  });
		  new function () {
                this.items = [
                    {x: 0, y: 0, width: 2, height: 6}
                ];

                this.grid = $('.grid-stack').data('gridstack');
				
                this.add_new_widget = function () {
					i++;
                    var node = this.items.pop() || {
                                x: 0* Math.random(),
                                y: 0* Math.random(),
                                width: 2,
                                height:6,
								auto_position: true
                            };
							

				var incrValue=$('#incrId').val();
				var newValue=parseInt(incrValue)+1;
				$('#incrId').val(newValue);
				var commEditDelHtml = '<div id="deleteComment'+newValue+'" style="position:absolute;top:-23px;right:-1px;background:#f1f1f1;border:1px solid #bfc4c8;width:50px;"><span style="margin-right:10px;"><a href="javascript:void(0)"; onclick="editExistingComment('+newValue+')"><img src="'+BASE_PATH+'/images/social_media/edit_ico.png"/></a></span><a href="javascript:void(0)"; onclick="deleteComment('+newValue+')" style="color:#f97e76" title="Close">X</a></div>';

				var newCommBoxHtml = '<div id="dragDropWindow'+newValue+'" class="c_DivCard grid-stack-item" data-gs-height="20"><div class="grid-stack-item-content">';
				newCommBoxHtml += '<div class="c_DivCardStoryWrapper"><div class="c_DivCardStorytellerDetails">';
				newCommBoxHtml += '<img class="c_DivCardStorytellerImg" src="<?php echo $basePath; ?>/images/project/montageImages/<?php echo $_SESSION['usersinfo']->montage_image; ?>"/>';
				newCommBoxHtml += '<div class="c_DivCardStorytellerName">@STORYTELLER (<?php echo $_SESSION['usersinfo']->displayName; ?>)</div>';
				newCommBoxHtml += '</div>';
				newCommBoxHtml += '<div class="c_DivCardStory"><span id="data_'+newValue+'">'+newCommentText+'</span>'+commEditDelHtml+'</div>';
				newCommBoxHtml += '</div>';
				this.grid.add_widget($(newCommBoxHtml),node.x, node.y, node.width, node.height);
                }.bind(this);
				
                // $('#add-new-widget').click(this.add_new_widget);
				tzGridStackRef = this;
				$('#add-new-widget').click(function(event)
				{
					custCommentCkEditorShow( '',0 );
				});
            };
	});
</script>		
<script>
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=608131635971702&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>   
