
        <div id="mainContainerWrapper" class="mainContainerWrapper tmar_t125">

            <!-- This div is to include the header.html page 
            <div id='divIncludeContent'></div>-->

            <section id="secSelectDatabox" class="">
                <div class="heading">SELECT DATABOX TYPE</div>
                <span class="box_crete_color">Click on your Choice Below and Continue </span>
                <div class="divSelectDataboxContentWrapper">
                    <a href="javascript:void(0);" onClick="selectDataBoxFunction('private')" class="divSelectDatabox">
                        <div class="divSelectDataboxHeading pad_bb">
                            Private Databox
                        </div>
                        <img src="<?php echo $basePath; ?>/img/private_databox.png" class="imgDataboxImage" alt="" />
                        <div class="divSelectDataboxDescription small_font_pt10 box_crete_color pad_tt">
                            Your Collection of Web/Hot Links is protected with a Generated Dynamic Unique Code. Access to Your Private Databox is allowed to Registered user(s) who's informed with its Generated Unique Code & #Hashtag.
                        </div>
                    </a>

                  <a href="javascript:void(0);" onClick="selectDataBoxFunction('public')" class="divSelectDatabox">
                        <div class="divSelectDataboxHeading pad_bb">
                            Public Databox
                        </div>
                        <img src="<?php echo $basePath; ?>/img/public_databox.png" class="imgDataboxImage" alt="" />
                        <div class="divSelectDataboxDescription small_font_pt10 box_crete_color pad_tt">
                            Your collection of Web/Hot Links is acccessible<br/>to Global users
                        </div>
                    </a>
                </div>
            </section>
        </div>

<script>
function selectDataBoxFunction(selecttype){
	if( setTzBoxId(0) )
	{
		if(selecttype=='private'){
			window.location=BASE_URL+'/databox/createhashtag/privatedatabox/0';
		}else{
			window.location=BASE_URL+'/databox/createhashtag/publicdatabox/0';
		}
	}
	else
	{
		alert( "Databox creation not available presently..." );
		return false;
	}
}
</script>