<?php //echo "<pre>";print_r($this->userDetails);exit; ?>
<link rel="stylesheet" media="(max-width: 799px)" href="<?php echo $basePath; ?>/css/new_css/styles-mobile.css" />
<div class="tzcontainer_as">
<div class="tmar_t125">
<section id="secAccountSettings" class="tac_bg">
                <div class="divAccountSettingsRow">
                    <!-- Account Settings Block -->
                    <div class="divAccountSettingsCard">
                        <div class="divAccountSettingsHeading heading_font_pt12">
                            ACCOUNT SETTINGS
                        </div>
						<div class="edit_pick_img">
								<div class="file-input-wrapper">
									<?
										$montage_image="";
										if(strpos($_SESSION['usersinfo']->montage_image, "https://") !== false || strpos($_SESSION['usersinfo']->montage_image, "http://") !== false) 
									   { 
											   $montage_image=$_SESSION['usersinfo']->montage_image;
									   }else{
											$montage_image=$basePath.'/images/project/montageImages/'.$_SESSION['usersinfo']->montage_image;
									   }
									
									?>
									<img id="uploadedAccountImage1" src="<?php echo $montage_image; ?>" class="btn-file-input" width="50px"/> <span style="cursor:hand;cursor:pointer;" id="tzAccCropLink">Edit Your Picture</span>
								</div>
						</div>
                        <div class="divAccountSettingsForm" style="position:relative">
                            <label>
                                Profile Name : 
                            </label>
							<input type="text" name="display_name" id="display_name"  value="<?echo $this->userDetails->display_name;?>" placeholder="Set profile name"/>
							<div class="acount_pos_abs" style="display:none;">
							<div style="margin-top:5px;text-align:right;">
							<p>Change</p>
								<img onClick="profileEmpty();" src="<?php echo $basePath; ?>/images/social_media/edit_ico.png" style="padding:8px;"/></div>
							</div>
                            <label>
                                Password : 
                            </label>
							<input type="password" name="password" id="password"  placeholder="Set password" onfocus="showConfirmPassword()" >
								<label id="confirmLable" style="display: none;">
                                Confirm Password : 
								</label>
								<input type="password" name="confirmPwd" id="confirmPwd" placeholder="confirm password" style="display: none;">
						<?php
							if( $this->userDetails->email != "" )
							{
								if( $this->userDetails->hide_me != "1" )
								{
						?>
						<label id="emailLabel" style="">
							Email Id : 
						</label>
						<input type="text" style="" name="email" id="email"  readonly = "readonly" value="<?echo $this->userDetails->email;?>" readonly="readonly" >
						<?php
						}else{
						?>
						<label id="emailLabel" style="display:none;">
							Email Id : 
						</label>
						<input type="text" style="display:none;" name="email" id="email"  readonly = "readonly" value="<?echo $this->userDetails->email;?>" readonly="readonly" >
						<?php }
						}
						?>
						<div>
						<?php
							if( $this->userDetails->hide_me != "1" )
						{?>
                            <input style="width:auto;" type="checkbox" name="hide_me" id="hide_me" > Hide Me 
                        <?php }else{?>
						      <input style="width:auto;" type="checkbox" name="hide_me" id="hide_me" checked > Hide Me 

						<?php } ?>
						</div>
						
						<div>
						<?php
							if( $this->userDetails->disable_messageing != "1" )
						{?>
                            <input style="width:auto;" type="checkbox" name="disable_messaging" id="disable_messaging" > Disable Personal messaging 
                         <?php }else{?>
							<input style="width:auto;" type="checkbox" name="disable_messaging" id="disable_messaging" checked > Disable Personal messaging 
						 <?php } ?>
						</div>
						
							  
                        </div>
                    </div>

                    <!-- User Summary Block -->
                    <div class="divUserSummaryCard">
                        <div class="divUserSummaryHeading heading_font_pt12" align="center">
							YOUR ACTIVITY
                        </div>

                        <div class="divUserSummaryRow">
                            <div class="divPublicDataboxCount"><b><?echo $this->getPublicDataboxCount;?></b></div> Public Databoxes &nbsp;
                            <div class="divPrivateDataboxCount"><b><?echo $this->getPrivateDataboxCount;?></b></div> Private Databoxes &nbsp;
                            <div class="divPrivateDataboxCount"><b><?echo $this->getHiglightDataboxCount;?></b></div> Highlights &nbsp;
                        </div>

                        <div class="divUserSummaryRow">
								<img src="<?php echo $basePath; ?>/img/star.png"> Montage Tacked
							<?if($_SESSION['usersinfo']->montage_paragraph!=""){?>
								<img src="<?php echo $basePath; ?>/images/social_media/ok.png"/>
							<?}else{?>
								<b>x</b>
							<?}?>
                        </div>

                        <div class="divUserSummaryRow">
                            Total Keywords <div class="divTotalKeywordsCount"><?php echo $this->totalKeywords; ?></div> <small> (Public Databoxes) </small>
                        </div>

                        <div class="divUserSummaryRow">
						<?php
							$upTotal = 0;
							$downTotal = 0;
							if( $this->votesCountRow->countUp != null )
							{
								$upTotal = $this->votesCountRow->countUp;
							}
							if( $this->votesCountRow->countDown != null )
							{
								$downTotal = $this->votesCountRow->countDown;
							}
						?>
                            <div class="divUserSummaryColumn">
                                <div class="divUserSummarySubColumn">
                                    <div class="divVotesCount"><?php echo $upTotal; ?></div> 
                                    <div class="divVotesText"> Votes </div>
                                </div>
                                <div class="divUserSummarySubColumn">
                                    <img src="<?php echo $basePath; ?>/img/thumbsUp.png" /> 
                                </div>
                            </div>


                            <div class="divUserSummaryColumn">
                                Response for posts
                            </div>

                            <div class="divUserSummaryColumn">
                                <div class="divUserSummarySubColumn">
                                    <img src="<?php echo $basePath; ?>/img/thumbsDown.png" /> 
                                </div>

                                <div class="divUserSummarySubColumn">
                                    <div class="divVotesCount"><?php echo $downTotal; ?></div> 
                                    <div class="divVotesText"> Votes </div>
                                </div>
                            </div>
                        </div>

                        <div class="divUserSummaryRow">
                            <h3><b><div class="divTotalLinksCount"><?echo $this->getTotalLinks;?></div> Links Collected, Categorized, #Hashtagged</h3></b>
                        </div>
                    </div>
                </div>

                <div class="divAccountSettingsRow tmar_t0">
                    <img src="<?php echo $basePath; ?>/img/emailVerified.png" class="imgEmailVerified" />
                    <button  href="javascript:void(0);" onclick="changeAccountStatus(2,<?echo $this->userDetails->user_id;?>);" class="btnDeactivateAccount">DEACTIVATE ACCOUNT</button>
                </div>
                
                <div class="divAccountSettingsRow">
                    <button href="javascript:void(0);" onclick="updateUser(<?echo $this->userDetails->user_id;?>)" class="btnSaveAccount">SAVE</button><span id="deactiveLoad" style="display:none"><img src="<?php echo $basePath; ?>/images/social_media/loading.gif"></span>
					<p id="updateMessage" style="color:green"></p>
				</div>
            </section>
</div>
</div>
</div>

<div id="pop-up-image-crop-new" class="pop-up-display-content conform_popup_content" style="margin-bottom:20px;">
	<div class="pop_up_haeding close"><h3>CROP IMAGE </h3><span onclick="selectHighCropImage();">Upload Image</span></div>
	<input type="file" id="HighCropInp" class="cropit-image-input" style="display:none;" onchange="showHighCropButton()" />
	<div class="cropit-image-preview-container">
		<div id="crop_heigh" class="cropit-image-preview"></div>
	</div>
	<div style="text-align:center;margin-top:30px;"><input type="range" class="cropit-image-zoom-input" /></div>
	<button class="export">Crop</button><span id="l_i_c" style="display:none;margin-left:80%;"><img src="<?php echo $basePath; ?>/images/social_media/bx_loader.gif" /></span>
</div>
<input type="hidden" id="cropImage1" name="cropImage1" value="0" />
<link rel="stylesheet" type="text/css" href="<?php echo $basePath; ?>/js/crop/cropit.css" />
<script src="<?php echo $basePath; ?>/js/crop/jquery.cropit.js"></script>
<script type="text/javascript" src="<?php echo $basePath; ?>/js/popupwindow.js"></script>

<script>

function checkHighImageLoaded()
{
	var filename = $('#HighCropInp').val();
	
	var invalidExtension = false;
	
	if( filename.trim() != "" )
	{
		filename = filename.toLowerCase();
		var fnameArray = filename.split( "." );
		if( parseInt(fnameArray.length) > 0 )
		{
			if( (fnameArray[fnameArray.length-1] != "gif") && (fnameArray[fnameArray.length-1] != "jpg") && (fnameArray[fnameArray.length-1] != "jpeg") && (fnameArray[fnameArray.length-1] != "bmp") && (fnameArray[fnameArray.length-1] != "png") && (fnameArray[fnameArray.length-1] != "bpg") && (fnameArray[fnameArray.length-1] != "tiff") && (fnameArray[fnameArray.length-1] != "ppm") && (fnameArray[fnameArray.length-1] != "pgm") && (fnameArray[fnameArray.length-1] != "pbm") && (fnameArray[fnameArray.length-1] != "pnm") && (fnameArray[fnameArray.length-1] != "webp") )
			{
				invalidExtension = true;
			}
		}
		if( invalidExtension )
		{
			alert( crop_input_valid_file );
			$('#HighCropInp').value='';
			return false;
		}
	}
	return true;
}

$(function() {
	$('#pop-up-image-crop-new').cropit({
		imageBackground: true
	});
	$('.export').click(function() {
		var src = $('#pop-up-image-crop-new').cropit('export');
		var fetchUploadedUrl = BASE_URL+'/upload-montage-image';
		var imageId=$('#cropImage1').val();
		$("#l_i_c").show();
		$.ajax({
			type	: "POST",
			url		: fetchUploadedUrl,
			data	: { data: src,page:'acc',imageId:imageId},
			success: function(data){
				$("#l_i_c").hide();
				$('#pop-up-image-crop-new').popUpWindow({action: "close"});
				$('#uploadedAccountImage1').attr('src',src);
				$('#cropImage1').val(data.imageId);
			}
		});
		//window.open(imageData);
	});
});

$('#tzAccCropLink').click(function(event){
	$('#pop-up-image-crop-new').popUpWindow({action: "open"});
	$('.pop-up-content').css('border','0');
	$('.close').css('right','0');
	$('.close').css('top','0');
});	


$(document).ready(function(){
  $("#display_name").click(function(){
    $(".acount_pos_abs").show();
  });
});

function acountChange(){
	  $(".acount_pos_abs").hide();
}
function showConfirmPassword(){
	  $("#confirmLable").show();
	  $("#confirmPwd").show();
}
function profileEmpty(){
		$("#display_name").val('');
		$("#display_name").focus();
		$(".acount_pos_abs").hide();
}

</script>