<?php //echo "<pre>";print_r($this->getUserMessages);exit; ?>
<link rel="stylesheet" media="(max-width: 799px)" href="<?php echo $basePath; ?>/css/new_css/styles-mobile.css" />
<div class="tzcontainer_as">
<div class="tmar_t125">
<section id="secAccountSettings" class="tac_bg">
                <div class="divAccountSettingsRow">
                    <!-- Account Settings Block -->
                    <div class="divAccountSettingsCard">
                        <div class="divAccountSettingsHeading heading_font_pt12">
                            ACCOUNT SETTINGS
                        </div>
						<div class="edit_pick_img">
								<div class="file-input-wrapper">
									<?
										$montage_image="";
										if(strpos($_SESSION['usersinfo']->montage_image, "https://") !== false || strpos($_SESSION['usersinfo']->montage_image, "http://") !== false) 
									   { 
											   $montage_image=$_SESSION['usersinfo']->montage_image;
									   }else{
											$montage_image=$basePath.'/images/project/montageImages/'.$_SESSION['usersinfo']->montage_image;
									   }
									
									?>
									<img id="uploadedAccountImage1" src="<?php echo $montage_image; ?>" class="btn-file-input" width="50px"/> <span>Edit Your Picture</span>
								</div>
						</div>
                        <div class="divAccountSettingsForm" style="position:relative">
                            <label>
                                Profile Name : 
                            </label>
							<input type="text" name="display_name" id="display_name" value="<?echo $this->userDetails->display_name;?>" placeholder="Set profile name"/>
							<div class="acount_pos_abs" style="display:none;">
							<div style="margin-top:5px;text-align:right;">
							<p>Change</p>
								<img onClick="profileEmpty();" src="<?php echo $basePath; ?>/images/social_media/edit_ico.png" style="padding:8px;"/></div>
							</div>
                            <label>
                                Password : 
                            </label>
							<input type="password" name="password" id="password" placeholder="Set password" onfocus="showConfirmPassword()" >
								<label id="confirmLable" style="display: none;">
                                Confirm Password : 
								</label>
								<input type="password" name="confirmPwd" id="confirmPwd" placeholder="confirm password" style="display: none;">
						<?php
							if( $this->userDetails->email != "" )
							{
						?>
								<label>
									Email Id : 
								</label>
								<input type="text" name="email" id="email" readonly value="<?echo $this->userDetails->email;?>" readonly >
						<?php
							}
						?>
                           
                        </div>
                    </div>

                    <!-- User Summary Block -->
                    <div class="divUserSummaryCard">
                        <div class="divUserSummaryHeading heading_font_pt12" align="center">
							USER SUMMARY
                        </div>

                        <div class="divUserSummaryRow">
                            <div class="divPublicDataboxCount"><b><?echo $this->getPublicDataboxCount;?></b></div> Public Databoxes &nbsp;
                            <div class="divPrivateDataboxCount"><b><?echo $this->getPrivateDataboxCount;?></b></div> Private Databoxes &nbsp;
                        </div>

                        <div class="divUserSummaryRow">
								<img src="<?php echo $basePath; ?>/img/star.png"> Montage Tacked
							<?if($_SESSION['usersinfo']->montage_paragraph!=""){?>
								<img src="<?php echo $basePath; ?>/images/social_media/ok.png"/>
							<?}else{?>
								<b>x</b>
							<?}?>
                        </div>

                        <div class="divUserSummaryRow">
                            Total Keywords <div class="divTotalKeywordsCount"><?php echo $this->totalKeywords; ?></div> <small> (Public Databoxes) </small>
                        </div>

                        <div class="divUserSummaryRow">
						<?php
							$upTotal = 0;
							$downTotal = 0;
							if( $this->votesCountRow->countUp != null )
							{
								$upTotal = $this->votesCountRow->countUp;
							}
							if( $this->votesCountRow->countDown != null )
							{
								$downTotal = $this->votesCountRow->countDown;
							}
						?>
                            <div class="divUserSummaryColumn">
                                <div class="divUserSummarySubColumn">
                                    <div class="divVotesCount"><?php echo $upTotal; ?></div> 
                                    <div class="divVotesText"> Votes </div>
                                </div>
                                <div class="divUserSummarySubColumn">
                                    <img src="<?php echo $basePath; ?>/img/thumbsUp.png" /> 
                                </div>
                            </div>


                            <div class="divUserSummaryColumn">
                                Response for posts
                            </div>

                            <div class="divUserSummaryColumn">
                                <div class="divUserSummarySubColumn">
                                    <img src="<?php echo $basePath; ?>/img/thumbsDown.png" /> 
                                </div>

                                <div class="divUserSummarySubColumn">
                                    <div class="divVotesCount"><?php echo $downTotal; ?></div> 
                                    <div class="divVotesText"> Votes </div>
                                </div>
                            </div>
                        </div>

                        <div class="divUserSummaryRow">
                            <div class="divTotalLinksCount"><?echo $this->getTotalLinks;?></div> Links Collected, Categorized, #Hashtagged
                        </div>
                    </div>
                </div>

                <div class="divAccountSettingsRow tmar_t0">
                    <img src="<?php echo $basePath; ?>/img/emailVerified.png" class="imgEmailVerified" />
                    <button  href="javascript:void(0);" onclick="changeAccountStatus(2,<?echo $this->userDetails->user_id;?>);" class="btnDeactivateAccount">DEACTIVATE ACCOUNT</button>
                </div>
                
                <div class="divAccountSettingsRow">
                    <button href="javascript:void(0);" onclick="updateUser(<?echo $this->userDetails->user_id;?>)" class="btnSaveAccount">SAVE</button><span id="deactiveLoad" style="display:none"><img src="<?php echo $basePath; ?>/images/social_media/loading.gif"></span>
					<p id="updateMessage" style="color:green"></p>
				</div>
            </section>
</div>
</div>
</div>
<script>
$(document).ready(function(){
  $("#display_name").click(function(){
    $(".acount_pos_abs").show();
  });
});

function acountChange(){
	  $(".acount_pos_abs").hide();
}
function showConfirmPassword(){
	  $("#confirmLable").show();
	  $("#confirmPwd").show();
}
function profileEmpty(){
		$("#display_name").val('');
		$("#display_name").focus();
		$(".acount_pos_abs").hide();
}

</script>