<link href="<?php echo $basePath; ?>/css/default.css" rel="stylesheet" type="text/css" />
<div class="montage_container">

			<div align="center" >
						<div class=""><h1>Convert your Activity Rewarded Points into Mobile Recharging Cash</h1></div>
			</div>
			<br>
			<div class="dash_pick_bg mycolleection">
			<div style="margin-top:1px;" class="">

			<!-- Hash name Start -->
			<div align="center" id="hash_name">
				<div class=""><h1>You have been rewarded with 00 INR from Earning 0000 activity based Points. You can Recharge a Mobile with the cash acquired from Rewarding Points.</h1>
				</div>
			</div>

				</div>
			</div>
	<div class="tg_montage_t montage_brg_box">
				<div class="montage_box_brg_title">
					<div class="text_row">
						<div class="float_l"><h3><b><a href="">Select Your Mobile Operator</a></b><span></span></h3></div>
					</div><div class="clearfix"></div>
				</div>
				<div class="pos_relative">
					<div id="montageRow3" class="montage_row">
						<div class="column1">
							<div>
							<a target="_blank" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/aircel.png" alt="" id="" class="" /></a>
							</div>
							<h5 style="text-align: center; ">
							Aircel							
							</h5>
						</div>
						<div class="column1">
							<div>
							<a target="_blank" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/airtel.png" alt="" id="" class="" /></a>
							</div>
							<h5 style="text-align: center;">
							Airtel							
							</h5>
						</div>
						<div class="column1">
							<div>
							<a target="_blank" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/bsnl.png" alt="" id="" class="" /></a>
							</div>
							<h5 style="text-align: center;">BSNL							
							</h5>
						</div>
						<div class="column1">
							<div>
							<a target="_blank" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/bsnl.png" alt="" id="" class="" /></a>
							</div>
							<h5 style="text-align: center;">BSNL-VALIDITY							
							</h5>
						</div>
					<div class="column1">
							<div>
							<a target="_blank" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/idea.png" alt="" id="" class="" /></a>
							</div>
							<h5 style="text-align: center;">Idea							
							</h5>
					</div>
					<div class="column1">
							<div>
								<a target="_blank" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/loop.png" alt="" id="" class="" /></a>
							</div>
							<h5 style="text-align: center;">Loop Mobile							
							</h5>
					</div>
					<div class="column1">
							<div>
							<a target="_blank" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/mts.png" alt="" id="" class="" /></a>
							</div>
							<h5 style="text-align: center;">MTS						
							</h5>
						</div>
						<div class="column1">
							<div>
							<a target="_blank" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/reliance.png" alt="" id="" class="" /></a>
							</div>
							<h5 style="text-align: center;">Reliance					
							</h5>
						</div>
						
						<div class="column1">
							<div>
							<a target="_blank" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/docomo.png" alt="" id="" class="" /></a>
							</div>
							<h5 style="text-align: center;">DOCOMO Cdma					
							</h5>
						</div>
						<div class="column1">
							<div>
							<a target="_blank" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/docomo.png" alt="" id="" class="" /></a>
							</div>
							<h5 style="text-align: center;">Tata DOCOMO					
							</h5>
						</div>
						<div class="column1">
							<div>
							<a target="_blank" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/docomo.png" alt="" id="" class="" /></a>
							</div>
							<h5 style="text-align: center;">Tata Docomo<br> 
								Special Recharges					
							</h5>
						</div>
						<div class="column1">
							<div>
							<a target="_blank" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/mtnl.png" alt="" id="" class="" /></a>
							</div>
							<h5 style="text-align: center;">MTNL Mumbai					
							</h5>
						</div>
						<div class="column1">
							<div>
							<a target="_blank" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/uninor.png" alt="" id="" class="" /></a>
							</div>
							<h5 style="text-align: center;">Uninor 				
							</h5>
						</div>
						<div class="column1">
							<div>
							<a target="_blank" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/uninor.png" alt="" id="" class="" /></a>
							</div>
							<h5 style="text-align: center;">Uninor Special					
							</h5>
						</div>
						<div class="column1">
							<div>
							<a target="_blank" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/videocon.png" alt="" id="" class="" /></a>
							</div>
							<h5 style="text-align: center;">Videocon 				
							</h5>
						</div>
						<div class="column1">
							<div>
							<a target="_blank" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/videocon.png" alt="" id="" class="" /></a>
							</div>
							<h5 style="text-align: center;">Videocon Special					
							</h5>
						</div>
						<div class="column1">
							<div>
							<a target="_blank" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/vadafone.png" alt="" id="" class="" /></a>
							</div>
							<h5 style="text-align: center;">Vodafone				
							</h5>
						</div>
						<div class="clearfix"></div>
						
				</div><br>
						<div style="margin-left:180px">
						<p>You have Selected : </p>
						<br>
						<label>Enter a Valid Mobile Number:</label>
						<input type="text"><br><br>
						<label>Enter the valid Recharge/Payment amount:</label>
						<input type="text">
						<label>from your Available Cash</label>
						<input type="text">
						</div>
						<br>
						<br>
						<div style="text-align:center">
						<input type="submit" value="pay" class="btn">&nbsp;&nbsp;
						<input type="submit" value="Cancel" class="btn">

					</div>
					
			</div>
	</div>
	