<link href="<?php echo $basePath; ?>/css/default.css" rel="stylesheet" type="text/css" />
<div class="montage_container">
	
	
	
	
	
	<div class="tg_montage_t montage_brg_box">
				<div class="montage_box_brg_title">
					<div class="text_row">
						<div class="float_l"><h3><b><a href="http://localhost/taggerzz-new/trunk/databox/post-vertical/3+5+EducationNews+Education-Information">#EducationNews</a></b><span>&nbsp;(13/100)</span></h3></div>
						<div class="float_r"><p class="text_sub_title"></p><h3><b><a href="http://localhost/taggerzz-new/trunk/databox/post-vertical/3+5+EducationNews+Education-Information">Education Information</a></b></h3><p></p></div>
					</div><div class="clearfix"></div>
				</div>
				<div class="pos_relative">
					<div id="montageRow3" class="montage_row">
											<div class="column1">
							<div>
							<p>
							http://timesofindia....								
							</p>
							<a target="_blank" href="http://timesofindia.indiatimes.com/home/education/news"><img src="https://taggerzz.com/public/images/social_media/noimage.png"></a></div>
						</div>
											<div class="column1">
							<div>
							<p>
							http://indianexpress...								
							</p>
							<a target="_blank" href="http://indianexpress.com/article/entertainment/bollywood/sex-education-is-important-aishwarya-rai-bachchan/"><img src="http://images.indianexpress.com/2015/12/aishwaryaraibachchan480.jpg?w=480"></a></div>
						</div>
											<div class="column1">
							<div>
							<p>
							http://zeenews.india...								
							</p>
							<a target="_blank" href="http://zeenews.india.com/education/news.htm"><img src="http://ste.india.com/ads/Magicbrics.png"></a></div>
						</div>
											<div class="column1">
							<div>
							<p>
							http://indiatoday.in...								
							</p>
							<a target="_blank" href="http://indiatoday.intoday.in/education/"><img src="http://media2.intoday.in/indiatoday/education/images/logo.png"></a></div>
						</div>
											<div class="column1">
							<div>
							<p>
							http://indianexpress...								
							</p>
							<a target="_blank" href="http://indianexpress.com/section/india/education-news/"><img src="https://indianexpressonline.files.wordpress.com/2015/09/bihar-banners.jpg"></a></div>
						</div>
											<div class="column1">
							<div>
							<p>
							http://www.jagranjos...								
							</p>
							<a target="_blank" href="http://www.jagranjosh.com/articles-education-news-1292334300-1"><img src="http://www.jagranjosh.com/Resources/edu2/images/jagran-logonew.png"></a></div>
						</div>
											<div class="column1">
							<div>
							<p>
							http://www.telegraph...								
							</p>
							<a target="_blank" href="http://www.telegraph.co.uk/education/educationnews/"><img src="http://www.telegraph.co.uk/template/ver1-0/i/telegraphFacebook.jpg"></a></div>
						</div>
											<div class="column1">
							<div>
							<p>
							http://www.dnaindia....								
							</p>
							<a target="_blank" href="http://www.dnaindia.com/topic/education"><img src="http://static.dnaindia.com/images/2013/logo2013.png"></a></div>
						</div>
											<div class="column1">
							<div>
							<p>
							http://indiatogether...								
							</p>
							<a target="_blank" href="http://indiatogether.org/c/education"><img src="http://indiatogether.org/uploads/picture/image/2459/thumb_School_children_at_Nandikotkur_village.jpg"></a></div>
						</div>
											<div class="column1">
							<div>
							<p>
							http://www.firstpost...								
							</p>
							<a target="_blank" href="http://www.firstpost.com/category/sports"><img src="http://s2.firstpost.in/wp-content/themes/firstpost2.0/images/promo/RHS-Header-Image.png"></a></div>
						</div>
											<div class="column1">
							<div>
							<p>
							http://in.reuters.co...								
							</p>
							<a target="_blank" href="http://in.reuters.com/news/sports/cricket"><img src="http://s3.reutersmedia.net/resources_v2/images/masthead-logo.gif"></a></div>
						</div>
											<div class="column1">
							<div>
							<p>
							http://www.telegraph...								
							</p>
							<a target="_blank" href="http://www.telegraph.co.uk/sport/cricket/"><img src="http://www.telegraph.co.uk/template/ver1-0/i/telegraphFacebook.jpg"></a></div>
						</div>
											<div class="column1">
							<div>
							<p>
							http://www.cricbuzz....								
							</p>
							<a target="_blank" href="http://www.cricbuzz.com/?gclid=CJO4l8r4uskCFRUfaAodbxoEfQ"><img src="https://taggerzz.com/public/images/social_media/noimage.png"></a></div>
						</div>
										</div>
					<div class="clearfix"></div>
				</div>
			</div>
	</div>
	