<link href="<?php echo $basePath; ?>/css/default.css" rel="stylesheet" type="text/css" />
<div class="" style="margin-top: 115px;">
			<div class="hor_line">
			<div align="center" >
						<div style="color:#5f5959;padding-top: 14px;"><h2 style="font-size:17px">Convert your Activity Rewarded Points into Mobile Recharging Cash</h2></div>
			</div>
			</div>
			<br>
				<div>
					<div align="center" id="hash_name">
						<div class="" style="color:#5f5959;padding-bottom: 15px;"><h4 style="font-size:13px;">You have been rewarded with 00 INR from Earning 0000 activity based Points. You can Recharge a Mobile with the cash acquired from Rewarding Points.</h4>
						</div>
					</div>
				</div>
	</div>
		<div class="montage_container2">
	<div class="tg_montage_t montage_brg_box">
				<div class="montage_box_brg_title">
					<div class="text_row">
						<div class="float_l"><h3><b><a href="">Select Your Mobile Operator</a></b><span></span></h3></div>
					</div><div class="clearfix"></div>
				</div>
				<div class="pos_relative">
					<div id="montageRow3" class="montage_row">
						<div class="column2">
							<div>
							<a target="" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/aircel.png" alt="" id="" class="" /></a>
							</div>
							<h5 class="img_label">
							Aircel							
							</h5>
						</div>
						<div class="column2">
							<div class="coupons_active">
							<a  href="#"><img src="<?php echo $basePath; ?>/images/coupons_images/airtel.png" alt="" id="" class="" /></a>
							</div>
							<h5 class="img_label">
							Airtel							
							</h5>
						</div>
						<div class="column2">
							<div>
							<a target="" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/bsnl.png" alt="" id="" class="" /></a>
							</div>
							<h5 class="img_label">BSNL							
							</h5>
						</div>
						<div class="column2">
							<div>
							<a target="" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/bsnl.png" alt="" id="" class="" /></a>
							</div>
							<h5 class="img_label">BSNL-VALIDITY							
							</h5>
						</div>
					<div class="column2">
							<div>
							<a target="" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/idea.png" alt="" id="" class="" /></a>
							</div>
							<h5 class="img_label">Idea							
							</h5>
					</div>
					<div class="column2">
							<div>
								<a target="" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/loop.png" alt="" id="" class="" /></a>
							</div>
							<h5 class="img_label">Loop Mobile							
							</h5>
					</div>
					<div class="column2">
							<div>
							<a target="" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/mts.png" alt="" id="" class="" /></a>
							</div>
							<h5 class="img_label">MTS						
							</h5>
						</div>
						
						<div class="column2">
							<div>
							<a target="" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/reliance.png" alt="" id="" class="" /></a>
							</div>
							<h5 class="img_label">Reliance					
							</h5>
						</div>
						
						<div class="column2">
							<div>
							<a target="" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/docomo.png" alt="" id="" class="" /></a>
							</div>
							<h5 class="img_label">DOCOMO Cdma					
							</h5>
						</div>
						<div class="column2">
							<div>
							<a target="" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/docomo.png" alt="" id="" class="" /></a>
							</div>
							<h5 class="img_label">Tata DOCOMO					
							</h5>
						</div>
						<div class="column2">
							<div>
							<a target="" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/docomo.png" alt="" id="" class="" /></a>
							</div>
							<h5 class="img_label">Tata Docomo<br> 
								Special Recharges					
							</h5>
						</div>
						<div class="column2">
							<div>
							<a target="" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/mtnl.png" alt="" id="" class="" /></a>
							</div>
							<h5 class="img_label">MTNL Mumbai					
							</h5>
						</div>
						<div class="column2">
							<div>
							<a target="" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/mtnl2.png" alt="" id="" class="" /></a>
							</div>
							<h5 class="img_label">MTNL Mumbai					
							</h5>
						</div>
						<div class="column2">
							<div>
							<a target="" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/uninor.png" alt="" id="" class="" /></a>
							</div>
							<h5 class="img_label"">Uninor 				
							</h5>
						</div>
						<div class="column2">
							<div>
							<a target="" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/uninor.png" alt="" id="" class="" /></a>
							</div>
							<h5 class="img_label">Uninor Special					
							</h5>
						</div>
						<div class="column2">
							<div>
							<a target="" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/videocon.png" alt="" id="" class="" /></a>
							</div>
							<h5 class="img_label">Videocon 				
							</h5>
						</div>
						<div class="column2">
							<div>
							<a target="" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/videocon.png" alt="" id="" class="" /></a>
							</div>
							<h5 class="img_label">Videocon Special					
							</h5>
						</div>
						<div class="column2">
							<div>
							<a target="" href=""><img src="<?php echo $basePath; ?>/images/coupons_images/vadafone.png" alt="" id="" class="" /></a>
							</div>
							<h5 class="img_label">Vodafone				
							</h5>
						</div>
						<div class="clearfix"></div>
				</div><br>
			</div>
	</div>
					<div class="mlabel">
						<p class="lab_color3">You have Selected : </p>
						<br class="smhide_m">
						<label  class="lab_color2">Enter a Valid Mobile Number:</label>
						<input type="text" class="text_pad2"><br><br class="smhide_m">
						<label  class="lab_color"> Enter the valid Recharge/Payment amount:</label>
						<input type="text" class="text_pad2">
						<label  class="lab_color">from your Available Cash</label>
						<input type="text" class="text_pad2">
					</div>
						<br>
						<br>
					<div style="text-align:center">
						<input type="submit" value="pay" class="btn">&nbsp;&nbsp;
						<input type="submit" value="Cancel" class="btn">
					</div>
</div>
	