<div class="tzcontainer_as tmar_b20">
<div class="tmar_t125">
<section id="secAccountSettings">
				<div class="tac_bg tmar_b20 das_brg_n">
                <div class="divAccountSettingsRow">
                    <div class="divCreatedCollectionsCard">
                        <div class="divAccountSettingsHeading heading_font_pt12">
                            CREATED COLLECTIONS 
                            <!--<small>(Databoxes &amp; Highlights)</small>-->
                        </div>
						
                        <ul class="ulCreatedCollectionList">
							
							<h3>Public</h3>
							<?php $pub=1;foreach($this->allDataboxes as $allDataboxes)
							{
								
								$currBoxEditLink = $baseUrl . "/databox/createhashtag/publicdatabox/" . $allDataboxes['category_id'];
								if( $allDataboxes['category_highlight'] == 2 )
								{
									$currBoxEditLink = $baseUrl . "/databox/createhashtag/highlight/" . $allDataboxes['category_id'];
								}
								else if( ! $allDataboxes['category_type'] )
								{
									$currBoxEditLink = $baseUrl . "/databox/createhashtag/privatedatabox/" . $allDataboxes['category_id'];
								}
								if($allDataboxes['category_highlight'] == 1 ){
									if($allDataboxes['category_type']==1){
										$pub++;
							?>
								<li class="liCreatedCollectionListItem"><div class="divCreatedCollectionText tdashboard_f"><h3 class="h3_size"><b><?php echo $allDataboxes['user_hashname'];?></b>, <?php echo $allDataboxes['category_title'];?></h3></div><a class="aCollectedCollectionEdit" href="Javascript:void(0);" onClick="setEditingBoxId( '<?php echo $allDataboxes['category_id']; ?>','<?php echo $currBoxEditLink; ?>' );">EDIT</a></li>
							<?php }}}
								if($pub==1){?>
							<li class="liCreatedCollectionListItem"><div class="divCreatedCollectionText tdashboard_f"><h3 class="h3_size">NO PUBLIC BOXES</h3></div></li>
							<?php }
							?>
							<h3>Private</h3>
							
							<?php $p=1; foreach($this->allDataboxes as $allDataboxes)
							{
								$currBoxEditLink = $baseUrl . "/databox/createhashtag/publicdatabox/" . $allDataboxes['category_id'];
								if( $allDataboxes['category_highlight'] == 2 )
								{
									$currBoxEditLink = $baseUrl . "/databox/createhashtag/highlight/" . $allDataboxes['category_id'];
								}
								else if( ! $allDataboxes['category_type'] )
								{
									$currBoxEditLink = $baseUrl . "/databox/createhashtag/privatedatabox/" . $allDataboxes['category_id'];
								}
								if($allDataboxes['category_highlight'] == 1 ){
									if($allDataboxes['category_type']==0){
										$p++;
							?>
								<li class="liCreatedCollectionListItem"><div class="divCreatedCollectionText tdashboard_f"><b><?php echo $allDataboxes['user_hashname'];?></b>, <?php echo $allDataboxes['category_title'];?></div><a class="aCollectedCollectionEdit" href="Javascript:void(0);" onClick="setEditingBoxId( '<?php echo $allDataboxes['category_id']; ?>','<?php echo $currBoxEditLink; ?>' );">EDIT</a></li>
								<?php }}}
								if($p==1){?>
								<li class="liCreatedCollectionListItem"><div class="divCreatedCollectionText tdashboard_f"><h3 class="h3_size">NO PRIVATE BOXES</h3></div></li>
								<?php }
								?>
							<h3>Heighlight</h3>
							
							<?php 
							$h=1;
							foreach($this->allDataboxes as $allDataboxes)
							{
								
								$currBoxEditLink = $baseUrl . "/databox/createhashtag/publicdatabox/" . $allDataboxes['category_id'];
								if( $allDataboxes['category_highlight'] == 2 )
								{
									$currBoxEditLink = $baseUrl . "/databox/createhashtag/highlight/" . $allDataboxes['category_id'];
								}
								else if( ! $allDataboxes['category_type'] )
								{
									$currBoxEditLink = $baseUrl . "/databox/createhashtag/privatedatabox/" . $allDataboxes['category_id'];
								}
								if($allDataboxes['category_highlight'] == 2 ){
									if($allDataboxes['category_type']==0){
										$h++;
							?>
								<li class="liCreatedCollectionListItem"><div class="divCreatedCollectionText tdashboard_f"><b><?php echo $allDataboxes['user_hashname'];?></b>, <?php echo $allDataboxes['category_title'];?></div><a class="aCollectedCollectionEdit" href="Javascript:void(0);" onClick="setEditingBoxId( '<?php echo $allDataboxes['category_id']; ?>','<?php echo $currBoxEditLink; ?>' );">EDIT</a></li>
							<?php }}}
								if($h==1 ){?>
							<li class="liCreatedCollectionListItem"><div class="divCreatedCollectionText tdashboard_f"><h3 class="h3_size">NO HEIGHLIGHT BOXES</h3></div></li>
							<?php }
							?>
                        </ul>
                    </div>
                </div>
                </div>
				<div class="tac_bg das_brg_n">
                <div  class="divAccountSettingsRow">
                   <?php if($this->userInfo->disable_messageing!="1"){ ?> 
					<div class="divCreatedCollectionsCard">
                    

						<div id="msgoto" class="divAccountSettingsHeading heading_font_pt12">
                            MESSAGES
                            <button onClick="composeMail()" class="btnComposeMessage">COMPOSE</button>
                        </div>
                        <ul class="ulCreatedCollectionList">
							<? if(count($this->getUserMessages)!=0){$i=0;foreach($this->getUserMessages as $userMessages){
								if($i==0){
								$id=$userMessages['msg_id'];
								$senderId=$userMessages['msg_sender_id'];
								$username=$userMessages['display_name'];
								$msg=$userMessages['message'];
								$date=$userMessages['msg_sended_date'];
								}
								$i++;
							?>
							<li class="liCreatedCollectionListItem">
								<div onClick="showMessage(<?php echo $userMessages['msg_id']?>)" class="divCreatedCollectionText"><a href="javaScript:void(0);"><?php echo $userMessages['msg_subject'];?></a></div><?php if($userMessages['msg_flag']=="0"){ ?><span id="statusFlag<?php echo $userMessages['msg_id']?>"  onClick="messageChangeStatus(<?php echo $userMessages['msg_id']?>)" class="spnNewMessageLabel new_pad"><a href="javaScript:void(0);">New</a></span><? }else{ }?>
							</li>
							<?}}else{?>
									<div  class="divCreatedCollectionText">No Records</div>
							<?}?>
                        </ul>
                    </div>
                </div>

                <div class="divAccountSettingsRow">
					<?php if(count($this->getUserMessages)!=0){?>
                    <div class="divCreatedCollectionsCard">
                        <div class="divCommentHeader">
                            <div class="divCommentHeaderUsernameBlock">
                                <div  id="divCommentUsername" class="divCommentUsername">
                                   <!-- Username,-->
								   <?php if(isset($username)){echo $username;}?>,
                                </div>
                                wrote
                            </div>
                            <div id="divCommentTime" class="divCommentTime">
                                <!--ON 06-02-2015, 2:22 AM-->
								<?php if(isset($date)){echo $date;}?>
                            </div>
                        </div>
                        
                        <div id="divCommentText" class="divCommentText">
							<?php if(isset($msg)){echo $msg;}?>
                        </div>
                        
                        <div id="divCommentControls" class="divCommentControls">
                            <button id="btnCommentReply" onClick="replyTo('<?php if(isset($username)){echo $username;}?>')" class="btnCommentReply">REPLY</button>
                            <button id="btnCommentForward" onClick="forwardTo(<?php if(isset($senderId)){echo $senderId;}?>)" class="btnCommentForward">FORWARD</button>
                            <button id="btnCommentBlockUser" onClick="blockUser(<?php if(isset($senderId)){echo $senderId;}?>)" class="btnCommentBlockUser">BLOCK USER</button>
                            
                            <button id="btnCommentReportSpam" class="btnCommentReportSpam">REPORT SPAM</button>
                        </div>
						<?php } ?>
                        
                        <div id="divReplyToWrapper" style="display:none;" class="divReplyToWrapper">
                            <input type="text" id="txtReplyTo" class="txtReplyTo" placeholder="To: Username" />
							<input type="text" id="txtSubject" class="txtReplyTo" placeholder="Enter message subject" />
                            <textarea id="textArea" class="txtReplyToText"></textarea>
                            <div class="divReplyToControls">
                                <div class="divReplyToMaxCharsText smhide_m">( &ast; MAXIMUM 5000 CHARS )</div>
                                <button onClick="insertMsg()" class="btnReplyToSend">SEND</button>
                                <button onclick="cancelForm()" class="btnReplyToCancel">CANCEL</button>
                            </div>
                        </div>
                    </div>
                </div>
				<?php }else{ ?>
						<div  class="divCreatedCollectionText"><center>Personal Messaging has been disabled.<a href="<?php echo $baseUrl; ?>/accounts" >Turn it on back </a></center></div>
					<?php } ?>
                </div>
				<input type="hidden" id="hidUserName" value="<?php if(isset($username)){echo $username;}?>">
				<input type="hidden" id="hidmessage" value="<?php if(isset($msg)){echo $msg;}?>">
				<input type="hidden" id="hidsenderid" value="1">
				<input type="hidden" id="hidreceivedid" value="">
            </section>
</div>
</div>
</div>
<script>
function setEditingBoxId( tzCreateEditBoxId,currBoxEditLink )
{
	if( setTzBoxId(tzCreateEditBoxId) )
	{
		window.location=currBoxEditLink;
	}
	else
	{
		alert( "Databox editing not available presently..." );
		return false;
	}
}

$(function() {
 $('html').niceScroll();
	$("#txtReplyTo").autocomplete({	
		source: function( request, response ) {
			var keywordsss = $('#txtReplyTo').val();
			$.ajax({
				url: BASE_URL+'/all-users-names-ajax',
				dataType: "json",
				type	: "POST",
				data	:{value:keywordsss},
				success: function( data ) {
					if(data.output!=0) {		
						response( $.map( data.usersAll, function( item ) {
							return {
								label: item.ref,
							}
						}));
					}else{
						$(".ui-autocomplete").css("display","none");
					}
				}				
			});
		},
		
	});
});
function blockUser(blocked_to_uid){
	
	if(typeof blocked_to_uid=="undefined"){
		alert('No messages');return false;
	}else{
		$.ajax({
			url: BASE_URL+'/check-blocked-user',
			dataType: "json",
			type	: "POST",
			data	:{blocked_to_uid:blocked_to_uid},
			success: function( data ) {
					if(data.output==0) {		
						$.ajax({
							url: BASE_URL+'/insert-blocked-user',
							dataType: "json",
							type	: "POST",
							data	:{blocked_to_uid:blocked_to_uid},
							success: function( data ) {
									if(data.output!=0) {		
										alert('Inserted blocked User');
									}
							}				
						});
					}else {
						alert('Already  blocked user');
					}
			}				
		});
	}
}
function composeMail(){
	$("#divReplyToWrapper").show();
	$("#txtReplyTo").val('');
	$("#textArea").val('');
	$('#txtSubject').val('');
}
function replyTo(id){
		$("#divReplyToWrapper").show();
		$("#textArea").val('');
		var hidName=$("#hidUserName").val();
		$("#txtReplyTo").val(hidName);
}
function forwardTo(id){
		$("#divReplyToWrapper").show();
	    $("#txtReplyTo").val('');
		var hidmessage=$("#hidmessage").val();
	    $("#textArea").val(hidmessage);
}
function messageChangeStatus(msgId){
		$.ajax({
				url: BASE_URL+'/change-message-status',
				dataType: "json",
				type	: "POST",
				data	:{msgId:msgId},
				success: function( data ) {
						if(data.output!=0) {		
							$('#statusFlag'+msgId).remove();
						}
				}				
		});
}
function showMessage(msgId){
		$.ajax({
				url: BASE_URL+'/show-message-content',
				dataType: "json",
				type	: "POST",
				data	:{msgId:msgId},
				success: function( data ) {
					
					if(data.output!=0) {
							var userName="";
								userName=data.userName+',';
                            var divCommentTime="";
								divCommentTime='ON '+data.date;
							var divCommentText="";
								 divCommentText=data.msg;
							var newDiv='<button onClick="replyTo('+data.sendedId+')" class="btnCommentReply">REPLY</button><button onClick="forwardTo('+data.sendedId+')" class="btnCommentForward">FORWARD</button><button onClick="blockUser('+data.sendedId+')" class="btnCommentBlockUser">BLOCK USER</button><button onClick="reportSpam('+data.sendedId+','+data.receiverId+')"class="btnCommentReportSpam">REPORT SPAM</button>';
								$('#divCommentUsername').html('');
								$('#divCommentUsername').html(userName);
								$('#divCommentTime').html('');
								$('#divCommentTime').html(divCommentTime);
								$('#divCommentText').html('');
								$('#divCommentText').html(divCommentText);
								$('#divCommentControls').html('');
								$('#divCommentControls').html(newDiv);
								$('#hidUserName').val('');
								$('#hidUserName').val(data.userName);
								$('#hidmessage').val('');
								$('#hidmessage').val(data.msg);
								$('#hidsenderid').val('');
								$('#hidsenderid').val(data.sendedId);
								$('#hidreceivedid').val('');
								$('#hidreceivedid').val(data.receiverId);
								$("#txtReplyTo").val('');
								$("#textArea").val('');
					}
					
				}				
		});
		messageChangeStatus(msgId);
}
function insertMsg(){
var email=$('#txtReplyTo').val();
var msg_subject=$('#txtSubject').val();
var message=$('#textArea').val();
if(email==""){
	alert('Enter username');return false;
}
if(msg_subject==""){
	alert('Enter the message subject');return false;
}
if(message==""){
	alert('Enter the message');return false;
}
	$.ajax({
			url: BASE_URL+'/get-email-details',
			dataType: "json",
			type	: "POST",
			data	:{email:email},
			success: function( data ) {
				if(data.output!=0) {
				var msg_receiver_id=data.user_id;
					$.ajax({
						url: BASE_URL+'/insert-message',
						dataType: "json",
						type	: "POST",
						data	:{msg_receiver_id:msg_receiver_id,msg_subject:msg_subject,message:message},
						success: function( data ) {
							if(data.output!=0) {
								alert('Inserted Sucessfully');
								$('#txtReplyTo').val('');
								$('#txtSubject').val('');
								$('#textArea').val('');
							}
						}			
					});	
				}else{
					alert('No data is found');
				}
				
			}	
			
	});


		
}
function cancelForm(){
	  $("#divReplyToWrapper").hide();
}
</script>