<?
global $forgotPwdPage;
$forgotPwdPage='Yes';
?>
<link rel="stylesheet" type="text/css" href="<?php echo $basePath; ?>/css/sugarcake.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $basePath; ?>/js/crop/cropit.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $basePath; ?>/css/default.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $basePath; ?>/css/allfont.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $basePath; ?>/css/nexus_menu/component.css" />
<div class="body_main_container cat_top">
	<div class="body_middle_container">
		<div class=" form_top">
			<div class="row">
				<center>
					Email ID&nbsp;:&nbsp;<input type="text" class="text_pad" name="emailId" id="fpEmailId"/>
					<p id="forgotPwdSbmt" class="fp_sbmt_btn"><a href="javascript:void(0)" class="btn" onClick="Javascript:checkFpEmailId();">SUBMIT</a></p>
					<p class="fp_sbmt_btn" id="loadingFp" style="display:none;"><img  style="vertical-align:middle;width:30px;" src="<?php echo $basePath; ?>/images/social_media/bx_loader.gif" />Mailing password reset link...</p>
					<p class="fp_home_link"><a href="/taggerzz-new/trunk/">Home Page</a></p>
				</center>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="<?php echo $basePath; ?>/js/project/common-functions.js"></script>
<script type="text/javascript" src="<?php echo $basePath; ?>/js/popupwindow.js"></script>