<?
global $forgotPwdPage;
$forgotPwdPage='Yes';
?>
<div class="tfogotcontainer">
<div class="tmar_t125 tac_bg tforgot_p">
				<center>
					<div class="tforgot_title">FORGOT PASSWORD</div>
					<div>Email ID&nbsp;:&nbsp;<input type="text" class="tforgot_inputbrg" name="emailId" id="fpEmailId"/></div>
					
					<div id="forgotPwdSbmt" class="fp_sbmt_btn">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="javascript:void(0)" class="btn" onClick="Javascript:checkFpEmailId();">SUBMIT</a></div>
					
					<div class="fp_sbmt_btn" id="loadingFp" style="display:none;"><img  style="vertical-align:middle;width:30px;" src="<?php echo $basePath; ?>/images/social_media/bx_loader.gif" />Mailing password reset link...</div>
				</center>
</div>
</div>
<script type="text/javascript" src="<?php echo $basePath; ?>/js/project/common-functions.js"></script>
<script type="text/javascript" src="<?php echo $basePath; ?>/js/popupwindow.js"></script>