<?
global $loginType;
$loginType='emailLogin';
global $step;
$step=2;
?>
<link rel="stylesheet" type="text/css" href="<?php echo $basePath; ?>/css/default.css" />
	<div class="tfogotcontainer">
		<div class="tmar_t125 tac_bg" style="padding:20px 0;">
			<center>
				<p class="tmar_b5">A Verification mail has been sent to your email id</p>
				<p class="tmar_b5"><?php echo $this->email; ?></p>
				<p class="tmar_b5">Kindly click on the link to complete Verification.</p>
				<p>(check your junk folders if you have not received.)</p>
			</center>
		</div>
	</div>