<?
global $loginType;
$loginType='emailLogin';
global $step;
$step=3;
?>
<link rel="stylesheet" type="text/css" href="<?php echo $basePath; ?>/css/default.css" />
<div class="tfogotcontainer">
	<div class="tmar_t125 tac_bg" style="padding:20px 0;">
		<center>
			<p class="tmar_b5">Thank you for Verifying your Email ID, You can start sharing your Collections of Web links as Databoxes and Highlights.</p>
			<p class="tmar_b5">Read and Learn our "<a href="https://taggerzz.com/blog/taggerzz-terms-and-conditions.htm" target="_blank"><b>Terms and Conditions</b></a>" before starting your activity. </p>
			<p class="tmar_b5 highlight_c"><a href="javascript:void(0);" onclick="gotoCategoryChoicePage('<?echo $this->encryptId;?>')"><h3><b>Continue To Login<b></h3></a></p>
		</center>
	</div>
</div>
<script>
function gotoCategoryChoicePage(id){
	window.location=BASE_URL+'/databoxuser/user-verified/'+id+'-<?echo $this->encryptedRand;?>'+'-LG';
}
</script>
