<?
global $loginType;
$loginType='emailLogin';
global $step;
$step=3;
?>
<link rel="stylesheet" type="text/css" href="<?php echo $basePath; ?>/css/default.css" />
<div class="tfogotcontainer">
	<div class="tmar_t125 tac_bg" style="padding:20px 0;">
		<center>
			<p class="tmar_b5">Thank you for verifying your email ID and joining</p>
			<p class="tmar_b5">with us to contribute Knowledge.</p>
			<p class="tmar_b5 highlight_c"><a href="javascript:void(0);" onclick="gotoCategoryChoicePage('<?echo $this->encryptId;?>')">Continue</a></p>
		</center>
	</div>
</div>
<script>
function gotoCategoryChoicePage(id){
	window.location=BASE_URL+'/databoxuser/user-verified/'+id+'-<?echo $this->encryptedRand;?>'+'-LG';
}
</script>
