
<link href="<?php echo $basePath; ?>/css/default.css" rel="stylesheet" type="text/css" /><!--<div class="" style="margin-top: 115px;">
	
</div>
<div class="montage_container2">
	<div>
		<?php 
		if(isset($_GET['status']) && $_GET['status']!="2"){
			echo "Congrates, Recharge Sucess";
		}else{
			echo "rechage fail";
		}
		?>
	</div>
</div>-->             <div align="center" >
						<div style="margin-top:250px" >
						<h3>Congrates</h3>
						<div class="" style=" width: 300px;padding: 20px;border: 1px solid #8fc304;margin: 25px; border-radius:2px">
						   
				
							<div class=""><h4 style="margin:auto;color:green;margin:auto">Recharge successful</h4>
							</div>
						</div>
					</div>
					</div>
		