
<link href="<?php echo $basePath; ?>/css/default.css" rel="stylesheet" type="text/css" />  

<div align="center" >
	<div style="margin-top:250px" >
		<?php 
		$color='';
		if(isset($_GET['status']) && $_GET['status']=="SUCCESS"){
			$color='green';
		?>
		<h3>Congrates</h3>
		<?php } else if(isset($_GET['status']) && $_GET['status']=="PENDING"){ 
			$color='orange';
		} else{
			$color='red';
		}
		?>
		<div class="" style=" width: 300px;padding: 20px;border: 1px solid #8fc304;margin: 25px; border-radius:2px">
		   

			<div class=""><h4 style="margin:auto;color:<?php echo $color;?>;margin:auto">Recharge is <?php echo $_GET['status'] ?></h4>
			</div>
		</div>
	</div>
</div>
		