<?
global $forgotPwdPage;
$forgotPwdPage='Yes';
?>
<div class="tfogotcontainer">
	<div class="tmar_t125 tac_bg tforgot_p">
	<center>
			<div class="tforgot_title">RESET PASSWORD</div>
				
					<?php
						if( isset($this->tokenExists) && ($this->tokenExists==1) )
						{
					?>
							<div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;New Password&nbsp;:&nbsp;<input type="password" class="tforgot_inputbrg" name="newPassword" id="newPassword"/></div>
							<div class="reset_cnf_div"><p>Confirm Password&nbsp;:&nbsp;<input type="password" class="tforgot_inputbrg" name="confirmPassword" id="confirmPassword"/></p></div>
							<div class="fp_sbmt_btn" id="resetPwdSbmt"><a href="javascript:void(0)" class="btn" onClick="Javascript:checkFpPassword();">RESET PASSWORD</a></div>
							<div class="fp_sbmt_btn" id="loadingFp" style="display:none;"><img  style="vertical-align:middle;width:30px;" src="<?php echo $basePath; ?>/images/social_media/bx_loader.gif" />Resetting your password...</div>
							<input type="hidden" id="hidtoken" name="hidtoken" value="<?echo $_GET['token'];?>"/>
					<?php
						}
						else
						{
					?>
							<div><p>Your link has expired.</p></div>
					<?php
						}
					?>
				</center>
			</div>
	</div>
<script type="text/javascript" src="<?php echo $basePath; ?>/js/project/common-functions.js"></script>
<script type="text/javascript" src="<?php echo $basePath; ?>/js/popupwindow.js"></script>