<input type="hidden" id="boxesterm" name="boxesterm" value="" />
<?php
		$dashBoardActive	='';
		$montageActive		='';
		$accountActive		='';
		$homeActive			='';
		$hintingOnActive		='';
		$createActive		='';
		if($_SERVER['REQUEST_URI']=='/databoxuser/dashboard'){
			$dashBoardActive='active_menu';
			
		}else if($_SERVER['REQUEST_URI']=='/montage'){
			$montageActive='active_menu';
			
		}else if($_SERVER['REQUEST_URI']=='/accounts'){
			$accountActive='active_menu';
			
		}else if($_SERVER['REQUEST_URI']=='/contentpage'){
			$homeActive='active_menu';
			
		}else if($_SERVER['REQUEST_URI']=='/hitting-on'){
			$hintingOnActive='active_menu';
			
		}else if($_SERVER['REQUEST_URI']=='/taggerzz/databox/category-choice'){
			$createActive='active_menu';
			
		}
		$header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
		$baseUrl = $header->headerarray['baseUrl'];
		$basePath = $header->headerarray['basePath'];
		global $cropUrl;
	?>
	<script> 
	
	var newCommentText = "";
	var tzGridStackRef;
	
	var BASE_URL = '<?php echo $baseUrl;?>';
	var BASE_PATH = '<?php echo $basePath;?>';
	var crop_url='<?echo $cropUrl;?>';
	var crop_value='';
	var crop_value_count=0;
	var crop_value_countt=0;
	var chkvalues=0;
	var _URL = window.URL || window.webkitURL;
	
	</script>

<!--All the CSS-->
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
<script type="text/javascript" charset="utf-8">
function logOut(value)
{
	if( chkvalues==0 )
	{
	}
	else
	{
		$('#pop-up-alerts').popUpWindow({action: "open"});	
		$("#alert_header_meassge").html('');
		$("#alert_meassage").html(verifying_urls_alert);
		return false;
	}

	var logoutUrl = '<?php echo $baseUrl; ?>' + "/application/logout";
	$.ajax
	({
		url: logoutUrl,
		success: function(data)
		{
			if(value!=""){
				$('#deactiveLoad').hide();
				var logoutUrl = '<?php echo $baseUrl; ?>' + "/application/deactivate";
				window.location=logoutUrl;
			}else{
				if(data.output=='success')
				{
					window.location='<? echo $this->Url('mainpage');?>';
				}
			}
		}
	});	
}
</script>
<link href='//fonts.googleapis.com/css?family=Raleway:500' rel='stylesheet' type='text/css'>
	<?php
if( $_SERVER['REQUEST_URI']== "/taggerzz/" && $_SERVER['REQUEST_URI']== "/taggerzz/signup" )
	{
		?> 
	<link rel="stylesheet" media="(max-width: 799px)" href="<?php echo $basePath; ?>/css/new_css/styles-mobile.css" />
	<link  href="<?php echo $basePath; ?>/css/new_css/styles.css" rel="stylesheet" type="text/css" />
	<?php } else{?>
		<? if(strpos($cropUrl, "post-vertical") == false && strpos($cropUrl, "post-horizontal") == false){?>
		
		<?php } ?>
		<link media="screen and (min-width: 800px)" href="<?php echo $basePath; ?>/css/new_css/styles.css" rel="stylesheet" type="text/css" />
		<link rel="stylesheet" media="(max-width: 799px)" href="<?php echo $basePath; ?>/css/new_css/styles-mobile.css" />
		
	<link  href="<?php echo $basePath; ?>/css/new_css/jquery-ui-1-11-4.css" rel="stylesheet" type="text/css" />
	<link  href="<?php echo $basePath; ?>/css/new_css/developer.css" rel="stylesheet" type="text/css" />
	<? } ?>
<link rel="stylesheet" type="text/css" href="<?php echo $basePath; ?>/css/popupwindow.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $basePath; ?>/css/custom-style.css" />


	<?php
if( $_SERVER['REQUEST_URI'] != "/taggerzz/" || $_SERVER['REQUEST_URI']== "/taggerzz/signup" )
	{
	?> 

<script type="text/javascript" src="<?php echo $basePath; ?>/js/project/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="<?php echo $basePath; ?>/js/project/jquery-172.min.js"></script>
	<? }else{ ?>
		<script src="<?php echo $basePath; ?>/js/new_js/libs/jquery/jquery.js"></script>
	<? } ?>

<? if(strpos($cropUrl, "post-vertical") == false && strpos($cropUrl, "post-horizontal") == false){?>
<script type="text/javascript" src="<?php echo $basePath; ?>/js/project/jquery-172-ui.min.js"></script>
<? } ?>

<script type="text/javascript" src="<?php echo $basePath; ?>/js/project/jquery-ui-1.7.2.min.js"></script>
<? if(strpos($cropUrl, "post-vertical") == false && strpos($cropUrl, "post-horizontal") == false){?>
<script type="text/javascript" src="<?php echo $basePath; ?>/js/project/jquery-172-ui.min.js"></script>
<? } ?>
<script type="text/javascript" src="<?php echo $basePath; ?>/js/project/jquery.nicescroll.min.js"></script>
<script src="<?php echo $basePath; ?>/js/new_js/custom_non_landingpage.js"></script>


<script type="text/javascript" src="<?php echo $basePath; ?>/js/project/index.js"></script>
<script src="<?php echo $basePath; ?>/js/jquery.cookie.js"></script>

<?php
if( $_SERVER['REQUEST_URI']!= "/taggerzz/" )
	{
		?>   
		<div id="mainContainerWrapper" class="mainContainerWrapper">
		<div class="tfix_header">
		<?php if( isset($_SESSION['usersinfo']->userId) &&  $_SESSION['usersinfo']->userId!=""){?>
		<div class="invite_f"><a class="tag_chk " href="javascript:void(0)" onClick="inivite_frnd()" >Invite Friends</a></div>
		<div class="reward_points"><b><?php if(isset($_SESSION['usersinfo']->rewardPoints)){echo $_SESSION['usersinfo']->rewardPoints ; }else{ echo '0000';}?></b><sub>POINTS</sub><b>00</b><sub>INR, Worth</sub><a href="#" title="Conversion is possible at 1000 points."> Convert</a></div>
		<? } ?> 
		 <section id="secHeader">
    <div id="divHeaderWrapper" class="width100 divHeaderWrapper">
        <div id="divMobileMenuWrapper" class="divMobileMenuWrapper">
            <img src="<?php echo $basePath; ?>/img/imgMenuCollapse.png" alt="" id="imgMenuCollapse" class="width25 autoPadding" />
        </div>
		<?php if( isset($_SESSION['usersinfo']) ) {
					$hintingUserId = 0;
					if( isset($_SESSION['usersinfo']->userId) )
					{
						$hintingUserId = $_SESSION['usersinfo']->userId;
					}
					$hintingState = "on";
					$hintingNewVal = 0;
					if( isset($_SESSION['usersinfo']->hinting_state) )
					{
						if( $_SESSION['usersinfo']->hinting_state == 0 )
						{
							$hintingState = "off";
							$hintingNewVal = 1;
						}
					}
					
					$headerMontageImage="";
					if( strpos($_SESSION['usersinfo']->montage_image, "https://" ) !== false || strpos($_SESSION['usersinfo']->montage_image, "http://") !== false )
					{
						$headerMontageImage=$_SESSION['usersinfo']->montage_image;
					}
					else
					{
						$headerMontageImage=$basePath.'/images/project/montageImages/'.$_SESSION['usersinfo']->montage_image;
					}?><div id="divAccountInfo" class="divAccountInfo twidth_acinfo" style="padding-left:36px;margin-top:4px;">
            <div id="divProfileImage" class="inline-block">
                <!--<img src="<?php //echo $basePath; ?>/img/imgFB.png" alt="" class="height100" />-->
                <img height="60px" width="46px" src="<?php echo $headerMontageImage; ?>" alt="" class="height100" />
            </div>

            <div id="divProfileDetails" class="inline-block tphoto_links tphoto_links">
                 <span id="spnGreetingsText" class="block smallFont">Hello, <?php echo $_SESSION['usersinfo']->displayName; ?></span>
                   <!-- <span id="spnUsername" class="block defaultFont"></span>-->
                    <span id="spnMessages" class="block verySmallFont">[<?php if(isset($_SESSION['usersinfo']->userMessagesCount)){echo $_SESSION['usersinfo']->userMessagesCount ; }else{ echo '0';}?> <a href="/taggerzz-new/trunk/databoxuser/dashboard#msgoto">Messages</a>, <span id="tzUserCollCountSpan"><?php if(isset($_SESSION['usersinfo']->collectionsCount)){echo $_SESSION['usersinfo']->collectionsCount; }else{ echo '0';}?></span>  <a class="tag_chk" href="javascript:void(0)" onClick="goToLocation('/databox/my-collected-links')">Collections</a>]</span>
                    <span id="spnCreateCollection" class="block smallFont highlightFont tmar_t9"><a href="#" class="highlightFont createCollection create_btn" id='createCollection'>+ Create Collection</a></span>
            </div>
        </div>
        <div id="divLogoWrapper" class="width30 marginallyCenter logo_home_new_size">
            <div class="width100 logo_martb5">
                <a href="/contentpage"><img src="<?php echo $basePath; ?>/img/imgLogo.png" alt="" class="imgLogo width100" /></a>
            </div> 
        </div>
        <div id="divLeftSlideMenu" class="divLeftSlideMenu">

            <div id="divAccountInfoMobile" class="divAccountInfo mobile">
                <div id="divProfileImageMobile" class="divProfileImage ">
                    <!--<img src="<?php //echo $basePath; ?>/img/imgFB.png" alt="" class="height100" />-->
					 <img height="68px" width="46px" src="<?php echo $headerMontageImage; ?>" alt="" class="height100" />
                </div>
                <div id="divProfileDetailsMobile" class="divProfileDetails">
                    <span id="spnGreetingsText" class="block smallFont">Hello, <?php echo $_SESSION['usersinfo']->displayName; ?></span>
                    <!--<span id="spnUsername" class="block defaultFont"></span>-->
                    <span id="spnMessages" class="block verySmallFont">[<?php if(isset($_SESSION['usersinfo']->userMessagesCount)){echo $_SESSION['usersinfo']->userMessagesCount ; }else{ echo '0';}?> <a href="/taggerzz-new/trunk/databoxuser/dashboard#msgoto">Messages</a>, <span id="tzUserCollCountSpan"><?php if(isset($_SESSION['usersinfo']->collectionsCount)){echo $_SESSION['usersinfo']->collectionsCount; }else{ echo '0';}?></span>  <a class="tag_chk" href="javascript:void(0)" onClick="goToLocation('/databox/my-collected-links')">Collections</a>]</span>
                    <span id="spnCreateCollection" class="block smallFont highlightFont"><a href="#" class="highlightFont createCollection create_btn" id='createCollection'>+ Create Collection</a></span>
                </div>
            </div>
			<div class="mar_b5 margin_top_20">
            <ul id="ulMenu" class="ulMenu tmenufont_inc">
                <li> <a class="tag_chk  <?php echo $homeActive; ?>" href="javascript:void(0)" onclick="goToLocation('/contentpage')">Home</a> </li>
				<li> <a class="tag_chk  <?php echo $montageActive; ?>" onClick="goToLocation('/montage')" href="javascript:void(0)" >My Profile</a></li>
                <li> <a class="tag_chk <?php echo $accountActive; ?>" href="javascript:void(0)" onClick="goToLocation('/accounts')">Account Settings</a> </li>
                <li> <a class="tag_chk <?php echo $dashBoardActive; ?>" href="javascript:void(0)" onClick="goToLocation('/databoxuser/dashboard')">Dashboard</a> </li>
                 <li class="invite_hide"> <a class="tag_chk" href="javascript:void(0)" onClick="inivite_frnd()">Invite Friends</a> </li>
                <li class="rewards_hide"> <b><?php if(isset($_SESSION['usersinfo']->rewardPoints)){echo $_SESSION['usersinfo']->rewardPoints ; }else{ echo '0000';}?></b> <sub>POINTS</sub> <b>00</b> <sub>INR, Worth</sub><a href="#" title="Conversion is possible at 1000 points."> Convert</a></li>
				<li> <a class="tag_chk " href="javascript:void(0)" onClick="goToLocation('logout')" >Logout</a> </li>
            </ul>
			</div>
        </div>
		<div id="divSearchBoxes" class="divSearchBoxes tinput_s">
            <input type="text" id="searchTermHolder" class="inptSearchHashTag tplaceholder_c" value="<?if(isset($_REQUEST['serTag']) && $_REQUEST['serTag']!=""){echo '#'.$_REQUEST['serTag'];}else{}?>" placeholder="Search by #hashtag"/>
            <input type="text" id="pvtUniqueCodeHolder" class="inptSearchUniqueCode" placeholder="Search by private databox unique code" value="<?if(isset($_REQUEST['serCode']) && $_REQUEST['serCode']!=""){echo $_REQUEST['serCode'];}else{}?>"/>
            <a href="Javascript:void(0);" id='homeSearchLink' class="aSearch"></a>
        </div>
			<?php
				} else { ?>
					<style>
						.tmar_t{ padding-top: 75px;}
						.tmar_t125{ margin-top: 95px;}
						.horizontalMenu li:not(:last-child)::after, .divHeaderWrapper .divLeftSlideMenu li:not(:last-child)::after{content:'';}
						.tfix_header{border-top:0;}
					</style>
					<div id="divLogoWrapper" class="width30 marginallyCenter withoutlogin_logo">
						<div class="width100">
							<a href="/contentpage"><img src="<?php echo $basePath; ?>/img/imgLogo.png" alt="nagaraju" class="imgLogo width100" /></a>
						</div>
					</div>
				<div>
				<div id="divLeftSlideMenu" class="divLeftSlideMenu">
					<div id="divAccountInfoMobile" class="divAccountInfo mobile">
					</div>
					<div class="mar_b5">
					<ul id="ulMenu" class="ulMenu">
							<!--<li><a href="<?php echo $baseUrl; ?>/signup">SignUp</a></li>
							<li><a href="<?php echo $baseUrl; ?>">SignIn</a></li>-->
							<!--<li><a href="/contentpage" class="link_email_login">HOME</a></li>-->
						<li><a id="signup-pop-up" href="javascript:void(0);" onclick="signUpWindow()" class="link_email_login tsignup_bg">SIGN UP</a></li>
						<li><a id="open-pop-up-1" href="javascript:void(0);" onclick="loginWindow()" class="link_email_login tlogin_bg">LOGIN</a></li>
					</ul>
					</div>
				</div>
				</div>
				<?php
				//if( $_SERVER['REQUEST_URI']== "/contentpage" )
				//{
				?> 
				<div id="divSearchBoxes" class="divSearchBoxes tinput_s">
						<input type="text" id="searchTermHolder" class="inptSearchHashTag tsearch_input_w tplaceholder_c" placeholder="Search by #hashtag" value="<?if(isset($_REQUEST['serTag']) && $_REQUEST['serTag']!=""){echo '#'.$_REQUEST['serTag'];}else{}?>"/>
						<a href="Javascript:void(0);" id='homeSearchLink' class="aSearch "></a>
				</div>
				<?php // } ?>
				<?php
					global $forgotPwdPage;
					global $browserDispPage;
					global $errorDispPage;
					global $loginType;
					global $step;
					if( $loginType == "emailLogin" )
					{
				?>
						<!--<p>LOGIN PROCESSING(<?echo $step;?> OF 3 STEPS)</p>-->
				<?php
					}
					else if( $forgotPwdPage == "Yes" )
					{
				?>
						<!--<p><strong>Forgot Password</strong></p>-->
				<?php
					}
					else if( $browserDispPage == "browserDisp" )
					{
				?>
						<p><strong></strong></p>
				<?php
					}
					else if( $errorDispPage == "errorDisp" )
					{
				?>
						<p><strong></strong></p>
				<?php
					}
					else
					{
				?>
						<!--<div class="email_login_home" id="openloginwindwo"><a id="open-pop-up-1" href="#pop-up-1" onclick="loginWindow()" class="link_email_login">LOGIN</a></div>
						<div class="email_login_home"><a id="signup-pop-up" href="javascript:void(0)" onclick="signUpWindow()" class="link_email_login">SIGN UP</a></div>-->
				<?php
					}}
				?>
				</div>
</section>
</div>
<section id="secModal" class="">
    <div class="divModalBlurBackground">
        <div class="divModalContentWrapper create_collection">
            <div class="divModalClose">&times;</div>
            <a href="javascript:void(0)"  onClick="goTohashtag('highlights')" class="divModalBox">
                <div class="divModalHeading heading_font_pt12">
					HIGHLIGHTS &AMP; CURRENT AFFAIRS
                </div>
                <img src="<?php echo $basePath; ?>/img/modalbox1.png" class="imgModalBoxImage" alt="" />
                <div class="divModalDescription">
                    Present your ideas by sharing your preffered collection of weblinks about the current issues
                    or on-going crisis or any current news and customize with your opinions as well #hashtag identify.
                </div>
            </a>

            <a href="javascript:void(0)"  onClick="goTohashtag('publicPrivate')" class="divModalBox">
                <div class="divModalHeading heading_font_pt12">
                    PUBLIC &AMP; PRIVATE DATABOX
                </div>
                <img src="<?php echo $basePath; ?>/img/modalbox2.png" class="imgModalBoxImage" alt="" />
                <div class="divModalDescription">
                    Collected links can be shared with your opinions as well by uploading chrome or firefox's bookmark files
                    to share your knowledge on any particular aspect to publish privately or for public. 
                </div>
            </a>
        </div>
    </div>
</section>
<?php  } ?>
<?php
	$loginDomAction=$this->action('Application\Controller\IndexController', 'logindomAction');
	$socialOptions = $header->loginarray['options'];
?>

<div id="pop-up-1" class="pop-up-display-content d">
<div class="tg_users_title">LOGIN USING ONE OF YOUR SOCIAL NETWORK</div>
<div class="tg_users_socila_login">
<?php
	echo '<div class="pp-lg-buttons">';
	foreach ($socialOptions->getEnabledProviders() as $provider) {
		echo  $this->socialSignInButton($provider, $this->redirect,$basePath);
	}
	echo '</div>';
?>

</div>

<div class="tg_users_email_login1">
	<div class="tg_users_email_login">OR</div>
	<div id="email_id_c" class="tg_users_email_login">YOUR EMAIL ID</div>
	<div class="tg_create_email">
		<form class="" method="post" id="userLoginFormUrl2" name="userLoginFormUrl2" role="form">
			<input type="hidden" id="categoryHighlight" name="categoryHighlight" value="0" />
			<input type="hidden" id="postHighlights" name="postHighlights" value="0" />
			<input type="hidden" id="nsfwMcSet" name="nsfwMcSet" value="0" />
			<input type="hidden" id="categoryId" name="categoryId" value="0" />
			<input type="hidden" id="hashName" name="hashName" value="" />
			<input type="hidden" id="categoryTitle" name="categoryTitle" value="" />
			<input type="hidden" id="settingId" name="settingId" value="0" />
			<input type="hidden" id="categoryImage" name="categoryImage" value="" />
			<p>Email ID</p>
			<input type="text" class="text_pad" name="emailId2" id="emailId2"/>
			<p id="c_password">Password</p>
			<input type="password" class="text_pad" name="userPassword2" id="userPassword2"/>
			<p class="tg_email_btn"><button name="btnSubmit" id="btnSubmit" type="button" class="btn" onClick="return checkLogin('loginPopup');">CONTINUE</button></p>
			<p class="tg_fp_btn"><a href="javascript:void(0)" id="forgot_password" class="home_anchor_black" onClick="Javascript:showFpEmailIdForm();"><b>Forgot Password?</b></a><span style="display:none"id="tgaccount"><span>Already have a Taggerzz account?</span>&nbsp;&nbsp;<a href="javascript:void(0);" class="home_anchor_black" onclick="loginWindow()"><b>Login</b></a></span></p>
			<span class="tg_email_btn success_display_c"><span id="userMessage2" style="display:none;font-size:8pt;" class="check_un_p">Checking Username,Password...</span></span>
			<input type="hidden" id="hid_log" name="hid_log" value="loginPopup">
			<div class="crete_acc">
				<p><span>Don't have an account</span>&nbsp;&nbsp;<a href="javascript:void(0);" onclick="signUpWindow()">Sign up now</a></p>
			</div>
		</form>
	</div>
</div>
</div>
<script>
function goTohashtag(title){
	if(title=="highlights"){
		if( setTzBoxId(0) )
		{
			window.location=BASE_URL+'/databox/createhashtag/highlight/0';
		}
		else
		{
			alert( "Highlight creation not available presently..." );
			return false;
		}
	}else{
		window.location=BASE_URL+'/databox/selectdatabox';
	}
}
$('#userPassword2').keypress(function(e) {
  if(e.which == 13) {
    // enter pressed
	checkLogin('loginPopup');
  }
}); 
</script>