<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="UTF-8">
	<?php
	global $homePageYes;
	if( (strpos($_SERVER['REQUEST_URI'],'post-vertical') !== false) || (strpos($_SERVER['REQUEST_URI'],'pre-vertical') !== false || strpos($_SERVER['REQUEST_URI'],'pre-horizontal') !== false) || (strpos($_SERVER['REQUEST_URI'],'post-horizontal') !== false) ){
		global $layoutTitle;
		global $layoutImage;
		global $layoutDescription;
		global $layoutUrl;
		global $layoutKeywords;
	?>
		<title><?php echo $layoutTitle; ?> - Taggerzz</title>
		<meta name="keywords" content="<?php echo $layoutKeywords; ?>">
		
		<meta property="og:type" content="article">
		<meta property="og:title" content="<? echo $layoutTitle; ?>">
		<meta property="og:image" content="<? echo $layoutImage; ?>">
		<meta property="og:image:width" content="200" />
		<meta property="og:image:height" content="200" />
		<meta property="og:description" content="<? echo $layoutDescription; ?>">  
		<meta property="og:url" content="<? echo $layoutUrl; ?>">
		<meta property="fb:app_id" content="608131635971702">

		
	<?php } else if( strpos($_SERVER['REQUEST_URI'],'montage') !== false ){
		global $layoutTitle;
		if( $layoutTitle != "" ){?>
			<title><?php echo $layoutTitle; ?></title>
	<?php }else{?>
	<title>#Tagging, Customize, Share Interests and Earn - Taggerzz.com</title>
	<?php }} else if( strpos($_SERVER['REQUEST_URI'],'user-collection') !== false ){
		global $layoutTitle;
		if( $layoutTitle != "" ){?>
			<title><?php echo $layoutTitle; ?></title>
	<?php } else {?>
	<title>#Tagging, Customize, Share Interests and Earn - Taggerzz.com</title>
	<?php }} else if( isset($homePageYes) && $homePageYes == "Yes" ){?>
	<title>Start #Tagging, Collecting Customizing Sharing – Taggerzz.com</title>
	<meta name="keywords" content="Public Databoxes,Private Databoxes, Highlights shared by Members,Cash rewarding Points,Free Mobile recharging,Cash rewarding,User activity">
	<meta name="description" content="Start #tagging here, collect and create Public databoxes and Private databoxes, Post any Highlighting content of Web by sharing Simple Web Paths.">
	<?php } else if( strpos($_SERVER['REQUEST_URI'],'dashboard') !== false ){?>
	<title>Your Dashboard, Edit your Shared content - taggerzz</title>
	<meta name="keywords" content="Edit or alter content,Edit Private Databoxes,Edit Highlights shared by Members,Customization mode Navigation,User activity">
	<meta name="description" content="Your Posted collections of Web links can be edited from this dashboard.">
	<?php } else if( strpos($_SERVER['REQUEST_URI'],'accounts') !== false ){?>
	<title>Manage your account - taggerzz</title>
	<meta name="keywords" content="Edit Your details,Change Profile name, ,Total User activity report,Profile picture,De-activate account">
	<meta name="description" content="Your account Details, Profile name/alias can be changed here.">
	<?php } else if( strpos($_SERVER['REQUEST_URI'],'category-choice') !== false ){?>
	<title>Create Your Collage, Upload Bookmark file & Hashtag your favorites - taggerzz</title>
	<meta name="keywords" content="Share and Customize your Ideas, Unique Opinions, Break Propagandists, Stereotypes, Bring change by your Opinions, Present and Share your Opinion by Web Links, Collect Customize present and share by Hashtag">
	<meta name="description" content="Upload your Bookmarks, Share your favorite Entertainment, Share your preferred Political Ideas">
	<?php } else if( strpos($_SERVER['REQUEST_URI'],'selectdatabox') !== false ){?>
	<title>Select Your Mode of Sharing - taggerzz</title>
	<?php } else if( strpos($_SERVER['REQUEST_URI'],'/databox/createhashtag/highlight/0') !== false ){?>
	<title>Creating Your Highlight - taggerzz</title>	
	<?php } else if( strpos($_SERVER['REQUEST_URI'],'databox/createhashtag/publicdatabox/0') !== false ){?>
	<title>Creating your Public Databox - taggerzz</title>
	<?php } else if( strpos($_SERVER['REQUEST_URI'],'databox/createhashtag/privatedatabox/0') !== false ){?>
	<title>Creating your Private Databox - taggerzz</title>
	<?php } else if( strpos($_SERVER['REQUEST_URI'],'contentpage') !== false ){?>
	 <title>Start #Tagging, Collecting Customizing Sharing – Taggerzz.com</title>
	<meta name="keywords" content="#Hashtag,Customize Link posts,Bookmark files upload, Private mode sharing,Unique #tagging,Public Databoxes,Private Databoxes,Post and share 100 web links">
	<meta name="description" content="Taggerzz.com is an Ideal Web Application to collage and Share Web Links of your Interests. Great tool to present your Ideas and Opinions.">
	<?php } else if( strpos($_SERVER['REQUEST_URI'],'enlist-highlights') !== false ){?>
	<title>Highlights and Current on-going Affairs - taggerzz</title>
	<meta name="keywords" content="Vote your preferred or valuable content">
	<meta name="description" content="Vote a current affair, Vote a Highlight, Up Vote or Down vote a Issue">
	<?php } else if( (strpos($_SERVER['REQUEST_URI'],'highlights-both') !== false) || (strpos($_SERVER['REQUEST_URI'],'edit-highlight') !== false) ){?>
	<title>Post a Internet Highlight with your preferred Website Links - taggerzz</title>
	<meta name="keywords" content="Create your Internet Highlight, Post a current Affair share with the world your Broader perspectives">
	<meta name="description" content="Post a current affair, Post your Highlight, Share your exclusive Knowledge about a current Issue">
	<?php } else if( (strpos($_SERVER['REQUEST_URI'],'predefined-both') !== false) || (strpos($_SERVER['REQUEST_URI'],'userdefined-both') !== false) || (strpos($_SERVER['REQUEST_URI'],'userdefined-bookmarks') !== false) ){?>
	<title>Upload Bookmarks or Manually Insert your Web Links - taggerzz</title>
	<meta name="keywords" content="Share and Customize your Ideas, Unique Opinions, Break Propagandists, Stereotypes, Bring change by your Opinions, Present and Share your Opinion by Web Links, Collect Customize present and share by Hashtag">
	<meta name="description" content="Upload your Bookmarks, Share your favorite Entertainment, Share your preferred Political Ideas">
	<?php } else {?>
			<title>#Tagging, Customize, Share Interests and Earn - Taggerzz.com</title>
	<?php } ?>
	<?php
		$header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
		$baseUrl = $header->headerarray['baseUrl'];
		$basePath = $header->headerarray['basePath'];
	?>
	<link rel="shortcut icon" href="<?php echo $basePath?>/images/social_media/favicon.ico" type="image/x-icon">
	<link rel="icon" href="<?php echo $basePath?>/images/social_media/favicon.ico" type="image/x-icon">
	<link href="https://plus.google.com/u/0/106787898385927742881" rel="publisher" />
			<script src="<?php echo $basePath; ?>/js/abDetector.min.js"></script>


</head>
<body>
<?php $page=basename($_SERVER['REQUEST_URI']); if($page=="intro"){

		echo $this->content;
	}else{?>
	<?php include_once("analyticstracking.php") ?>
	<? include "header.phtml"; ?>
	<?php echo $this->content; ?>
	<? include "footer.phtml"; ?> 
	<? } ?>
	</body> 
</html>
