<div class="main_container_search_block">
	<div class="container_search_block">
		<!--<div class="search_title_box">Search</div>
		<div class="search_box_block">
			<input name="" type="text" class="search_box_props" />
		</div>
		<div class="block_search_n_menu">
			<div class="go_search_btn">
				<img src="<?php //echo $basePath; ?>/images/go_search_btn.png" width="30" height="30" />
			</div>
			<div class="cats_menu_block">
				<ul id="gn-menu" class="gn-menu-main">
					<li class="gn-trigger"> 
						<a class="gn-icon gn-icon-menu"><span>Menu</span></a>
						<nav style="box-sizing: border-box;" class="gn-menu-wrapper  main_categories">
							<div class="gn-scroller">
								<ul class="gn-menu">
								  <li> <a class="gn-icon gn-icon-download">Entertainment</a>
									<ul class="gn-submenu">
									  <li><a class="gn-icon gn-icon-illustrator">#NewRJD</a></li>
									  <li><a class="gn-icon gn-icon-photoshop">#Hollywoodgosips</a></li>
									</ul>
								  </li>
								  <li><a class="gn-icon gn-icon-cog">Settings</a></li>
								  <ul class="gn-submenu">
									<li><a class="gn-icon gn-icon-article">Articles</a></li>
									<li><a class="gn-icon gn-icon-pictures">Images</a></li>
									<li><a class="gn-icon gn-icon-videos">Videos</a></li>
									<li><a class="gn-icon gn-icon-article">Articles</a></li>
									<li><a class="gn-icon gn-icon-videos">Videos</a></li>
									<li><a class="gn-icon gn-icon-article">Articles</a></li>
									<li><a class="gn-icon gn-icon-pictures">Images</a></li>
									<li><a class="gn-icon gn-icon-videos">Videos</a></li>
								  </ul>
								  <li><a class="gn-icon gn-icon-help">Help</a></li>
								  <li> <a class="gn-icon gn-icon-archive">Archives</a>
									<ul class="gn-submenu">
									  <li><a class="gn-icon gn-icon-article">Articles</a></li>
									  <li><a class="gn-icon gn-icon-pictures">Images</a></li>
									  <li><a class="gn-icon gn-icon-videos">Videos</a></li>
									  <li><a class="gn-icon gn-icon-article">Articles</a></li>
									  <li><a class="gn-icon gn-icon-videos">Videos</a></li>
									  <li><a class="gn-icon gn-icon-article">Articles</a></li>
									  <li><a class="gn-icon gn-icon-pictures">Images</a></li>
									  <li><a class="gn-icon gn-icon-videos">Videos</a></li>
									</ul>
								  </li>
								</ul>
							</div>
						</nav>
					</li>
				</ul>
			</div>
		</div>-->
	</div>
</div>
<div class="body_main_container">
	<div class="body_middle_container">
		<div class=" form_top">
			<div class="row">
				<center>
					<p>
						Your Account is Deactivate 
					</p>
					<p>Please check Your mail.Then go to relogin. 
					</p>
				</center>
			</div>
		</div>
	</div>
</div>
