<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php if(!isset($_SESSION['usersinfo']) ){?>
    <head>
        <title>Taggerzz</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width">
		
	<?php
//unset($_SESSION['sLoginFValue']);
//unset($_SESSION['sLoginGValue']); exit;
 global $facebook_login;
	global $google_login;
	global $facebookAppId;
	if(!isset($_SESSION['usersinfo'])){
	if(!isset($_SESSION['logoutStatus'])){
		$_SESSION['logoutStatus']=0;
		$value=0;
	}else if(isset($_SESSION['logoutStatus']) && $_SESSION['logoutStatus']==1){
		unset($_SESSION['logoutStatus']);
		$value=1;
	}else if(isset($_SESSION['logoutStatus']) && $_SESSION['logoutStatus']==0){
		$value=0;
	}
	
	if($value==0){
?>
<script type="text/javascript">
function show_login_status(network, status)
{
	if (status)
	{
		if( $('#tpName').html() != ""  )
		{
			$('#socialLoginSecond').val( network );
			return false;
		}
		if(network=='Facebook'){
			$('#tpName').html( 'Facebook' );
		}else if(network=='Google'){
			$('#tpName').html( 'Google' );
		}
		$('#popUpConfirmTpLogin').popUpWindow({action: "open"});
	}
}



</script>
<script>
window.fbAsyncInit = function(){
	FB.init({ appId:'<?echo $facebookAppId;?>', status:true,  cookie:true, xfbml:true});
	FB.getLoginStatus(function(response){
		if (response.status != "unknown")
		{
			show_login_status("Facebook", true);
		}else{
			//show_login_status("Facebook", false);
			checkGoogleLogin(2);
		}
	});
};
// Load the SDK Asynchronously
(function(d){
	var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
	js = d.createElement('script'); js.id = id; js.async = true;
	js.src = "//connect.facebook.net/en_US/all.js";
	d.getElementsByTagName('head')[0].appendChild(js);
}(document));

function checkGoogleLogin(valGoogle){
	if(valGoogle==2){
		$('#checkGoogleLogin1').val(valGoogle);
		var googleValue=$('#checkGoogleLogin').val();
		if(googleValue==1){
			show_login_status( 'Google',true );
		}
	}else{
		$('#checkGoogleLogin').val(valGoogle);
		if(valGoogle==1){
			$('#socialLoginSecond').val( 'Google' );
		}
	}
}
</script>
<img style="display:none;"
onload="checkGoogleLogin(1)"
onerror="checkGoogleLogin(0)"
src="https://accounts.google.com/CheckCookie?continue=https%3A%2F%2Fwww.google.com%2Fintl%2Fen%2Fimages%2Flogos%2Faccounts_logo.png&followup=https%3A%2F%2Fwww.google.com%2Fintl%2Fen%2Fimages%2Flogos%2Faccounts_logo.png&chtml=LoginDoneHtml&checkedDomains=youtube&checkConnection=youtube%3A291%3A1"
/>
<div id="fb-root"></div>
<?}}?>

<?php
	$header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
		$baseUrl = $header->headerarray['baseUrl'];
		$basePath = $header->headerarray['basePath'];
	$loginDomAction=$this->action('Application\Controller\IndexController', 'logindomAction');
	$socialOptions = $header->loginarray['options'];
	?>
<script type="text/javascript" src="<?php echo $basePath; ?>/js/project/login-ready.js"></script>
<input type="hidden" id="socialLoginSecond" value="" />
<input type="hidden" id="checkGoogleLogin" />
<input type="hidden" id="checkGoogleLogin1" value="0" />
		
        <!--
		<link rel="stylesheet" media="(max-width: 799px)" href="<?php echo $basePath; ?>/css/new_css/styles-mobile.css" /> 
        <link rel="stylesheet" href="<?php echo $basePath; ?>/css/new_css/styles.css" />
		-->
    </head>
    <body>
        <div id="mainWrapper" class="mainWrapper">
            <!--            Fixed Section-->
            <section id="secFixedAspects">
                <img id="imgBackgoundOverlay" class="imgBackground" src="<?php echo $basePath; ?>/img/imgLightBlueOverlay.png" alt="" />

              
                <div id="divLoaderWrapper" class="divLoaderWrapper">
                    <div id="divLoader" class="divLoader">
                        <div id="divLoaderText" class="divLoaderText">
                            <img src="<?php echo $basePath; ?>/img/imgLogo.png" alt=""/> <br>
                            <span id="spnLoaderText" class="spnLoaderText smallFont">Preparing awesome dashboard for you. Please wait...</span>
                        </div>
                    </div>
                </div>
            </section>
            
			 <!--            Left Section-->
            <section id="secLeftAspects" class="leftSticky verticalCenterWrapper">
                <div id="divLeftWrapper" class="divLeftWrapper verticalCenterContainer whiteFont">
                    <img id="imgLogo" class="imgLogo verticalCenter width100" src="<?php echo $basePath; ?>/img/imgLogo.png" alt="" /> <br>
                    <div id="divLogoText" class="divLogoText">
                        <span id="spnLogoText" class="verySmallFont spnLogoText">TAGGERZZ.COM IS A WEB PERSONALIZING &amp; IDEAS SHARING WEBSITE. GREAT HUB FOR GENERATING
                            YOUR IDEAS BY HOT LINKS SHARING AND CUSTOMISING.</span>
                    </div>
                </div>
            </section>
            <!--            Center Section-->
          <div class="ctrl_right_sticky">
               <div id="divLoginWrapper" class="divLoginWrapper rightSticky">
                        <div id="divLoginSocial" class="divLoginSocial smallFont whiteFont fatFont textCenter largeFont">
						<form class="" method="post" id="userLoginFormUrl1" name="userLoginFormUrl1" role="form" >
                            <div class="block">
                                <span class="fatFont _footer_text_shadow">LOGIN USING</span>
                            </div>
                            <div class="block">
								<?php
								foreach ($socialOptions->getEnabledProviders() as $provider) {
								echo  $this->socialSignInButton($provider, $this->redirect,$basePath);
								}
								?>
								<!--
                                <img id="imgFBLogin" class="imgSocialImage" src="<?php echo $basePath; ?>/img/imgFB.png" alt=""/>
                                <img id="imgGPlusLogin" class="imgSocialImage" src="<?php echo $basePath; ?>/img/imgGPlus.png" alt=""/>
								-->
                            </div>
                            <div class="block fatFont _footer_text_shadow">
                                OR
                            </div>
                            <div class="block textLeft _footer_text_shadow">
                                <label>Email</label> <br>
								<!--
                                <input type="email" name="txtEmail" id="txtEmail" class="formField txtEmail"/>
								-->
								<input type="email" name="emailId1" id="emailId1" class="formField txtEmail"/>
                            </div>
                            <div class="block textLeft _footer_text_shadow">
                                <label>Password</label> <br>
								<!--
                                <input type="password" name="txtPassword" id="txtPassword" class="formField txtPassword"/>
								-->
								<input type="password" name="userPassword1" id="userPassword1" class="formField txtPassword"/>
                            </div>
							<div class="block textLeft _footer_text_shadow">
								<label><input type="checkbox" name="remember_me" id="remember_me" value="" style="width:7% !important;">Remember Me</label> 									
							</div>
                            <div class="block textRight">
								<a href="javascript:void(0)" id="forgot_password"  onClick="Javascript:showFpEmailIdForm();">Forgot Password?</a>
								<!--
                                <button name="btnSubmit" id="btnSubmit" class="formField btnSubmit">SUBMIT</button>
								-->
								<button type="button" name="btnSubmit" id="btnSubmit" onClick="return checkLogin('loginChe');" class="formField btnSubmit _shadow_boxes">SUBMIT</button>
                            </div>
								<input type="hidden" id="hid_log" name="hid_log" value="logChe">
                            <div class="block textCenter _footer_text_shadow">
                                <label>Don't have account with us? </label><br>
								<!--
                                <button name="btnSignup" id="btnSignup" class="formField btnSignup">SIGNUP</button>
								-->
								<button type="button" name="btnSignup" id="btnSignup" class="formField btnSignup" onClick="Javascript:sUpFunction();" >SIGNUP</button>
                            </div>
                            <div class="block">
								<a href="<?php echo $baseUrl; ?>/contentpage">I'll do this later >></a>
                            </div>
							</form>
                        </div>
                    </div>
</div>

      <section id="secCenterAspects" class="secCenterAspects">
                <div id="divCenterWrapper" class="divCenterWrapper verticalCenterWrapper">
                    <div id="divCenter" class="divCenter verticalCenterContainer" >
			<div id="divCenterText" class="divCenterText verticalCenter textCenter">
                            <!--<ul class="ulCenterSlide">
                                <li>
                                    <img class="imgCenterImage" src="<?php //echo $basePath; ?>/img/c1.png" alt=""/> <br>
                                    <span class="spnCenterText smallFont whiteFont">
                                        Collect 100 web links per category, 1000 per user, recognizing 18 types of files.
                                    </span>
                                </li>
                                <li>
                                    <img  class="imgCenterImage" src="<?php //echo $basePath; ?>/img/c2.png" alt=""/> <br>
                                    <span class="spnCenterText smallFont whiteFont">Preparing awesome dashboard for you. Please wait...</span>
                                </li>
                                <li>
                                    <img  class="imgCenterImage" src="<?php //echo $basePath; ?>/img/c3.png" alt=""/> <br>
                                    <span class="spnCenterText smallFont whiteFont">Preparing awesome dashboard for you. Please wait...</span>
                                </li>
                                <li>
                                    <img  class="imgCenterImage" src="<?php //echo $basePath; ?>/img/c4.png" alt=""/> <br>
                                    <span class="spnCenterText smallFont whiteFont">Preparing awesome dashboard for you. Please wait...</span>
                                </li>
                                <li>
                                    <img  class="imgCenterImage" src="<?php //echo $basePath; ?>/img/c5.png" alt=""/> <br>
                                    <span class="spnCenterText smallFont whiteFont">Preparing awesome dashboard for you. Please wait...</span>
                                </li>
                                <li>
                                    <img  class="imgCenterImage" src="<?php //echo $basePath; ?>/img/c6.png" alt=""/> <br>
                                    <span class="spnCenterText smallFont whiteFont">Preparing awesome dashboard for you. Please wait...</span>
                                </li>
                                <li>
                                    <img  class="imgCenterImage" src="<?php //echo $basePath; ?>/img/c7.png" alt=""/> <br>
                                    <span class="spnCenterText smallFont whiteFont">Preparing awesome dashboard for you. Please wait...</span>
                                </li>
                            </ul>-->

                        </div> 
                    </div>
                </div>
            </section>

            <div class="side_image">
          <img src="<?php echo $basePath; ?>/img/imgLeftArrow.png"></div>

            <!--            Right Section-->
            <!--            Bottom Section-->
        </div>
        
        <section id="secFooterAspects" class="bottomSticky">
                <div id="divFooterSentence" class="whiteFont">
                    <span class="fatFont intro_footer_text"><?php echo $totalHotLinksCount;?></span> <span class="smallFont _footer_text_shadow">HOT LINKS, PERSONALIZED AND SHARED,</span> <span class="fatFont  intro_footer_text"><?php echo $homeUsersCount;?></span> <span class="smallFont _footer_text_shadow">Users</span>
                </div>
            </section>
        
        <script src="<?php echo $basePath; ?>/js/new_js/custom.js"></script>

		<div id="popUpConfirmTpLogin" class="pop-up-display-content conform_popup_content">
			<p>Do you want to continue with your <b id="tpName"></b> login ?</p><br/>
			<p><a id="tpLoginLink" class="btn" href="Javascript:void(0);">CONTINUE</a>
			&nbsp;&nbsp;<a id="tpNoLink" class="btn" href="Javascript:void(0);">NO</a></p>
		</div>

    </body>
	
<script>

	function ianGetCookie(name) {
	  var value = "; " + document.cookie;
	  var parts = value.split("; " + name + "=");
	  if (parts.length == 2) return parts.pop().split(";").shift();
	}


function sUpFunction(){
	window.location=BASE_URL+ "/signup";
}
$(document).ready(function() {
	setInterval(function(){ $("#secFixedAspects").css({"display":"none"}); },2000);
	var remember = $.cookie('remember');
	if (remember == 'true') 
	{
		var email = $.cookie('email');
		var password = $.cookie('password');
		$('#emailId1').val(email);
		$('#userPassword1').val(password);
		$('#remember_me').attr('checked',true);
	}
	$('#tpLoginLink').click(function(event)
	{
		$('#popUpConfirmTpLogin').popUpWindow({action: "close"});
		if( $('#tpName').html() == 'Facebook' )
		{
			openPopup('<?echo $facebook_login;?>');
		}
		else if( $('#tpName').html() =='Google' )
		{
			openPopup('<?echo $google_login;?>');
		}
	});
	$('#tpNoLink').click(function(event)
	{
		$('#popUpConfirmTpLogin').popUpWindow({action: "close"});
		$('#tpName').html( "" );
		if( $('#socialLoginSecond').val() != ""  )
		{
			var socialLoginSecond = $('#socialLoginSecond').val();
			$('#socialLoginSecond').val( "" );
			var valGooglee=$('#checkGoogleLogin').val();
			var valGooglee1=$('#checkGoogleLogin1').val();
			if(valGooglee1==0){
				if(valGooglee==1){
					show_login_status( socialLoginSecond,true );
				}
			}
		}
	});
});
$('#userPassword1').keypress(function(e) {
	  if(e.which == 13) {
		// enter pressed
		checkLogin('loginChe');
	  }
  }); 
</script>

        <link rel="stylesheet" href="<?php echo $basePath; ?>/css/new_css/landing_.css" />        
        <link rel="stylesheet" href="<?php echo $basePath; ?>/css/new_css/media-queries.css" />                
<?}else{?>
	<script> window.location=BASE_URL+ "/contentpage"; </script>
<?}?>
