<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>Taggerzz</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width">
		<link href="<?php echo $basePath; ?>/css/new_css/styles.css" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <div id="mainWrapper" class="mainWrapper landingpage">
            <!--            Fixed Section-->
            <section id="secFixedAspects">
                <img id="imgBackgoundOverlay" class="imgBackground" src="<?php echo $basePath; ?>/img/imgLightBlueOverlay.png" alt="" />

                <div id="divLoaderWrapper" class="divLoaderWrapper verticalCenterWrapper onTop defaultFont">
                    <div id="divLoader" class="divLoader verticalCenterContainer">
                        <div id="divLoaderText" class="divLoaderText verticalCenter textCenter">
                            <img src="<?php echo $basePath; ?>/img/imgLogo.png" alt=""/> <br>
                            <span id="spnLoaderText" class="spnLoaderText smallFont">Preparing awesome dashboard for you. Please wait...</span>
                        </div>
                    </div>
                </div>
            </section>

            <!--            Left Section-->
            <section id="secLeftAspects" class="leftSticky verticalCenterWrapper">
                <div id="divLeftWrapper" class="divLeftWrapper verticalCenterContainer whiteFont">
                    <img id="imgLogo" class="imgLogo verticalCenter width100" src="<?php echo $basePath; ?>/img/imgLogo.png" alt="" /> <br>
                    <div id="divLogoText" class="divLogoText">
                        <span id="spnLogoText" class="verySmallFont spnLogoText">TAGGERZZ.COM IS A WEB PERSONALIZING &amp; IDEAS SHARING WEBSITE. GREAT HUB FOR GENERATING
                            YOUR IDEAS BY HOT LINKS SHARING AND CUSTOMISING.</span>
                    </div>
                </div>
            </section>

            <!--            Center Section-->
            <section id="secCenterAspects" class="secCenterAspects">
                <div id="divCenterWrapper" class="divCenterWrapper verticalCenterWrapper">
                    <div id="divCenter" class="divCenter verticalCenterContainer">
                        <div id="divCenterText" class="divCenterText verticalCenter textCenter">
                            <ul class="ulCenterSlide">
                                <li>
                                    <img class="imgCenterImage" src="<?php echo $basePath; ?>/img/c1.png" alt=""/> <br>
                                    <span class="spnCenterText smallFont whiteFont">
                                        Collect 100 web links per category, 1000 per user, recognizing 18 types of files.
                                    </span>
                                </li>
                                <li>
                                    <img  class="imgCenterImage" src="<?php echo $basePath; ?>/img/c2.png" alt=""/> <br>
                                    <span class="spnCenterText smallFont whiteFont">Preparing awesome dashboard for you. Please wait...</span>
                                </li>
                                <li>
                                    <img  class="imgCenterImage" src="<?php echo $basePath; ?>/img/c3.png" alt=""/> <br>
                                    <span class="spnCenterText smallFont whiteFont">Preparing awesome dashboard for you. Please wait...</span>
                                </li>
                                <li>
                                    <img  class="imgCenterImage" src="<?php echo $basePath; ?>/img/c4.png" alt=""/> <br>
                                    <span class="spnCenterText smallFont whiteFont">Preparing awesome dashboard for you. Please wait...</span>
                                </li>
                                <li>
                                    <img  class="imgCenterImage" src="<?php echo $basePath; ?>/img/c5.png" alt=""/> <br>
                                    <span class="spnCenterText smallFont whiteFont">Preparing awesome dashboard for you. Please wait...</span>
                                </li>
                                <li>
                                    <img  class="imgCenterImage" src="<?php echo $basePath; ?>/img/c6.png" alt=""/> <br>
                                    <span class="spnCenterText smallFont whiteFont">Preparing awesome dashboard for you. Please wait...</span>
                                </li>
                                <li>
                                    <img  class="imgCenterImage" src="<?php echo $basePath; ?>/img/c7.png" alt=""/> <br>
                                    <span class="spnCenterText smallFont whiteFont">Preparing awesome dashboard for you. Please wait...</span>
                                </li>
                            </ul>

                        </div>
                    </div>
                </div>
            </section>

            <!--            Right Section-->
            <section id="secCenterAspects" class="secCenterAspects">
                <div id="divCenterWrapper" class="divCenterWrapper verticalCenterWrapper">
                    <div id="divCenter" class="divCenter verticalCenterContainer">
                        <div id="divCenterText" class="divCenterText verticalCenter textCenter">
                            <ul class="ulCenterSlide">
                                <li>
                                    <img class="imgCenterImage" src="<?php echo $basePath; ?>/img/c1.png" alt=""/> <br>
                                    <span class="spnCenterText smallFont whiteFont">
                                        Collect 100 web links per category, 1000 per user, recognizing 18 types of files.
                                    </span>
                                </li>
                                <li>
                                    <img  class="imgCenterImage" src="<?php echo $basePath; ?>/img/c2.png" alt=""/> <br>
                                    <span class="spnCenterText smallFont whiteFont">Preparing awesome dashboard for you. Please wait...</span>
                                </li>
                                <li>
                                    <img  class="imgCenterImage" src="<?php echo $basePath; ?>/img/c3.png" alt=""/> <br>
                                    <span class="spnCenterText smallFont whiteFont">Preparing awesome dashboard for you. Please wait...</span>
                                </li>
                                <li>
                                    <img  class="imgCenterImage" src="<?php echo $basePath; ?>/img/c4.png" alt=""/> <br>
                                    <span class="spnCenterText smallFont whiteFont">Preparing awesome dashboard for you. Please wait...</span>
                                </li>
                                <li>
                                    <img  class="imgCenterImage" src="<?php echo $basePath; ?>/img/c5.png" alt=""/> <br>
                                    <span class="spnCenterText smallFont whiteFont">Preparing awesome dashboard for you. Please wait...</span>
                                </li>
                                <li>
                                    <img  class="imgCenterImage" src="<?php echo $basePath; ?>/img/c6.png" alt=""/> <br>
                                    <span class="spnCenterText smallFont whiteFont">Preparing awesome dashboard for you. Please wait...</span>
                                </li>
                                <li>
                                    <img  class="imgCenterImage" src="<?php echo $basePath; ?>/img/c7.png" alt=""/> <br>
                                    <span class="spnCenterText smallFont whiteFont">Preparing awesome dashboard for you. Please wait...</span>
                                </li>
                            </ul>

                        </div>
                    </div>
                </div>
            </section>

            <!--            Bottom Section-->
            <section id="secFooterAspects" class="bottomSticky">
                <div id="divFooterSentence" class="whiteFont">
                    <span class="fatFont">1500</span> <span class="smallFont">HOT LINKS, PERSONALIZED AND SHARED,</span> <span class="fatFont">49</span> <span class="smallFont">Users</span>
                </div>
            </section>
        </div>
    </body>
</html>
<script type="text/javascript" src="<?php echo $basePath; ?>/js/new_js/libs/jquery/jquery.js"></script>
<script type="text/javascript" src="<?php echo $basePath; ?>/js/new_js/custom.js"></script>
