<input type="hidden" id="loggedInStatus" <?php if( isset($_SESSION['usersinfo']) ) {?>value="loggedIn"<?php } ?> />
<input type="hidden" id="postClicked" value="0" />
<input type="hidden" id="nsfwMcClicked" value="0" />

<input type="hidden" id="socialLoginSecond" value="" />
<input type="hidden" id="homePageSection" value="1" />
<input type="hidden" id="checkGoogleLogin" />
<input type="hidden" id="checkGoogleLogin1" value="0" />

<input type="hidden" id="highlightBoxesPerPage" value="5" />
<input type="hidden" id="highlightBoxesOffset" value="0" />
<input type="hidden" id="publicBoxesPerPage" value="10" />
<input type="hidden" id="publicBoxesOffset" value="0" />
<input type="hidden" id="montageBoxesPerPage" value="10" />
<input type="hidden" id="montageBoxesOffset" value="0" />
<input type="hidden" id="publicBoxesOn" value="1" />
<input type="hidden" id="montageBoxesOn" value="1" />
<input type="hidden" id="filterBoxesOn" value="1" />
<input type="hidden" id="homepageSearched" value="0" />
<input type="hidden" id="pboxesOnBeforeSearch" value="0" />
<input type="hidden" id="publicBoxesfilterVal" value="0" />
<!-- New added for filter perpose -->
<input type="hidden" id="publicBoxesNewPerPage" value="10" />
<input type="hidden" id="publicBoxesNewOffset" value="0" />
<input type="hidden" id="publicBoxesTrendingPerPage" value="10" />
<input type="hidden" id="publicBoxesTrendingOffset" value="0" />
<input type="hidden" id="publicBoxesMyPostPerPage" value="10" />
<input type="hidden" id="publicBoxesMyPostOffset" value="0" />

<div class="clearfix"></div>

            <section id="secHighlights" class="secHighlights mainpage_firstdivbg tmar_t current_affairs">

                <div id="divCardsHeading" class="divHeadingLabel">
                    Highlights #Tagged by Members
                </div>

                <div id="divHighlightsMainWrapper" class="divCardsMainWrapper tmar_b20">
                    <div id="divNavLeftArrow" class="divNavLeftArrow"><img src="<?php echo $basePath; ?>/img/imgNavLeftArrow.png" alt="" /></div>

                    <div id="divCardsWrapper" class="divCardsWrapper" style="min-height:310px;">
						<?php if( isset($this->homehighlightBoxesArray) )
					{foreach( $this->homehighlightBoxesArray as $key=>$currentBoxData ){
						$viewUrl = "";
						if( isset($_SESSION['usersinfo']) )
						{
							if($currentBoxData['settingId']==3){
								$viewUrl = "post-vertical";
							}else{
								$viewUrl = "post-horizontal";
							}
						}
						else
						{
							if($currentBoxData['settingId']==3){
								$viewUrl = "pre-vertical";
							}else{
								$viewUrl = "pre-horizontal";
							}
						}
						$displayCustomizationUrl = $baseUrl;
						$catTitles = str_replace( "-","~",$currentBoxData["category_title"] );
						$catTitle = str_replace( " ","-",$catTitles );
						$catHashName = substr( $currentBoxData["user_hashname"],1 );
						$catImageUrl=explode(".",$currentBoxData["category_image"]);
						$catImageUrll=$catImageUrl[0];
						$displayCustomizationUrl .= "/databox/" . $viewUrl . "/" . $currentBoxData["category_id"] . "+" . $catImageUrll . "+" . $catHashName . "+" . $catTitle;?>
                        <div id="divCard-1" class="divCard" draggable="true">
													<a href="<?php echo $displayCustomizationUrl; ?>" onClick='Javascript:displayCustomization(<?php echo $currentBoxData["category_id"]; ?>,"<?php echo $currentBoxData["user_hashname"]; ?>","<?php echo $currentBoxData["category_title"]; ?>",<? echo $currentBoxData['settingId']?>,"<? echo $catImageUrll?>");'>
                            <div id="divCard-1-imageWrapper" class="divCardImageWrapper img_center">
                                <img id="Card-1-img" class="" src="<?php echo $basePath.'/images/project/categoryImages/'.$currentBoxData["category_image"]; ?>" alt="<?php echo $currentBoxData["user_hashname"]; ?>" />
                                <div id="divCard-1-hashtag" class="divCardHashtag hash_tag_color_r">
                                   <a href="<?php echo $displayCustomizationUrl; ?>"><h3 class="hashtagh2_size"><b><?php echo $currentBoxData["user_hashname"]; ?></b></h3></a>
                                </div>
                                <!--<div id="Card-1-user" class="divCardUser">
									<!--<img src="<?php echo $basePath; ?>/img/userImage.png" class="imgUserImage" alt="" />
                                    <div class="divCardUserName">By: Arun Kolhapur</div>-->
									<!--<div class="divCardUserName">By: <?php echo $currentBoxData["display_name"];?></div>
									<?php if($currentBoxData["montage_image"]!=""){?>
									<div class="pdatabox_profile">
										<img  src="<?php echo $basePath; ?>/images/project/montageImages/<?php echo $currentBoxData["montage_image"];?>" class="imgUserImage" alt="" />
									</div><br/>
									<?php } ?>
									<div id="likes<?php echo $currentBoxData["category_id"];?>" class="divCardUserName likes_percentage">
									<h2><?php echo round($currentBoxData["NetVotes"],2);?>% liked</h2></div>
                                </div>-->
                                <div id="divCard-1-sharedLinks" class="divCardSharedLinks">
                                    <span class="fatFont"><?php if($currentBoxData["user_classification"]!="") {  echo $currentBoxData["categoryLinksCount"];?> HOT LINKS </span><?php echo $currentBoxData["user_classification"]; }else{?><?php echo $currentBoxData["categoryLinksCount"]; ?> HOT LINKS</span> collected and shared
									<?php } ?>
                                </div>
								<div class="divCardLoveTrash<?php echo $currentBoxData["category_id"];?>" id="divCardLoveTrash<?php echo $currentBoxData["category_id"];?>">
									<div class="divbrg_f" onClick="return likeDislikeCnt('<?php echo $currentBoxData["category_id"];?>','1','1');"><?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?> <img src="<?php echo $basePath; ?>/img/love.png" alt="" width="15px"/></div>
									<div class="divbrg_s" onClick="return likeDislikeCnt('<?php echo $currentBoxData["category_id"];?>','0','1');"><?php if($currentBoxData["voteDown"]!=""){echo $currentBoxData["voteDown"];}else{ echo "0";}?> <a href="Javascript:void(0);" ><img src="<?php echo $basePath; ?>/img/trash.png" alt="" width="10px"/></a></div>
								</div>
                                  <input type="hidden" id="voting<?php echo $currentBoxData["category_id"];?>" name="voting<?php echo $currentBoxData["category_id"];?>" value="<?php if($currentBoxData["userVoteUp"]!=""){echo $currentBoxData["userVoteUp"];}else{ echo "3";}  ?>">
                               <div style="clear:both;"></div>
                            </div>
							</a>
                            <div id="divCard-1-contentWrapper" class="divCardContentWrapper">
                                <div id="divCard-1-views" class="" align="center">
                                    <img src="<?php echo $basePath; ?>/img/views.png" alt="" /> <?php if($currentBoxData["views_count"]!=""){echo $currentBoxData["views_count"]; }else { echo "0"; } ?> views 
                                </div>
								<!--<span><?php //echo round($currentBoxData["NetVotes"],2);?>% liked</span>-->
                                <!--<div id="divCardLoveTrash<?php echo $currentBoxData["category_id"];?>" class="divCardLoveTrash">
									<?php //if((isset($_SESSION['usersinfo']->userId )&& $currentBoxData["userVoteId"]==$_SESSION['usersinfo']->userId) || $currentBoxData["userVoteId"]==$_SERVER['REMOTE_ADDR']){
									//if($currentBoxData["userVoteUp"]=='1'){?>
									<img src="<?php //echo $basePath; ?>/img/love_ok.png" alt="" />  or <a href="Javascript:void(0);" onClick="return likeDislikeCnt('0','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"> <img src="<?php echo $basePath; ?>/img/trash.png" alt="" /></a>
									<?php
									//}else if($currentBoxData["uservoteDown"]=='1'){?>
									<a href="Javascript:void(0);" onClick="return likeDislikeCnt('1','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"><img src="<?php echo $basePath; ?>/img/love.png" alt="" /></a>  or <img src="<?php echo $basePath; ?>/img/love_ok.png" alt="" />
									<?php
									//}}else{
									?>
									<a href="Javascript:void(0);" onClick="return likeDislikeCnt('1','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"><img src="<?php echo $basePath; ?>/img/love.png" alt="" /></a>  or <a href="Javascript:void(0);" onClick="return likeDislikeCnt('0','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"> <img src="<?php echo $basePath; ?>/img/trash.png" alt="" /></a>
									<?php
									//}
								?>
                                  <input type="hidden" id="voting<?php echo $currentBoxData["category_id"];?>" name="voting<?php echo $currentBoxData["category_id"];?>" value="<?php if($currentBoxData["userVoteUp"]!=""){echo $currentBoxData["userVoteUp"];}else{ echo "3";}  ?>">
                               </div>-->
								<?php if($currentBoxData["category_title"]!=""){?>
								<div id="divCard-1-title" class="divCardTitle">
                                   <h2 class="home_title_d"><?php echo $currentBoxData["category_title"];?></h2>
                                </div>
								<?php } ?>
								<?php if($currentBoxData["meta_tags"]!=""){?>
                                <div id="divCardKeywords" class="divCardKeywords">
									<h3 class="home_keyword_h3"><b>Keywords: </b> <?php echo $currentBoxData["meta_tags"];?></h3>
								</div>
								<?php } ?>
								<?php if($currentBoxData["category_description"]!=""){?>
                                <div id="divCard-1-description" class="divCardDescription home_title_des_s home_heightlight_des_p">
                                    <?php if($currentBoxData["category_description"]!=""){
										if(strlen($currentBoxData["category_description"])>155)
										{
											echo substr($currentBoxData["category_description"],0,155) . '...';
										}
										else
										{
											echo $currentBoxData["category_description"];
										}
									}?>
                                </div>
								<?php } ?>
                            </div>
                        </div>
                        <?php } } ?>
                   
                    </div>

                    <div id="divNavRightArrow" class="divNavRightArrow"><img src="<?php echo $basePath; ?>/img/imgNavRightArrow.png" alt="" /></div>
                </div>
					<div class="clearfix"></div>
            </section>
			<div class="clearfix"></div>
			<div class="tmar_t20 pad_lr">
            <section id="secDataboxes" class="secDataboxes">
                <div id="divDataboxesHeading" class="divHeadingLabel">
                   <a href="Javascript:void(0);" id="publicBoxesLink"><b>Public Databoxes</b></a> (<a href="Javascript:void(0);" id="publicBoxesLinkForNew">New</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="Javascript:void(0);" id="publicBoxesLinkForTrending">Trending</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="Javascript:void(0);" id="publicBoxesLinkForAll">All</a><?php if( isset($_SESSION['usersinfo']) ) {?>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="Javascript:void(0);" id="publicBoxesLinkForMyPosts">My Posts</a><?php } ?><?php if( isset($_SESSION['usersinfo']) ) {?><a href="Javascript:void(0);" id="memCollectionsLink">) &nbsp;&nbsp;|&nbsp;&nbsp; <b>Members</b></a><?php }else{ echo ')';} ?>
                </div>
				<div id="list_public_boxes" >
                <div id="divDataboxWrapper" class="divCardsWrapper" data-columns>
					<?php
						if( isset($this->homePublicBoxesArray) )
						{
						if(count($this->homePublicBoxesArray)!="0"){
								
							foreach( $this->homePublicBoxesArray as $key=>$currentBoxData )
							{
								$showMcNsfwPopup = false;
								if( (! isset($_SESSION['usersinfo'])) && (($currentBoxData["mature_content"] == 1) || ($currentBoxData["not_safe_for_work"] == 1)) )
								{
									$showMcNsfwPopup = true;
								}
								
								$viewUrl = "";
								if( isset($_SESSION['usersinfo']) )
								{
									if($currentBoxData['settingId']==3){
										$viewUrl = "post-vertical";
									}else{
										$viewUrl = "post-horizontal";
									}
								}
								else
								{
									if($currentBoxData['settingId']==3){
										$viewUrl = "pre-vertical";
									}else{
										$viewUrl = "pre-horizontal";
									}
								}
								$displayCustomizationUrl = $baseUrl;
								$catTitles = str_replace( "-","~",$currentBoxData["category_title"] );
								$catTitle = str_replace( " ","-",$catTitles );
								$catHashName = substr( $currentBoxData["user_hashname"],1 );
								$catImageUrl=explode(".",$currentBoxData["category_image"]);
								$userImageUrl=$currentBoxData["image"];
								$catImageUrll=$catImageUrl[0];
								$displayCustomizationUrl .= "/databox/" . $viewUrl . "/" . $currentBoxData["category_id"] . "+" . $catImageUrll . "+" . $catHashName . "+" . $catTitle;?>
								
				    <div id="divDatabox-1" class="divCard" draggable="true">
                        <div id="divDatabox-1-imageWrapper" class="divCardImageWrapper img_center">
							<?php if( $showMcNsfwPopup ){  ?><a href="javascript:void(0)" onClick='Javascript:displayNsfwMc(<?php echo $currentBoxData["category_id"]; ?>,"<?php echo $currentBoxData["user_hashname"]?>","<?php echo $currentBoxData["category_title"]; ?>",<? echo $currentBoxData["settingId"]?>,"<? echo $catImageUrll?>");'><img src="<?php echo $basePath; ?>/images/social_media/mature_content.jpg"  /></a>
							<?php } else { ?>
                            <a href="<?php echo $displayCustomizationUrl; ?>"><img id="Databox-1-img" class="" alt="<?php echo $currentBoxData["user_hashname"]; ?>" src="<?php echo $basePath.'/images/project/categoryImages/'.$currentBoxData["category_image"]; ?>"/></a>
							<?php } ?>
                            <div id="divDatabox-1-hashtag" class="divCardHashtag hash_tag_color">
                              <a href="<?php echo $displayCustomizationUrl; ?>"><h3 class="hashtagh2_size"><b><?php echo $currentBoxData["user_hashname"];?></b></h3></a>
                            </div>

                            <div id="divDatabox-1-sharedLinks" class="divCardSharedLinks">
                                <span class="fatFont"><?php if($currentBoxData["user_classification"]!="") { echo $currentBoxData["categoryLinksCount"];?> HOT LINKS </span><?php echo $currentBoxData["user_classification"];  }else{ ?><?php echo $currentBoxData["categoryLinksCount"]; ?> HOT LINKS</span> collected and shared
								<?php } ?>
                            </div>
                           <!-- <div id="Card-1-user" class="divCardUser">
							<div class="divCardUserName">By: <?php echo $currentBoxData["display_name"];?></div>
								<?php if($currentBoxData["montage_image"]!=""){?>
                               <div class="pdatabox_profile">
								<img  src="<?php echo $basePath; ?>/images/project/montageImages/<?php echo $currentBoxData["montage_image"];?>" class="imgUserImage" alt="" />
							   </div><br/>
								<?php } ?>
								<div id="likes<?php echo $currentBoxData["category_id"];?>" class="divCardUserName likes_percentage"><h2><?php echo round($currentBoxData["likes"],2);?>% liked</h2></div>
                            </div>-->
							<div class="divCardLoveTrash<?php echo $currentBoxData["category_id"];?>" id="divCardLoveTrash<?php echo $currentBoxData["category_id"];?>">
								<div class="divbrg_f" onClick="return likeDislikeCnt('<?php echo $currentBoxData["category_id"];?>','1','1');"><?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?> <img src="<?php echo $basePath; ?>/img/love.png" alt="" width="15px"/></div>
								<div class="divbrg_s" onClick="return likeDislikeCnt('<?php echo $currentBoxData["category_id"];?>','0','1');"><?php if($currentBoxData["voteDown"]!=""){echo $currentBoxData["voteDown"];}else{ echo "0";}?> <a href="Javascript:void(0);" ><img src="<?php echo $basePath; ?>/img/trash.png" alt="" width="10px"/></a></div>
								<input type="hidden" id="voting<?php echo $currentBoxData["category_id"];?>" name="voting<?php echo $currentBoxData["category_id"];?>" value="<?php if($currentBoxData["userVoteUp"]!=""){echo $currentBoxData["userVoteUp"];}else{ echo "3";}  ?>">
								</div>
							<div style="clear:both;"></div>
                        </div>
                        <div id="divDatabox-1-contentWrapper" class="divCardContentWrapper">
						<div>
                            <div id="divDatabox-1-views" class="" align="center">
                                <img src="<?php echo $basePath; ?>/img/views.png" alt="" /> <?php if($currentBoxData["views_count"]!=""){echo $currentBoxData["views_count"]; }else { echo "0"; } ?> views
                            </div>
							<!--<span><?php echo round($currentBoxData["likes"],2);?>% liked</span>-->
                            <!--<div id="divCardLoveTrash<?php echo $currentBoxData["category_id"];?>" class="divCardLoveTrash love_trash_color">
								<?php //if((isset($_SESSION['usersinfo']->userId )&& $currentBoxData["userVoteId"]==$_SESSION['usersinfo']->userId) || $currentBoxData["userVoteId"]==$_SERVER['REMOTE_ADDR']){
									//if($currentBoxData["userVoteUp"]=='1'){?>
									<img src="<?php echo $basePath; ?>/img/love_ok.png" alt="" />  or  <a href="Javascript:void(0);" onClick="return likeDislikeCnt('0','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"><img src="<?php echo $basePath; ?>/img/trash.png" alt="" /></a>
									<?php
									//}else if($currentBoxData["uservoteDown"]=='1'){?>
									<a href="Javascript:void(0);" onClick="return likeDislikeCnt('1','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"><img src="<?php echo $basePath; ?>/img/love.png" alt="" /></a>  or  <img src="<?php echo $basePath; ?>/img/love_ok.png" alt="" />
									<?php
									//}}else{
									?>
									<a href="Javascript:void(0);" onClick="return likeDislikeCnt('1','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"><img src="<?php echo $basePath; ?>/img/love.png" alt="" /></a>  or  <a href="Javascript:void(0);" onClick="return likeDislikeCnt('0','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"><img src="<?php echo $basePath; ?>/img/trash.png" alt="" /></a>
									<?php
									//}
								?>
                            <input type="hidden" id="voting<?php echo $currentBoxData["category_id"];?>" name="voting<?php echo $currentBoxData["category_id"];?>" value="<?php if($currentBoxData["userVoteUp"]!=""){echo $currentBoxData["userVoteUp"];}else{ echo "3";}  ?>">

							</div>-->
                        </div>
							<?php if($currentBoxData["category_title"]!=""){?>
                            <div id="divDatabox-1-title" class="divCardTitle">
                                <h2 class="home_title_d"><?php echo $currentBoxData["category_title"];?></h2>
                            </div>
							<?php } ?>
							<?php if($currentBoxData["meta_tags"]!=""){?>
							 <div id="divCardKeywords" class="divCardKeywords">
								<h3 class="home_keyword_h3"><b>Keywords: </b><?php echo $currentBoxData["meta_tags"];?></h3>
							 </div>
							 <?php } ?>
							 <?php if($currentBoxData["category_description"]!=""){?>
                            <div id="divDatabox-1-description" class="divCardDescription home_de_brg_t home_title_des_s">
							<?php if($currentBoxData["category_description"]!=""){
								if(strlen($currentBoxData["category_description"])>155)
								{
									echo substr($currentBoxData["category_description"],0,155) . '...';
								}
								else
								{
									echo $currentBoxData["category_description"];
								}
							}?>
                            </div>
							<?php } ?>
                        </div>
                    </div>
						<?php } }else { echo '<div>Not Found</div>';}}?>
                </div>
				<div id="publicBoxesLoadingDiv" style="position:relative;display:none;" >
				<!--<div class="home_publicboxes_loading" >
					<center><img src="<?php echo $basePath; ?>/images/social_media/bx_loader.gif" /></center>
				</div>-->
			</div>
              </div>
				<!-- newly added for filtering -->
			<div id="list_public_boxesForNew" style="display:none;">
                <div id="divDataboxWrapper" class="divCardsWrapper" data-columns>
					<?php
						if( isset($this->homePublicBoxesNewArray) )
						{
							if(count($this->homePublicBoxesNewArray)!="0"){
								
							foreach( $this->homePublicBoxesNewArray as $key=>$currentBoxData )
							{
								$showMcNsfwPopup = false;
								if( (! isset($_SESSION['usersinfo'])) && (($currentBoxData["mature_content"] == 1) || ($currentBoxData["not_safe_for_work"] == 1)) )
								{
									$showMcNsfwPopup = true;
								}
								
								$viewUrl = "";
								if( isset($_SESSION['usersinfo']) )
								{
									if($currentBoxData['settingId']==3){
										$viewUrl = "post-vertical";
									}else{
										$viewUrl = "post-horizontal";
									}
								}
								else
								{
									if($currentBoxData['settingId']==3){
										$viewUrl = "pre-vertical";
									}else{
										$viewUrl = "pre-horizontal";
									}
								}
								$displayCustomizationUrl = $baseUrl;
								$catTitles = str_replace( "-","~",$currentBoxData["category_title"] );
								$catTitle = str_replace( " ","-",$catTitles );
								$catHashName = substr( $currentBoxData["user_hashname"],1 );
								$catImageUrl=explode(".",$currentBoxData["category_image"]);
								$userImageUrl=$currentBoxData["image"];
								$catImageUrll=$catImageUrl[0];
								$displayCustomizationUrl .= "/databox/" . $viewUrl . "/" . $currentBoxData["category_id"] . "+" . $catImageUrll . "+" . $catHashName . "+" . $catTitle;?>
								
				    <div id="divDatabox-1" class="divCard" draggable="true">
                        <div id="divDatabox-1-imageWrapper" class="divCardImageWrapper img_center">
							<?php if( $showMcNsfwPopup ){  ?><a href="javascript:void(0)" onClick='Javascript:displayNsfwMc(<?php echo $currentBoxData["category_id"]; ?>,"<?php echo $currentBoxData["user_hashname"]?>","<?php echo $currentBoxData["category_title"]; ?>",<? echo $currentBoxData["settingId"]?>,"<? echo $catImageUrll?>");'><img src="<?php echo $basePath; ?>/images/social_media/mature_content.jpg"  /></a>
							<?php } else { ?>
                            <a href="<?php echo $displayCustomizationUrl; ?>"><img id="Databox-1-img" class="" alt="<?php echo $currentBoxData["user_hashname"]; ?>" src="<?php echo $basePath.'/images/project/categoryImages/'.$currentBoxData["category_image"]; ?>"/></a>
							<?php } ?>
                            <div id="divDatabox-1-hashtag" class="divCardHashtag hash_tag_color">
                              <a href="<?php echo $displayCustomizationUrl; ?>"><h3 class="hashtagh2_size"><b><?php echo $currentBoxData["user_hashname"];?></b></h3></a>
                            </div>

                            <div id="divDatabox-1-sharedLinks" class="divCardSharedLinks">
                                <span class="fatFont"><?php if($currentBoxData["user_classification"]!="") { echo $currentBoxData["categoryLinksCount"];?> HOT LINKS </span><?php echo $currentBoxData["user_classification"];  }else{ ?><?php echo $currentBoxData["categoryLinksCount"]; ?> HOT LINKS</span> collected and shared<?php } ?>
                            </div>
                           <!-- <div id="Card-1-user" class="divCardUser">
							<div class="divCardUserName">By: <?php echo $currentBoxData["display_name"];?></div>
								<?php if($currentBoxData["montage_image"]!=""){?>
                               <div class="pdatabox_profile">
								<img  src="<?php echo $basePath; ?>/images/project/montageImages/<?php echo $currentBoxData["montage_image"];?>" class="imgUserImage" alt="" />
							   </div><br/>
								<?php } ?>
								<div id="likes<?php echo $currentBoxData["category_id"];?>" class="divCardUserName likes_percentage"><h2><?php echo round($currentBoxData["likes"],2);?>% liked</h2></div>
                            </div>-->
							<div class="divCardLoveTrash<?php echo $currentBoxData["category_id"];?>" id="divCardLoveTrash<?php echo $currentBoxData["category_id"];?>">
								<div class="divbrg_f" onClick="return likeDislikeCnt('<?php echo $currentBoxData["category_id"];?>','1','1');"><?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?> <img src="<?php echo $basePath; ?>/img/love.png" alt="" width="15px"/></div>
								<div class="divbrg_s" onClick="return likeDislikeCnt('<?php echo $currentBoxData["category_id"];?>','0','1');"><?php if($currentBoxData["voteDown"]!=""){echo $currentBoxData["voteDown"];}else{ echo "0";}?> <a href="Javascript:void(0);" ><img src="<?php echo $basePath; ?>/img/trash.png" alt="" width="10px"/></a></div>
								<input type="hidden" id="voting<?php echo $currentBoxData["category_id"];?>" name="voting<?php echo $currentBoxData["category_id"];?>" value="<?php if($currentBoxData["userVoteUp"]!=""){echo $currentBoxData["userVoteUp"];}else{ echo "3";}  ?>">

								</div>
							<div style="clear:both;"></div>
                        </div>
                        <div id="divDatabox-1-contentWrapper" class="divCardContentWrapper">
						<div>
                            <div id="divDatabox-1-views" class="" align="center">
                                <img src="<?php echo $basePath; ?>/img/views.png" alt="" /> <?php if($currentBoxData["views_count"]!=""){echo $currentBoxData["views_count"]; }else { echo "0"; } ?> views
                            </div>
							<!--<span><?php echo round($currentBoxData["likes"],2);?>% liked</span>-->
                            <!--<div id="divCardLoveTrash<?php echo $currentBoxData["category_id"];?>" class="divCardLoveTrash love_trash_color">
								<?php //if((isset($_SESSION['usersinfo']->userId )&& $currentBoxData["userVoteId"]==$_SESSION['usersinfo']->userId) || $currentBoxData["userVoteId"]==$_SERVER['REMOTE_ADDR']){
									//if($currentBoxData["userVoteUp"]=='1'){?>
									<img src="<?php echo $basePath; ?>/img/love_ok.png" alt="" />  or  <a href="Javascript:void(0);" onClick="return likeDislikeCnt('0','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"><img src="<?php echo $basePath; ?>/img/trash.png" alt="" /></a>
									<?php
									//}else if($currentBoxData["uservoteDown"]=='1'){?>
									<a href="Javascript:void(0);" onClick="return likeDislikeCnt('1','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"><img src="<?php echo $basePath; ?>/img/love.png" alt="" /></a>  or  <img src="<?php echo $basePath; ?>/img/love_ok.png" alt="" />
									<?php
									//}}else{
									?>
									<a href="Javascript:void(0);" onClick="return likeDislikeCnt('1','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"><img src="<?php echo $basePath; ?>/img/love.png" alt="" /></a>  or  <a href="Javascript:void(0);" onClick="return likeDislikeCnt('0','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"><img src="<?php echo $basePath; ?>/img/trash.png" alt="" /></a>
									<?php
									//}
								?>
                            <input type="hidden" id="voting<?php echo $currentBoxData["category_id"];?>" name="voting<?php echo $currentBoxData["category_id"];?>" value="<?php if($currentBoxData["userVoteUp"]!=""){echo $currentBoxData["userVoteUp"];}else{ echo "3";}  ?>">

							</div>-->
                        </div>
							<?php if($currentBoxData["category_title"]!=""){?>
                            <div id="divDatabox-1-title" class="divCardTitle">
                                <h2 class="home_title_d"><?php echo $currentBoxData["category_title"];?></h2>
                            </div>
							<?php } ?>
							<?php if($currentBoxData["meta_tags"]!=""){?>
							 <div id="divCardKeywords" class="divCardKeywords">
								<h3 class="home_keyword_h3"><b>Keywords: </b><?php echo $currentBoxData["meta_tags"];?></h3>
							 </div>
							 <?php } ?>
							 <?php if($currentBoxData["category_description"]!=""){?>
                            <div id="divDatabox-1-description" class="divCardDescription home_de_brg_t home_title_des_s">
							<?php if($currentBoxData["category_description"]!=""){
								if(strlen($currentBoxData["category_description"])>155)
								{
									echo substr($currentBoxData["category_description"],0,155) . '...';
								}
								else
								{
									echo $currentBoxData["category_description"];
								}
							}?>
                            </div>
							<?php } ?>
                        </div>
                    </div>
						<?php } }else{ echo '<div>NOT FOUND THE NEW POSTS</div>';}}?>
                </div>
				<div id="publicBoxesLoadingDiv" style="position:relative;display:none;" >
			</div>
              </div>	
			  <div id="list_public_boxesForTrending" style="display:none;">
                <div id="divDataboxWrapper" class="divCardsWrapper" data-columns>
					<?php
						if( isset($this->homePublicBoxesTrendingArray) )
						{
						if(count($this->homePublicBoxesTrendingArray)!="0"){

							foreach( $this->homePublicBoxesTrendingArray as $key=>$currentBoxData )
							{
								$showMcNsfwPopup = false;
								if( (! isset($_SESSION['usersinfo'])) && (($currentBoxData["mature_content"] == 1) || ($currentBoxData["not_safe_for_work"] == 1)) )
								{
									$showMcNsfwPopup = true;
								}
								
								$viewUrl = "";
								if( isset($_SESSION['usersinfo']) )
								{
									if($currentBoxData['settingId']==3){
										$viewUrl = "post-vertical";
									}else{
										$viewUrl = "post-horizontal";
									}
								}
								else
								{
									if($currentBoxData['settingId']==3){
										$viewUrl = "pre-vertical";
									}else{
										$viewUrl = "pre-horizontal";
									}
								}
								$displayCustomizationUrl = $baseUrl;
								$catTitles = str_replace( "-","~",$currentBoxData["category_title"] );
								$catTitle = str_replace( " ","-",$catTitles );
								$catHashName = substr( $currentBoxData["user_hashname"],1 );
								$catImageUrl=explode(".",$currentBoxData["category_image"]);
								$userImageUrl=$currentBoxData["image"];
								$catImageUrll=$catImageUrl[0];
								$displayCustomizationUrl .= "/databox/" . $viewUrl . "/" . $currentBoxData["category_id"] . "+" . $catImageUrll . "+" . $catHashName . "+" . $catTitle;?>
								
				    <div id="divDatabox-1" class="divCard" draggable="true">
                        <div id="divDatabox-1-imageWrapper" class="divCardImageWrapper img_center">
							<?php if( $showMcNsfwPopup ){  ?><a href="javascript:void(0)" onClick='Javascript:displayNsfwMc(<?php echo $currentBoxData["category_id"]; ?>,"<?php echo $currentBoxData["user_hashname"]?>","<?php echo $currentBoxData["category_title"]; ?>",<? echo $currentBoxData["settingId"]?>,"<? echo $catImageUrll?>");'><img src="<?php echo $basePath; ?>/images/social_media/mature_content.jpg"  /></a>
							<?php } else { ?>
                            <a href="<?php echo $displayCustomizationUrl; ?>"><img id="Databox-1-img" class="" alt="<?php echo $currentBoxData["user_hashname"]; ?>" src="<?php echo $basePath.'/images/project/categoryImages/'.$currentBoxData["category_image"]; ?>"/></a>
							<?php } ?>
                            <div id="divDatabox-1-hashtag" class="divCardHashtag hash_tag_color">
                              <a href="<?php echo $displayCustomizationUrl; ?>"><h3 class="hashtagh2_size"><b><?php echo $currentBoxData["user_hashname"];?></b></h3></a>
                            </div>

                            <div id="divDatabox-1-sharedLinks" class="divCardSharedLinks">
                                <span class="fatFont"><?php if($currentBoxData["user_classification"]!="") { echo $currentBoxData["categoryLinksCount"];?> HOT LINKS </span><?php echo $currentBoxData["user_classification"];  }else{ ?><?php echo $currentBoxData["categoryLinksCount"]; ?> HOT LINKS</span> collected and shared<?php } ?>
                            </div>
                           <!-- <div id="Card-1-user" class="divCardUser">
							<div class="divCardUserName">By: <?php echo $currentBoxData["display_name"];?></div>
								<?php if($currentBoxData["montage_image"]!=""){?>
                               <div class="pdatabox_profile">
								<img  src="<?php echo $basePath; ?>/images/project/montageImages/<?php echo $currentBoxData["montage_image"];?>" class="imgUserImage" alt="" />
							   </div><br/>
								<?php } ?>
								<div id="likes<?php echo $currentBoxData["category_id"];?>" class="divCardUserName likes_percentage"><h2><?php echo round($currentBoxData["likes"],2);?>% liked</h2></div>
                            </div>-->
							<div class="divCardLoveTrash<?php echo $currentBoxData["category_id"];?>" id="divCardLoveTrash<?php echo $currentBoxData["category_id"];?>">
								<div class="divbrg_f" onClick="return likeDislikeCnt('<?php echo $currentBoxData["category_id"];?>','1','1');"><?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?> <img src="<?php echo $basePath; ?>/img/love.png" alt="" width="15px"/></div>
								<div class="divbrg_s" onClick="return likeDislikeCnt('<?php echo $currentBoxData["category_id"];?>','0','1');"><?php if($currentBoxData["voteDown"]!=""){echo $currentBoxData["voteDown"];}else{ echo "0";}?> <a href="Javascript:void(0);" ><img src="<?php echo $basePath; ?>/img/trash.png" alt="" width="10px"/></a></div>
								<input type="hidden" id="voting<?php echo $currentBoxData["category_id"];?>" name="voting<?php echo $currentBoxData["category_id"];?>" value="<?php if($currentBoxData["userVoteUp"]!=""){echo $currentBoxData["userVoteUp"];}else{ echo "3";}  ?>">

								</div>
							<div style="clear:both;"></div>
                        </div>
                        <div id="divDatabox-1-contentWrapper" class="divCardContentWrapper">
						<div>
                            <div id="divDatabox-1-views" class="" align="center">
                                <img src="<?php echo $basePath; ?>/img/views.png" alt="" /> <?php if($currentBoxData["views_count"]!=""){echo $currentBoxData["views_count"]; }else { echo "0"; } ?> views
                            </div>
							<!--<span><?php echo round($currentBoxData["likes"],2);?>% liked</span>-->
                            <!--<div id="divCardLoveTrash<?php echo $currentBoxData["category_id"];?>" class="divCardLoveTrash love_trash_color">
								<?php //if((isset($_SESSION['usersinfo']->userId )&& $currentBoxData["userVoteId"]==$_SESSION['usersinfo']->userId) || $currentBoxData["userVoteId"]==$_SERVER['REMOTE_ADDR']){
									//if($currentBoxData["userVoteUp"]=='1'){?>
									<img src="<?php echo $basePath; ?>/img/love_ok.png" alt="" />  or  <a href="Javascript:void(0);" onClick="return likeDislikeCnt('0','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"><img src="<?php echo $basePath; ?>/img/trash.png" alt="" /></a>
									<?php
									//}else if($currentBoxData["uservoteDown"]=='1'){?>
									<a href="Javascript:void(0);" onClick="return likeDislikeCnt('1','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"><img src="<?php echo $basePath; ?>/img/love.png" alt="" /></a>  or  <img src="<?php echo $basePath; ?>/img/love_ok.png" alt="" />
									<?php
									//}}else{
									?>
									<a href="Javascript:void(0);" onClick="return likeDislikeCnt('1','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"><img src="<?php echo $basePath; ?>/img/love.png" alt="" /></a>  or  <a href="Javascript:void(0);" onClick="return likeDislikeCnt('0','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"><img src="<?php echo $basePath; ?>/img/trash.png" alt="" /></a>
									<?php
									//}
								?>
                            <input type="hidden" id="voting<?php echo $currentBoxData["category_id"];?>" name="voting<?php echo $currentBoxData["category_id"];?>" value="<?php if($currentBoxData["userVoteUp"]!=""){echo $currentBoxData["userVoteUp"];}else{ echo "3";}  ?>">

							</div>-->
                        </div>
							<?php if($currentBoxData["category_title"]!=""){?>
                            <div id="divDatabox-1-title" class="divCardTitle">
                                <h2 class="home_title_d"><?php echo $currentBoxData["category_title"];?></h2>
                            </div>
							<?php } ?>
							<?php if($currentBoxData["meta_tags"]!=""){?>
							 <div id="divCardKeywords" class="divCardKeywords">
								<h3 class="home_keyword_h3"><b>Keywords: </b><?php echo $currentBoxData["meta_tags"];?></h3>
							 </div>
							 <?php } ?>
							 <?php if($currentBoxData["category_description"]!=""){?>
                            <div id="divDatabox-1-description" class="divCardDescription home_de_brg_t home_title_des_s">
							<?php if($currentBoxData["category_description"]!=""){
								if(strlen($currentBoxData["category_description"])>155)
								{
									echo substr($currentBoxData["category_description"],0,155) . '...';
								}
								else
								{
									echo $currentBoxData["category_description"];
								}
							}?>
                            </div>
							<?php } ?>
                        </div>
                    </div>
						<?php } }else{ echo '<div>NOT FOUND THE TRENDING POSTS</div>';}}?>
                </div>
				<div id="publicBoxesLoadingDiv" style="position:relative;display:none;" >
			</div>
            </div>		
			<div id="list_public_boxesForMyPosts" style="display:none;">
                <div id="divDataboxWrapper" class="divCardsWrapper" data-columns>
					<?php
						if( isset($this->homePublicBoxesMyPostsArray) )
						{
							if(count($this->homePublicBoxesMyPostsArray)!="0"){

							foreach( $this->homePublicBoxesMyPostsArray as $key=>$currentBoxData )
							{
								$showMcNsfwPopup = false;
								if( (! isset($_SESSION['usersinfo'])) && (($currentBoxData["mature_content"] == 1) || ($currentBoxData["not_safe_for_work"] == 1)) )
								{
									$showMcNsfwPopup = true;
								}
								
								$viewUrl = "";
								if( isset($_SESSION['usersinfo']) )
								{
									if($currentBoxData['settingId']==3){
										$viewUrl = "post-vertical";
									}else{
										$viewUrl = "post-horizontal";
									}
								}
								else
								{
									if($currentBoxData['settingId']==3){
										$viewUrl = "pre-vertical";
									}else{
										$viewUrl = "pre-horizontal";
									}
								}
								$displayCustomizationUrl = $baseUrl;
								$catTitles = str_replace( "-","~",$currentBoxData["category_title"] );
								$catTitle = str_replace( " ","-",$catTitles );
								$catHashName = substr( $currentBoxData["user_hashname"],1 );
								$catImageUrl=explode(".",$currentBoxData["category_image"]);
								$userImageUrl=$currentBoxData["image"];
								$catImageUrll=$catImageUrl[0];
								$displayCustomizationUrl .= "/databox/" . $viewUrl . "/" . $currentBoxData["category_id"] . "+" . $catImageUrll . "+" . $catHashName . "+" . $catTitle;?>
								
				    <div id="divDatabox-1" class="divCard" draggable="true">
                        <div id="divDatabox-1-imageWrapper" class="divCardImageWrapper img_center">
							<?php if( $showMcNsfwPopup ){  ?><a href="javascript:void(0)" onClick='Javascript:displayNsfwMc(<?php echo $currentBoxData["category_id"]; ?>,"<?php echo $currentBoxData["user_hashname"]?>","<?php echo $currentBoxData["category_title"]; ?>",<? echo $currentBoxData["settingId"]?>,"<? echo $catImageUrll?>");'><img src="<?php echo $basePath; ?>/images/social_media/mature_content.jpg"  /></a>
							<?php } else { ?>
                            <a href="<?php echo $displayCustomizationUrl; ?>"><img id="Databox-1-img" class="" alt="<?php echo $currentBoxData["user_hashname"]; ?>" src="<?php echo $basePath.'/images/project/categoryImages/'.$currentBoxData["category_image"]; ?>"/></a>
							<?php } ?>
                            <div id="divDatabox-1-hashtag" class="divCardHashtag hash_tag_color">
                              <a href="<?php echo $displayCustomizationUrl; ?>"><h3 class="hashtagh2_size"><b><?php echo $currentBoxData["user_hashname"];?></b></h3></a>
                            </div>

                            <div id="divDatabox-1-sharedLinks" class="divCardSharedLinks">
                                <span class="fatFont"><?php if($currentBoxData["user_classification"]!="") { echo $currentBoxData["categoryLinksCount"];?> HOT LINKS </span><?php echo $currentBoxData["user_classification"];  }else{ ?><?php echo $currentBoxData["categoryLinksCount"]; ?> HOT LINKS</span> collected and shared<?php } ?>
                            </div>
                           <!-- <div id="Card-1-user" class="divCardUser">
							<div class="divCardUserName">By: <?php echo $currentBoxData["display_name"];?></div>
								<?php if($currentBoxData["montage_image"]!=""){?>
                               <div class="pdatabox_profile">
								<img  src="<?php echo $basePath; ?>/images/project/montageImages/<?php echo $currentBoxData["montage_image"];?>" class="imgUserImage" alt="" />
							   </div><br/>
								<?php } ?>
								<div id="likes<?php echo $currentBoxData["category_id"];?>" class="divCardUserName likes_percentage"><h2><?php echo round($currentBoxData["likes"],2);?>% liked</h2></div>
                            </div>-->
							<div class="divCardLoveTrash<?php echo $currentBoxData["category_id"];?>" id="divCardLoveTrash<?php echo $currentBoxData["category_id"];?>">
								<div class="divbrg_f" onClick="return likeDislikeCnt('<?php echo $currentBoxData["category_id"];?>','1','1');"><?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?> <img src="<?php echo $basePath; ?>/img/love.png" alt="" width="15px"/></div>
								<div class="divbrg_s" onClick="return likeDislikeCnt('<?php echo $currentBoxData["category_id"];?>','0','1');"><?php if($currentBoxData["voteDown"]!=""){echo $currentBoxData["voteDown"];}else{ echo "0";}?> <a href="Javascript:void(0);" ><img src="<?php echo $basePath; ?>/img/trash.png" alt="" width="10px"/></a></div>
								<input type="hidden" id="voting<?php echo $currentBoxData["category_id"];?>" name="voting<?php echo $currentBoxData["category_id"];?>" value="<?php if($currentBoxData["userVoteUp"]!=""){echo $currentBoxData["userVoteUp"];}else{ echo "3";}  ?>">

								</div>
							<div style="clear:both;"></div>
                        </div>
                        <div id="divDatabox-1-contentWrapper" class="divCardContentWrapper">
						<div>
                            <div id="divDatabox-1-views" class="" align="center">
                                <img src="<?php echo $basePath; ?>/img/views.png" alt="" /> <?php if($currentBoxData["views_count"]!=""){echo $currentBoxData["views_count"]; }else { echo "0"; } ?> views
                            </div>
							<!--<span><?php echo round($currentBoxData["likes"],2);?>% liked</span>-->
                            <!--<div id="divCardLoveTrash<?php echo $currentBoxData["category_id"];?>" class="divCardLoveTrash love_trash_color">
								<?php //if((isset($_SESSION['usersinfo']->userId )&& $currentBoxData["userVoteId"]==$_SESSION['usersinfo']->userId) || $currentBoxData["userVoteId"]==$_SERVER['REMOTE_ADDR']){
									//if($currentBoxData["userVoteUp"]=='1'){?>
									<img src="<?php echo $basePath; ?>/img/love_ok.png" alt="" />  or  <a href="Javascript:void(0);" onClick="return likeDislikeCnt('0','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"><img src="<?php echo $basePath; ?>/img/trash.png" alt="" /></a>
									<?php
									//}else if($currentBoxData["uservoteDown"]=='1'){?>
									<a href="Javascript:void(0);" onClick="return likeDislikeCnt('1','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"><img src="<?php echo $basePath; ?>/img/love.png" alt="" /></a>  or  <img src="<?php echo $basePath; ?>/img/love_ok.png" alt="" />
									<?php
									//}}else{
									?>
									<a href="Javascript:void(0);" onClick="return likeDislikeCnt('1','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"><img src="<?php echo $basePath; ?>/img/love.png" alt="" /></a>  or  <a href="Javascript:void(0);" onClick="return likeDislikeCnt('0','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"><img src="<?php echo $basePath; ?>/img/trash.png" alt="" /></a>
									<?php
									//}
								?>
                            <input type="hidden" id="voting<?php echo $currentBoxData["category_id"];?>" name="voting<?php echo $currentBoxData["category_id"];?>" value="<?php if($currentBoxData["userVoteUp"]!=""){echo $currentBoxData["userVoteUp"];}else{ echo "3";}  ?>">

							</div>-->
                        </div>
							<?php if($currentBoxData["category_title"]!=""){?>
                            <div id="divDatabox-1-title" class="divCardTitle">
                                <h2 class="home_title_d"><?php echo $currentBoxData["category_title"];?></h2>
                            </div>
							<?php } ?>
							<?php if($currentBoxData["meta_tags"]!=""){?>
							 <div id="divCardKeywords" class="divCardKeywords">
								<h3 class="home_keyword_h3"><b>Keywords: </b><?php echo $currentBoxData["meta_tags"];?></h3>
							 </div>
							 <?php } ?>
							 <?php if($currentBoxData["category_description"]!=""){?>
                            <div id="divDatabox-1-description" class="divCardDescription home_de_brg_t home_title_des_s">
							<?php if($currentBoxData["category_description"]!=""){
								if(strlen($currentBoxData["category_description"])>155)
								{
									echo substr($currentBoxData["category_description"],0,155) . '...';
								}
								else
								{
									echo $currentBoxData["category_description"];
								}
							}?>
                            </div>
							<?php } ?>
                        </div>
                    </div>
						<?php } }else{ echo '<div>NOT FOUND THE MY POSTS</div>';}}?>
                </div>
				<div id="publicBoxesLoadingDiv" style="position:relative;display:none;" >
			</div>
              </div>  
				<!-- End newly added for filtering -->
				
				<div id="publicBoxesDiv" style="display:none;">
				 <div id="divDataboxWrapper" class="divCardsWrapper" data-columns>
					<?php
						if( isset($this->homePublicBoxesArray) )
						{
						if(count($this->homePublicBoxesArray)!="0"){

							foreach( $this->homePublicBoxesArray as $key=>$currentBoxData )
							{
								$showMcNsfwPopup = false;
								if( (! isset($_SESSION['usersinfo'])) && (($currentBoxData["mature_content"] == 1) || ($currentBoxData["not_safe_for_work"] == 1)) )
								{
									$showMcNsfwPopup = true;
								}
								
								$viewUrl = "";
								if( isset($_SESSION['usersinfo']) )
								{
									if($currentBoxData['settingId']==3){
										$viewUrl = "post-vertical";
									}else{
										$viewUrl = "post-horizontal";
									}
								}
								else
								{
									if($currentBoxData['settingId']==3){
										$viewUrl = "pre-vertical";
									}else{
										$viewUrl = "pre-horizontal";
									}
								}
								$displayCustomizationUrl = $baseUrl;
								$catTitles = str_replace( "-","~",$currentBoxData["category_title"] );
								$catTitle = str_replace( " ","-",$catTitles );
								$catHashName = substr( $currentBoxData["user_hashname"],1 );
								$catImageUrl=explode(".",$currentBoxData["category_image"]);
								$userImageUrl=$currentBoxData["image"];
								$catImageUrll=$catImageUrl[0];
								$displayCustomizationUrl .= "/databox/" . $viewUrl . "/" . $currentBoxData["category_id"] . "+" . $catImageUrll . "+" . $catHashName . "+" . $catTitle;?>
								
				    <div id="divDatabox-1" class="divCard" draggable="true">
                        <div id="divDatabox-1-imageWrapper" class="divCardImageWrapper img_center">
							<?php if( $showMcNsfwPopup ){  ?><a href="javascript:void(0)" onClick='Javascript:displayNsfwMc(<?php echo $currentBoxData["category_id"]; ?>,"<?php echo $currentBoxData["user_hashname"]?>","<?php echo $currentBoxData["category_title"]; ?>",<? echo $currentBoxData["settingId"]?>,"<? echo $catImageUrll?>");'><img src="<?php echo $basePath; ?>/images/social_media/mature_content.jpg"  /></a>
							<?php } else { ?>
                            <a href="<?php echo $displayCustomizationUrl; ?>"><img id="Databox-1-img" class="" alt="<?php echo $currentBoxData["user_hashname"]; ?>" src="<?php echo $basePath.'/images/project/categoryImages/'.$currentBoxData["category_image"]; ?>"/></a>
							<?php } ?>
                            <div id="divDatabox-1-hashtag" class="divCardHashtag hash_tag_color">
                              <a href="<?php echo $displayCustomizationUrl; ?>"><h3 class="hashtagh2_size"><b><?php echo $currentBoxData["user_hashname"];?></b></h3></a>
                            </div>

                            <div id="divDatabox-1-sharedLinks" class="divCardSharedLinks">
                                <span class="fatFont"><?php if($currentBoxData["user_classification"]!="") { echo $currentBoxData["categoryLinksCount"];?> HOT LINKS </span><?php echo $currentBoxData["user_classification"];  }else{ ?><?php echo $currentBoxData["categoryLinksCount"]; ?> HOT LINKS</span> collected and shared<?php } ?>
                            </div>
                           <!-- <div id="Card-1-user" class="divCardUser">
							<div class="divCardUserName">By: <?php echo $currentBoxData["display_name"];?></div>
								<?php if($currentBoxData["montage_image"]!=""){?>
                               <div class="pdatabox_profile">
								<img  src="<?php echo $basePath; ?>/images/project/montageImages/<?php echo $currentBoxData["montage_image"];?>" class="imgUserImage" alt="" />
							   </div><br/>
								<?php } ?>
								<div id="likes<?php echo $currentBoxData["category_id"];?>" class="divCardUserName likes_percentage"><h2><?php echo round($currentBoxData["likes"],2);?>% liked</h2></div>
                            </div>-->
							<div class="divCardLoveTrash<?php echo $currentBoxData["category_id"];?>" id="divCardLoveTrash<?php echo $currentBoxData["category_id"];?>">
								<div class="divbrg_f" onClick="return likeDislikeCnt('<?php echo $currentBoxData["category_id"];?>','1','1');"><?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?> <img src="<?php echo $basePath; ?>/img/love.png" alt="" width="15px"/></div>
								<div class="divbrg_s" onClick="return likeDislikeCnt('<?php echo $currentBoxData["category_id"];?>','0','1');"><?php if($currentBoxData["voteDown"]!=""){echo $currentBoxData["voteDown"];}else{ echo "0";}?> <a href="Javascript:void(0);" ><img src="<?php echo $basePath; ?>/img/trash.png" alt="" width="10px"/></a></div>
								<input type="hidden" id="voting<?php echo $currentBoxData["category_id"];?>" name="voting<?php echo $currentBoxData["category_id"];?>" value="<?php if($currentBoxData["userVoteUp"]!=""){echo $currentBoxData["userVoteUp"];}else{ echo "3";}  ?>">

							</div>
							<div style="clear:both;"></div>
                        </div>
                        <div id="divDatabox-1-contentWrapper" class="divCardContentWrapper">
						<div>
                            <div id="divDatabox-1-views" class="" align="center">
                                <img src="<?php echo $basePath; ?>/img/views.png" alt="" /> <?php if($currentBoxData["views_count"]!=""){echo $currentBoxData["views_count"]; }else { echo "0"; } ?> views
                            </div>
							<!--<span><?php echo round($currentBoxData["likes"],2);?>% liked</span>-->
                            <!--<div id="divCardLoveTrash<?php echo $currentBoxData["category_id"];?>" class="divCardLoveTrash love_trash_color">
								<?php //if((isset($_SESSION['usersinfo']->userId )&& $currentBoxData["userVoteId"]==$_SESSION['usersinfo']->userId) || $currentBoxData["userVoteId"]==$_SERVER['REMOTE_ADDR']){
									//if($currentBoxData["userVoteUp"]=='1'){?>
									<img src="<?php echo $basePath; ?>/img/love_ok.png" alt="" />  or  <a href="Javascript:void(0);" onClick="return likeDislikeCnt('0','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"><img src="<?php echo $basePath; ?>/img/trash.png" alt="" /></a>
									<?php
									//}else if($currentBoxData["uservoteDown"]=='1'){?>
									<a href="Javascript:void(0);" onClick="return likeDislikeCnt('1','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"><img src="<?php echo $basePath; ?>/img/love.png" alt="" /></a>  or  <img src="<?php echo $basePath; ?>/img/love_ok.png" alt="" />
									<?php
									//}}else{
									?>
									<a href="Javascript:void(0);" onClick="return likeDislikeCnt('1','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"><img src="<?php echo $basePath; ?>/img/love.png" alt="" /></a>  or  <a href="Javascript:void(0);" onClick="return likeDislikeCnt('0','<?php echo $currentBoxData["category_id"];?>','1','<?php if($currentBoxData["voteUp"]!=""){echo $currentBoxData["voteUp"];}else{ echo "0";}?>','<?php if($currentBoxData["rw_lh"]!=""){echo $currentBoxData["rw_lh"];}else{ echo "0";}?>');"><img src="<?php echo $basePath; ?>/img/trash.png" alt="" /></a>
									<?php
									//}
								?>
                            <input type="hidden" id="voting<?php echo $currentBoxData["category_id"];?>" name="voting<?php echo $currentBoxData["category_id"];?>" value="<?php if($currentBoxData["userVoteUp"]!=""){echo $currentBoxData["userVoteUp"];}else{ echo "3";}  ?>">

							</div>-->
                        </div>
							<?php if($currentBoxData["category_title"]!=""){?>
                            <div id="divDatabox-1-title" class="divCardTitle">
                                <h2 class="home_title_d"><?php echo $currentBoxData["category_title"];?></h2>
                            </div>
							<?php } ?>
							<?php if($currentBoxData["meta_tags"]!=""){?>
							 <div id="divCardKeywords" class="divCardKeywords">
								<h3 class="home_keyword_h3"><b>Keywords: </b><?php echo $currentBoxData["meta_tags"];?></h3>
							 </div>
							 <?php } ?>
							 <?php if($currentBoxData["category_description"]!=""){?>
                            <div id="divDatabox-1-description" class="divCardDescription home_de_brg_t home_title_des_s">
							<?php if($currentBoxData["category_description"]!=""){
								if(strlen($currentBoxData["category_description"])>155)
								{
									echo substr($currentBoxData["category_description"],0,155) . '...';
								}
								else
								{
									echo $currentBoxData["category_description"];
								}
							}?>
                            </div>
							<?php } ?>
                        </div>
                    </div>
						<?php } }else{ echo '<div>NOT FOUND </div>';}}?>
                </div>
				
				</div>
				<!-- Members start -->
				<div id="memCollectionBoxesDiv" style="display:none;">
					<div id="divDataboxWrapper" class="divCardsWrapper" data-columns>
					<?php
					if( isset($this->homeMontageBoxesArray) )
					{
					if(count($this->homePublicBoxesArray)!="0"){
	
					foreach( $this->homeMontageBoxesArray as $key=>$currentBoxData )
					{
					//echo "<pre>";print_r($currentBoxData);
					$viewUrl = "user-collection";
					$displayUserCollectionUrl = $baseUrl;
					$displayUserCollectionUrl .= "/" . $viewUrl . "/" . $currentBoxData["user_id"];?>
					<div id="divDatabox-1" class="divCard">
                        <div id="divDatabox-1-imageWrapper" class="divCardImageWrapper img_center">
							<?php 
							$montageHashName="";
								if( ! is_null($currentBoxData["montage_hash_name"]) && $currentBoxData["montage_hash_name"] != "" )
								{
								if(strlen($currentBoxData["montage_hash_name"])>25)
								{
								$montageHashName = substr($currentBoxData["montage_hash_name"],0,25) . '...';
								}
								else
								{
								$montageHashName = $currentBoxData["montage_hash_name"];
								}}
							if( ! is_null($currentBoxData["montage_main_image"]) && $currentBoxData["montage_main_image"] != "" )
							{
								$memberDisplayImage = $basePath.'/images/project/montageMainImage/'.$currentBoxData["montage_main_image"];
							}else{
										if(strpos($currentBoxData["montage_image"], "https://") !== false || strpos($currentBoxData["montage_image"], "http://") !== false) 
									   { 
											   $memberDisplayImage=$currentBoxData["montage_image"];
									   }else{
											$memberDisplayImage = $basePath.'/images/project/montageImages/'.$currentBoxData["montage_image"];
									   }
									
							}
							?>
                            <a href="<?php echo $displayUserCollectionUrl; ?>" onClick="Javascript:displayUserCollection(<?php echo $currentBoxData["user_id"]; ?>)" >
							<img id="Databox-1-img" class="" alt="<?php echo $montageHashName; ?>" src="<?php echo $memberDisplayImage; ?>"/>
							<?php if( ! is_null($currentBoxData["montage_hash_name"]) && $currentBoxData["montage_hash_name"] != "" ){?>
							<div id="divDatabox-1-hashtag" class="divCardHashtag">
								<h2 class="hashtagh2_size">#<?php echo $montageHashName; ?></h2>
                            </div>
							<?php } ?>
							</a>
                            <div id="divDatabox-1-sharedLinks" class="divCardSharedLinks" style="bottom:21px;">
                                <span class="fatFont"><?php echo $currentBoxData["userWiseLinksCount"];?> HOT LINKS</span> collected and shared
                            </div>
                            <div id="Card-1-user" class="divCardUser">
								<?php if($currentBoxData["image"]!=""){?>
                                <img  src="<?php echo $currentBoxData["image"];?>" class="imgUserImage" alt="" />
								<?php } ?>
                                <div class="divCardUserName">By: <?php echo $currentBoxData["display_name"];?></div>
                            </div>
                        </div>
                        <div id="divDatabox-1-contentWrapper" class="divCardContentWrapper">
                           <!-- <div id="divDatabox-1-views" class="divCardViews">
                                <img src="<?php echo $basePath; ?>/img/views.png" alt="" /> 120 views
                            </div>
                            <div class="divCardLoveTrash">
                                <a href="#"><img src="<?php echo $basePath; ?>/img/love.png" alt="" /></a>  or  <img src="<?php echo $basePath; ?>/img/trash.png" alt="" />
                            </div>-->
                            <!-- <div id="divCardKeywords" class="divCardKeywords"><?php //echo $currentBoxData["meta_tags"];?></div>-->

                            <div id="divDatabox-1-title" class="divCardTitle">
									<?php $montageTitle = "";
									if( ! is_null($currentBoxData["montage_title"]) && $currentBoxData["montage_title"] != "" )
									{
										if(strlen($currentBoxData["montage_title"])>57)
										{
											$montageTitle = substr($currentBoxData["montage_title"],0,57) . '...';
										}
										else
										{
											$montageTitle = $currentBoxData["montage_title"];
										}
									}?>
                                <h2 class="home_title_d"><?php echo $montageTitle;?></h2>
                            </div>
                            <div id="divDatabox-1-description" class="divCardDescription home_title_des_s">
								<?php
									if( ! is_null($currentBoxData["montage_paragraph"]) && $currentBoxData["montage_paragraph"] != "" )
									{
										if(strlen($currentBoxData["montage_paragraph"])>155)
										{?>
											
												<?php // echo $montageTitle = substr($currentBoxData["montage_paragraph"],0,155) . '...';?>
										<?php }
										else
										{
											// echo $montageTitle = $currentBoxData["montage_paragraph"];
										}
									}
								?>
                            </div>
                        </div>
                    </div>
					<?php } }else{ echo "<div>Not Found The Mumbers</div>";}}?>
					</div>
					</div>
                </div>
            </section>
			</div>
		</div>
    </body>
</html>
<script>
	$(document).ready(function() {
		if($("#searchTermHolder").val()!=""){
			$("#homeSearchLink" ).click();
		}
		$('body').css('background','#f8f8f8');
	});
</script>