
<div class="body_main_container mycolleection_bottom_bg pos_relative cat_top">
	<div class="body_middle_container body_mar_b">
		<div class="pos_absolute tg_media_b">
			<div class="">
			<?
				$value=0;
				if($this->totalDataboxes>=10){
					$value=$this->totalDataboxes;
				}else{
					$value='0'.$this->totalDataboxes;
				}
			?>
				<p><span class="medium_collection">MEMBER COLLECTIONS</span><span class="media_count">&nbsp;<? echo '('.$value.'  Public)';?></span><span class="media_private_boxes"></span></P>
			</div>
		</div>
	</div>
</div>
<div class="body_main_container" style="margin-bottom:80px;">
	<div class="body_middle_container body_mar_b">
		<?foreach($this->dashboard as $key=>$dashboard){$count=0;?>
			<input type="hidden" id="totalCount<?echo $key;?>" name="totalCount<?echo $key;?>" value="<?echo $dashboard['totalLinks'];?>">
			<div class="tg_montage_t">
				<div class="text_row">
					<div class="float_l"><h3><?echo $dashboard['user_hashname']?><span>&nbsp;(<?echo $dashboard['totalLinks']?>/100)</span></h3></div>
					<div class="float_r"><P><?echo $dashboard['category_title']?></P></div>
				</div><div class="clearfix"></div>
			</div>
			<div class="pos_relative colman_min_h">
				<div class="montage_row" id="montageRow<?echo $key;?>">
				<?foreach($dashboard['links'] as $links){
					$count++;
				if($count<=7){
					$link=explode('***',$links);
					?>
					<div class="column1">
						<p><?echo substr($link[0],0,22) . '...';$url = $link[0];?></p>
						<div><a href="<?php echo $url; ?>" target="_blank"><img src="<?php echo $link[2]; ?>"/></a></div>
					</div>
				<?}}?>
				</div>
				<div class="text_row Previous">
					<div class="float_l" id="prevPagination<?echo $key;?>" style="display:none">
						<a href="javascript:void(0);" onclick="paginationLinks('0',<?echo $key;?>)" >
							<img src="<?php echo $basePath; ?>/images/social_media/leftarrow.png"/>&nbsp;Previous
						</a>
					</div>
					<?if($dashboard['totalLinks']>7){?>
					<div class="float_r" id="nextPagination<?echo $key;?>">
						<a href="javascript:void(0);" onclick="paginationLinks('1',<?echo $key;?>)">Next&nbsp;
							<img src="<?php echo $basePath; ?>/images/social_media/rightarrow.png"/>
						</a>
					</div>
					<?}?>
				</div>
				<div class="clearfix"></div>
					<div class="pos_absolute montage_social_network_b">
						<div class="montage_social_network_btn">
							<p style="width:90px;"><img class="img_top" src="<?php echo $basePath; ?>/images/social_media/rightmark.png"/>&nbsp;relevance
								<b class="pos_absolute" id="relevanceDiv<?php echo $key; ?>">
									<?php
										if( $dashboard['categoryRelevance'] == 0 )
										{
									?>
											<a href="JavaScript:void(0);" onClick="voteRelevance(1,<?php echo $key; ?>);" ><img class="upparrow" src="<?php echo $basePath; ?>/images/social_media/upparrow.png" /></a>
											<img class="downarrow" src="<?php echo $basePath; ?>/images/social_media/downarrow.png" />
									<?php
										}
										else if( $dashboard['categoryRelevance'] == 1 )
										{
									?>
											<img class="upparrow" src="<?php echo $basePath; ?>/images/social_media/upparrow_disable.png" />
											<a href="JavaScript:void(0);" onClick="voteRelevance(0,<?php echo $key; ?>);"><img class="downarrow" src="<?php echo $basePath; ?>/images/social_media/downarrow_enable.png" /></a>
									<?php
										}
										else if( $dashboard['categoryRelevance'] == 2 )
										{
									?>
											<a href="JavaScript:void(0);" onClick="voteRelevance(1,<?php echo $key; ?>);" ><img class="upparrow" src="<?php echo $basePath; ?>/images/social_media/upparrow.png" /></a><br/>
											<a href="JavaScript:void(0);" onClick="voteRelevance(0,<?php echo $key; ?>);"><img class="downarrow" src="<?php echo $basePath; ?>/images/social_media/downarrow_enable.png" /></a>
									<?php
										}
									?>
								</b>
							</p>
							<p style="width:70px;"><img class="img_top" src="<?php echo $basePath; ?>/images/social_media/star.png"/>&nbsp;worth
								<b class="pos_absolute" id="worthDiv<?php echo $key; ?>">
									<?php
										if( $dashboard['categoryWorth'] == 0 )
										{
									?>
											<a href="JavaScript:void(0);" onClick="voteWorth(1,<?php echo $key; ?>);" ><img class="upparrow" src="<?php echo $basePath; ?>/images/social_media/upparrow.png" /></a>
											<img class="downarrow" src="<?php echo $basePath; ?>/images/social_media/downarrow.png" />
									<?php
										}
										else if( $dashboard['categoryWorth'] == 1 )
										{
									?>
											<img class="upparrow" src="<?php echo $basePath; ?>/images/social_media/upparrow_disable.png" />
											<a href="JavaScript:void(0);" onClick="voteWorth(0,<?php echo $key; ?>);"><img class="downarrow" src="<?php echo $basePath; ?>/images/social_media/downarrow_enable.png" /></a>
									<?php
										}
										else if( $dashboard['categoryWorth'] == 2 )
										{
									?>
											<a href="JavaScript:void(0);" onClick="voteWorth(1,<?php echo $key; ?>);" ><img class="upparrow" src="<?php echo $basePath; ?>/images/social_media/upparrow.png" /></a><br/>
											<a href="JavaScript:void(0);" onClick="voteWorth(0,<?php echo $key; ?>);"><img class="downarrow" src="<?php echo $basePath; ?>/images/social_media/downarrow_enable.png" /></a>
									<?php
										}
									?>
								</b>
							</p>
							<?if(isset($_SESSION['usersinfo']->userId)){?>
								<p style="width:80px;">
								<img class="img_top" src="<?php echo $basePath; ?>/images/social_media/eye.png"/>&nbsp;<a href="javascript:void(0);" onclick="reportPopUp(<?php echo $key; ?>,<?echo $dashboard['user_id'];?>)">report</a>
								</p>
							<?}?>
						</div>
					</div>
			</div>
			<?}?>


			
	</div>
</div>
<input type="hidden" id="presentCount" name="presentCount" value="7">

<div id="pop-up-1" class="pop-up-display-content">
<h1 class="tg_users_title">Login Using one of your Social network</h1>
<div class="tg_users_socila_login">
<?php
	echo '<div class="pp-lg-buttons">';
	foreach ($this->options->getEnabledProviders() as $provider) {
		echo  $this->socialSignInButton($provider, $this->redirect);
	}
	echo '</div>';
?>
	<!--<img src="<?php echo $basePath; ?>/images/social_media/facebook.png"/>
	<img src="<?php echo $basePath; ?>/images/social_media/google+.png"/>-->
</div>

<input type="hidden" id="basePath" name="basePath" value="<?php echo $basePath;?>" />
<input type="hidden" id="baseUrl"  name="baseUrl" value="<?php echo $baseUrl;?>" />
<input type="hidden" id="hid_userid"  name="baseUrl" />
<input type="hidden" id="hid_cat_id"  name="baseUrl" />

<div class="tg_users_email_login">
	<h1>Or</h1>
	<h1>Your email ID</h1>
	<div class="tg_create_email">
		<form class="" method="post" id="userLoginFormUrl" name="userLoginFormUrl" role="form">
			<input type="hidden" id="categoryHighlight" name="categoryHighlight" value="0" />
			<p>Email ID</p>
			<input type="text" class="text_pad" name="emailId" id="emailId"/>
			<p>Password</p>
			<input type="password" class="text_pad" name="userPassword" id="userPassword"/>
			<p class="tg_email_btn"><a href="javascript:void(0)" class="btn" onClick="Javascript:checkLogin();">CONTINUE</a></p>
			<span id="userMessage" style="display:none;">Checking Username,Password...</span>
		</form>
	</div>
</div>
</div>
<div id="pop-up-report" class="pop-up-display-content conform_popup_content">
	<div class="montage_desc">
		<p>Please provide your Report</p>
		<p><textarea type="text" class="text_pad" name="report_text"  id="report_text" ></textarea></p>
	</div>
	<p>
		<a class="larg_btn" href="javascript:void(0);" onclick="sendReportClose()">CANCEL</a>
		<a class="larg_btn" href="javascript:void(0);" onclick="sendReport()">CONTINUE</a>
	</p>
	<p id="reportMessageSend"></p>
</div>
<input type="hidden" id="report_id_hid" name="report_id_hid" value="0">