<div class="body_main_container cat_top">
	<div class="body_middle_container">
		<div class=" form_top">
			<div class="row">
				<center><h3>Privacy Policy</h3></center>
				<br/>
				<p align="justify">
This privacy policy has been compiled to better serve those who are concerned with how their 'Personally identifiable information' (PII) is being used online. PII, as used in US privacy law and information security, is information that can be used on its own or with other information to identify, contact, or locate a single person, or to identify an individual in context. Please read our privacy policy carefully to get a clear understanding of how we collect, use, protect or otherwise handle your Personally Identifiable Information in accordance with our website.
				</p>
				<br/><br/>
				
				<p align="justify">
<strong>What personal information do we collect from the people that website or app?</strong>
				</p>
				<br/>
				<p align="justify">
When registering on our site, as appropriate, you may be asked to enter your name, email address, nickname/alias to help you with your experience.
				</p>
				<br/>
				
				<p align="justify">
<strong>When do we collect information?</strong>
				</p>
				<br/>
				<p align="justify">
We collect information from you when you register on our site or enter information on our site.
				</p>
				<br/>
				
				<p align="justify">
<strong>How do we use your information?</strong>
				</p>
				<br/>
				<p align="justify">
We may use the information we collect from you when you register, surf the website, or use certain other site features in the following ways:
				</p>
				<br/>
				<ul style="margin-left:35px;">
					<li>To personalize user's experience and to allow us to deliver the type of content users willing to share and interested.</li>
					<li>To improve our website in order to serve you better.</li>
					<li>To administer a contest, promotion, survey or other site feature.</li>
				</ul>
				<br/>
				
				<p align="justify">
<strong>How do we protect visitor information?</strong>
				</p>
				<br/>
				<p align="justify">
Our website is scanned on a regular basis for security holes and known vulnerabilities in order to make your visit to our site as safe as possible.
				</p>
				<br/>
				<p align="justify">
Your personal information is contained behind secured networks and is only accessible by a limited number of persons who have special access rights to such systems, and are required to keep the information confidential. In addition, all sensitive information you supply is encrypted via Secure Socket Layer (SSL) technology.
				</p>
				<br/>
				<p align="justify">
We implement a variety of security measures when a user enters, submits, or accesses their information to maintain the safety of your personal information.
				</p>
				<br/>
				
				<p align="justify">
<strong>Do we use 'cookies'?</strong>
				</p>
				<br/>
				<p align="justify">
Yes. Cookies are small files that a site or its service provider transfers to your computer's hard drive through your Web browser (if you allow) that enables the site's or service provider's systems to recognize your browser and capture and remember certain information. For instance, we use cookies to help us remember and process your activity. They are also used to help us understand your preferences based on previous or current site activity, which enables us to provide you with improved services. We also use cookies to help us compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future.
				</p>
				<br/>
				<p align="justify">
<strong>We use cookies to:</strong>
				</p>
				<ul style="margin-left:35px;">
					<li>Understand and save user's preferences for future visits.</li>
				</ul>
				<br/>
				<p align="justify">
You can choose to have your computer warn you each time a cookie is being sent, or you can choose to turn off all cookies. You do this through your browser (like Internet Explorer) settings. Each browser is a little different, so look at your browser's Help menu to learn the correct way to modify your cookies.
				</p>
				<br/>
				<p align="justify">
If you disable cookies off, some features will be disabled It won't affect the users experience that make your site experience more efficient and some of our services will not function properly.
				</p>
				<br/>

				<br/>
				<p align="justify">
<strong>Third Party Disclosure</strong>
				</p>
				<br/>
				<p align="justify">
Facebook and Google Plus Third party sessions are used; therefore their applications are used as medium in order to perform successful accessing and activity in our website.
				</p>
				<br/>
				
				<p align="justify">
<strong>Third party links</strong>
				</p>
				<br/>
				<p align="justify">
Occasionally, at our discretion, we may include or offer third party products or services on our website. These third party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.
				</p>
				<br/>
				
				<br/>
				<p align="justify">
<strong>Google</strong>
				</p>
				<br/>
				<p align="justify">
<strong>We have implemented the following:</strong>
				</p>
				<ul style="margin-left:35px;">
					<li>Demographics and Interests Reporting</li>
				</ul>
				<br/>
				<p align="justify">
We along with third-party vendors, such as Google use first-party cookies (such as the Google Analytics cookies) and third-party cookies (such as the DoubleClick cookie) or other third-party identifiers together
				</p>
				<br/>
				
				<br/>
				<p align="justify">
<strong>Web Traffic Analyzing</strong>
				</p>
				<br/>
				<p align="justify">
Opting out:
				</p>
				<p align="justify">
Users can set preferences for how Google advertises to you using the Google Ad Settings page. Alternatively, you can opt out by visiting the Network Advertising initiative opt out page or permanently using the Google Analytics Opt Out Browser add on.
				</p>
				<br/>
				
				<p align="justify">
<strong>California Online Privacy Protection Act</strong>
				</p>
				<br/>
				<p align="justify">
CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law's reach stretches well beyond California to require a person or company in the United States (and conceivably the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy. - See more at:
				</p>
				<p align="justify">
http://consumercal.org/california-online-privacy-protection-act-caloppa/#sthash.0FdRbT51.dpuf
				</p>
				<br/>
				
				<p align="justify">
<strong>According to CalOPPA we agree to the following:</strong>
				</p>
				<p align="justify">
Users can visit our site anonymously
				</p>
				<p align="justify">
Once this privacy policy is created, we will add a link to it on our home page, or as a minimum on the first significant page after entering our website.
				</p>
				<p align="justify">
Our Privacy Policy link includes the word 'Privacy', and can be easily be found on the page specified above.
				</p>
				<br/>
				<p align="justify">
Users will be notified of any privacy policy changes:
				</p>
				<ul style="margin-left:35px;">
					<li>On our Privacy Policy Page</li>
				</ul>
				<p align="justify">
Users are able to change their personal information:
				</p>
				<ul style="margin-left:35px;">
					<li>By logging in to their account</li>
				</ul>

				<br/>
				<p align="justify">
<strong>How does our site handle do not track signals?</strong>
				</p>
				<p align="justify">
We honor do not track signals and do not track, plant cookies, or use advertising when a Do Not Track (DNT) browser mechanism is in place.
				</p>
				<br/>

				<p align="justify">
<strong>Does our site allow third party behavioral tracking?</strong>
				</p>
				<p align="justify">
It's also important to note that we allow third party behavioral tracking
				</p>
				<br/>
				
				<p align="justify">
<strong>COPPA (Children Online Privacy Protection Act)</strong>
				</p>
				<br/>
				<p align="justify">
When it comes to the collection of personal information from children under 13, the Children's Online Privacy Protection Act (COPPA) puts parents in control. The Federal Trade Commission, the nation's consumer protection agency, enforces the COPPA Rule, which spells out what operators of websites and online services must do to protect children's privacy and safety online.
				</p>
				<br/>
				<p align="justify">
We do not specifically market to children under 13.
				</p>
				<br/>

				<p align="justify">
<strong>Fair Information Practices</strong>
				</p>
				<br/>
				<p align="justify">
The Fair Information Practices Principles form the backbone of privacy law in the United States and the concepts they include have played a significant role in the development of data protection laws around the globe. Understanding the Fair Information Practice Principles and how they should be implemented is critical to comply with the various privacy laws that protect personal information.
				</p>
				<br/>
				
				<p align="justify">
<strong>In order to be in line with Fair Information Practices we will take the following responsive action, should a data breach occur:</strong>
				</p>
				<br/>
				<ul style="margin-left:35px;">
					<li>Within 7 business days</li>
				</ul>
				<p style="text-align:justify;margin-left:20px;">
We will notify the users via in site notification
				</p>
				<br/>
				<ul style="margin-left:35px;">
					<li>Within 7 business days</li>
				</ul>
				<br/>
				<p align="justify">
We also agree to the individual redress principle, which requires that individuals have a right to pursue legally enforceable rights against data collectors and processors who fail to adhere to the law. This principle requires not only that individuals have enforceable rights against data users, but also that individuals have recourse to courts or a government agency to investigate and/or prosecute non-compliance by data processors.
				</p>
				<br/>
				<br/>
				
				<p align="justify">
<strong>Contacting Us</strong>
				</p>
				<br/>
				<p align="justify">
If there are any questions regarding this privacy policy you may contact us using the information below.
				</p>
				<br/>
				<p align="justify">
taggerzz.com
				</p>
				<p align="justify">
Bangalore, Karnataka
				</p>
				<p align="justify">
India
				</p>
				<p align="justify">
560027
				</p>
				<p align="justify">
Taggerzz(.)com(@)gmail(.)com
				</p>
				<br/>
				<br/>
			</div>
		</div>
	</div>
</div>

<input type="hidden" id="basePath" name="basePath" value="<?php echo $basePath;?>" />
<input type="hidden" id="baseUrl"  name="baseUrl" value="<?php echo $baseUrl;?>" />

<script type="text/javascript" src="<?php echo $basePath; ?>/js/project/login-ready.js"></script>
