<link href="<?php echo $basePath; ?>/css/default.css" rel="stylesheet" type="text/css" />
	<div class="montage_container">
	<div>
	<div class="mycolleection dash_pick_bg">
	
	<div class="" style="margin-top:1px;">
		<div class="">
			<?
			$ucDispImage = "";
			if( ! is_null($this->montageMainImage) && $this->montageMainImage != "" )
			{
				if(strpos($this->montageMainImage, "https://") !== false || strpos($this->montageMainImage, "http://") !== false)
				{
					$ucDispImage=$this->montageMainImage;
				}
				else
				{
					$ucDispImage=$basePath.'/images/project/montageMainImage/'.$this->montageMainImage;
				}
			}
			else if( ! is_null($this->montageImage) && $this->montageImage != "" )
			{
				if(strpos($this->montageImage, "https://") !== false || strpos($this->montageImage, "http://") !== false)
				{
					$ucDispImage=$this->montageImage;
				}
				else
				{
					$ucDispImage=$basePath.'/images/project/montageImages/'.$this->montageImage;
				}
			}
			if( $ucDispImage == "" )
			{
				$ucDispImage = $basePath.'/images/social_media/profile_img.png';
			}?>
			<div class="dash_board_profile_pick">
					<img src="<?php echo $ucDispImage; ?>">
			</div>
				<!-- Hash tag Start-->
		<div id="hash_name" align="center">
		<?if($this->montageHashName==""){$montage_hash_name="";?>
		<div class="">
			<h1>#MONTAGE
			<?if( isset($_SESSION['usersinfo']->userId) && $_SESSION['usersinfo']->userId==$this->ucUserId){?>
			<a href="javascript:void(0);" onclick="montagePopUp(1)" class="add_new_pick">ADD YOURS</a>
			</h1>
		</div>
			<?}}else{
				$montage_hash_name=$this->montageHashName;
				if(strlen($montage_hash_name)>30){
					$montageLength=substr($montage_hash_name,0,30) . '..'; 
				}else{
					$montageLength=$montage_hash_name; 
				}
			?>
		<div>
			<h1>#<?echo $montageLength;?>
				<?if( isset($_SESSION['usersinfo']->userId) && $_SESSION['usersinfo']->userId==$this->ucUserId){?>
				<a href="javascript:void(0);" onclick="montagePopUp(1)" title="Edit hash name" class="add_new_pick">EDIT</a>
				<?}}?>
			</h1>
		</div>
		</div>
		<div class="clearfix"></div>
		<!-- Hash tag End-->
		<!-- title Start-->
		
		<div  id="your_title" class="montage_tit_show" align="center"> 
		<?if($this->montageTitle==""){$montage_title="";?>
		<?if( isset($_SESSION['usersinfo']->userId) && $_SESSION['usersinfo']->userId==$this->ucUserId){?>
		<h2><a href="javascript:void(0);" onclick="montagePopUp(2)" class="add_title">Add your Title here</a></h2>
		<? }else { ?><h2>&nbsp;</h2>
		<?}}else{
			$montage_title=$this->montageTitle;
		?>
		<h2><?if( isset($_SESSION['usersinfo']->userId) && $_SESSION['usersinfo']->userId==$this->ucUserId){?><span> <?echo $montage_title;?><a href="javascript:void(0);" onclick="montagePopUp(2)" class="add_new_pick">&nbsp;&nbsp;&nbsp;&nbsp;EDIT TITLE</a></span><? }else { ?><span> <?echo $montage_title; ?></span><?} ?></h2>
		<?}
			if( $montage_title != "" )
			{
				if( $montage_hash_name != "" )
				{
					global $layoutTitle;
					$layoutTitle = $montage_hash_name . " | " . $montage_title . " - Taggerzz";
				}
				else
				{
					global $layoutTitle;
					$layoutTitle = $montage_title . " - Taggerzz";
				}
			}
			else if( $montage_hash_name != "" )
			{
				global $layoutTitle;
				$layoutTitle = $montage_hash_name . " - Taggerzz";
			}
			else
			{
				global $layoutTitle;
				$layoutTitle =  "Taggerzz - Collect.Connect.Tag and Share your Web-Data with Everyone and Any one";
			}
		?>
		</div> 
	<!-- Title End -->		
	</div>			
				<div id="your_paragraph" class="dashboard_img_paragrap">
					<?if($this->montageParagraph==""){
						$montage_paragraph="";
					?>
					<div class="profile_text_empty">
							<div id="montagPara_Div_id1" class="montage_Paragraph_show"><?if( isset($_SESSION['usersinfo']->userId) && $_SESSION['usersinfo']->userId==$this->ucUserId){?><a href="javascript:void(0);" title="Edit your paragraph" onclick="montagePopUp(3)"><? } ?><img src="<?php echo $basePath; ?>/images/social_media/profile_empty.png" class="edit_paragraph_mon_empty"/><?if( isset($_SESSION['usersinfo']->userId) && $_SESSION['usersinfo']->userId==$this->ucUserId){?></a><p>Set your Profile Description</p><? } else { ?><p>&nbsp;</p><? } ?></div>
					</div>
					<?}else{
						$montage_paragraph=$this->montageParagraph;
					?>
					<div class="">
						<div id="montagPara_Div_id" class="montage_Paragraph_show"><P><?echo $this->montageParagraph?><?if( isset($_SESSION['usersinfo']->userId) && $_SESSION['usersinfo']->userId==$this->ucUserId){?><span><a href="javascript:void(0);" title="Edit your paragraph" onclick="montagePopUp(3)" class="edit_paragraph_mon_empty">EDIT</a></SPAN><? } ?></P></div>
					</div>
					<?}?>
				</div>
		</div>
	</div>

<div class="clearfix"></div>
	
	
	
	
	
	
	
	
	
	
		<div class="tmar_t20">
	<div class="body_mar_b">
		<div class="body_mar_b">
		<?php if($this->dashboard!=""){?>
		<?foreach($this->dashboard as $key=>$dashboard){$count=0;
		$viewUrl = "";
				if( isset($_SESSION['usersinfo']) )
				{
					if($dashboard['settingId']==3){
						$viewUrl = "post-vertical";
					}else{
						$viewUrl = "post-horizontal";
					}
				}
				else
				{
					if($dashboard['settingId']==3){
						$viewUrl = "pre-vertical";
					}else{
						$viewUrl = "pre-horizontal";
					}
				}
				$displayCustomizationUrl = $baseUrl;
				$catTitles = str_replace( "-","~",$dashboard["category_title"] );
				$catTitle = str_replace( " ","-",$catTitles );
				$catHashName = substr( $dashboard["user_hashname"],1 );
				$catImageUrl=explode(".",$dashboard["category_image"]);
				//$userImageUrl=$dashboard["image"];
				$userImageUrl=$dashboard["category_image"];
				
				$catImageUrll=$catImageUrl[0];
				$displayCustomizationUrl .= "/databox/" . $viewUrl . "/" . $dashboard["category_id"] . "+" . $catImageUrll . "+" . $catHashName . "+" . $catTitle;

		?>
			<input type="hidden" id="totalCount<?echo $key;?>" name="totalCount<?echo $key;?>" value="<?echo $dashboard['totalLinks'];?>">
			<input type="hidden" id="presentCount<?echo $key;?>" name="presentCount<?echo $key;?>" value="7">
			<div class="tg_montage_t montage_brg_box">
			<div class="montage_box_brg_title">
				<div class="text_row">
					<div class="float_l"><h3><b><a href="<?php echo $displayCustomizationUrl;?>"><?echo $dashboard['user_hashname']?></a></b><span>&nbsp;(<?echo $dashboard['totalLinks']?>/100)</span></h3></div>
					<div class="float_r"><P class="text_sub_title"><a href="<?php echo $displayCustomizationUrl;?>"><?echo $dashboard['category_title'];?></a></P></div>
				</div><div class="clearfix"></div>
			</div>
			<div class="pos_relative">
				<div class="montage_row" id="montageRow<?echo $key;?>">
				<?foreach($dashboard['links'] as $links){
					$count++;
				if($count){
					$link=explode('***',$links);
					?>
					<div class="column1">
						<div><p><?echo substr($link[0],0,20) . '...';
								$url = $link[0];
									 if(strpos($url, "https://") !== false || strpos($url, "http://") !== false){
								$url=$url;
							}
							else{
								$url='http://'.$url;
							}
							$imageLink1 = getimagesize($link[2]);
							if($imageLink1[0]!="" && $imageLink1[2]!=""){
								$imageLink=$link[2];
							}else{
								$imageLink=$basePath.'/images/social_media/noimage.png';
							}
								?></p>
						<a href="<?php echo $url; ?>" target="_blank"><img src="<?php if($link[2]!=""){echo $imageLink;}else{ echo $basePath;?>/images/social_media/noimage.png<? } ?>"/></a></div>
					</div>
				<?}}?>
				</div>
				<div class="clearfix"></div>
			</div>
			</div>
			<?}}else{?>
			<div align="center">
				<h3>no donuts. <br/>No Databoxes created :/</h3>
				<a href="#" class="highlightFont createCollection create_btn" id='createCollection'><img src="<?php echo $basePath; ?>/images/social_media/databox_create.png"/></a>
				<h4>CLICK THE DONUT TO CREATE</h4>
				<h5>this particular page won’t be shown as databox <br/>
				unless you have at least 2 created public databoxes</h5>
			</div>
			<?php } ?>
		</div>
	</div>
		</div>
	</div>
</div>
<div class="clearfix"></div>
<input type="hidden" id="hid_userid"  name="baseUrl" />
<input type="hidden" id="hid_cat_id"  name="baseUrl" />
<input type="hidden" id="category_user_id" value="0" />
<input type="hidden" id="report_id_hid" name="report_id_hid" value="0">
<script>
	//$('body').css('background','#f5f5f5');
</script>


<?if( isset($_SESSION['usersinfo']->userId) && $_SESSION['usersinfo']->userId==$this->ucUserId){?>
<div id="pop-up-hash" class="pop-up-display-content conform_popup_content">
	<div class="montage_desc">
		<h4>Please provide your montage hash name</h4>
		<p><input type="text" name="montage_hash_name" class="text_pad" id="montage_hash_name" value="#<?echo $montage_hash_name;?>" /></p>
	</div>
	<p>
		<a class="btn" href="javascript:void(0);" onclick="montagePopUpClose(1)">CANCEL</a>
		<a class="btn" href="javascript:void(0);" onclick="saveMontage(1)">CONTINUE</a>
	</p>
	<p id="hashMessageError"></p>
</div>
<div id="pop-up-title" class="pop-up-display-content conform_popup_content">
	<div class="montage_desc">
		<h4>Please provide your title</h4>
		<p><input type="text" name="montage_title" class="text_pad" id="montage_title" value="<?echo $montage_title;?>"/></p>
	</div>
	<p>
		<a class="btn" href="javascript:void(0);" onclick="montagePopUpClose(2)">CANCEL</a>
		<a class="btn" href="javascript:void(0);" onclick="saveMontage(2)">CONTINUE</a>
	</p>
	<p id="titleMessageError"></p>
</div>
<div id="pop-up-paragraph" class="pop-up-display-content conform_popup_content">
	<div class="montage_desc">
		<h4>Please provide your paragraph</h4>
		<p><textarea  name="montage_paragraph" class="text_pad" id="montage_paragraph" ><?echo $montage_paragraph;?></textarea></p>
	</div>
	<p>
		<a class="btn" href="javascript:void(0);" onclick="montagePopUpClose(3)">CANCEL</a>
		<a class="btn" href="javascript:void(0);" onclick="saveMontage(3)">CONTINUE</a>
	</p>
	<p id="paragraphMessageError"></p>
</div>
<? } ?>
<input type="hidden" id="basePath" name="basePath" value="<?php echo $basePath;?>" />
<input type="hidden" id="baseUrl"  name="baseUrl" value="<?php echo $baseUrl;?>" />
<input type="hidden" id="hid_userid"  name="baseUrl" />
<input type="hidden" id="hid_cat_id"  name="baseUrl" />
<input type="hidden" id="category_user_id" value="0" />

<input type="hidden" id="report_id_hid" name="report_id_hid" value="0">
<?if( isset($_SESSION['usersinfo']->userId) && $_SESSION['usersinfo']->userId==$this->ucUserId){?>
<script type="text/javascript" src="<?php echo $basePath; ?>/js/ckeditor/ckeditor.js"></script>
<script>
$('.edit_paragraph_mon_empty').click(function() {
	CKEDITOR.replace( 'montage_paragraph', {
});
});

	$(document).ready(function () {
		$("a[id^='montagePic']").each(function(){
			$('#montagePic').click(function(event){
				$('#change_image').click();
			});
		});
	});

</script>
<? } ?>